
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `Household` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model Household
 * 
 */
export type HouseholdModel = runtime.Types.Result.DefaultSelection<Prisma.$HouseholdPayload>

export type AggregateHousehold = {
  _count: HouseholdCountAggregateOutputType | null
  _min: HouseholdMinAggregateOutputType | null
  _max: HouseholdMaxAggregateOutputType | null
}

export type HouseholdMinAggregateOutputType = {
  id: string | null
  name: string | null
  createdAt: Date | null
  ownerId: string | null
}

export type HouseholdMaxAggregateOutputType = {
  id: string | null
  name: string | null
  createdAt: Date | null
  ownerId: string | null
}

export type HouseholdCountAggregateOutputType = {
  id: number
  name: number
  createdAt: number
  ownerId: number
  _all: number
}


export type HouseholdMinAggregateInputType = {
  id?: true
  name?: true
  createdAt?: true
  ownerId?: true
}

export type HouseholdMaxAggregateInputType = {
  id?: true
  name?: true
  createdAt?: true
  ownerId?: true
}

export type HouseholdCountAggregateInputType = {
  id?: true
  name?: true
  createdAt?: true
  ownerId?: true
  _all?: true
}

export type HouseholdAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Household to aggregate.
   */
  where?: Prisma.HouseholdWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Households to fetch.
   */
  orderBy?: Prisma.HouseholdOrderByWithRelationInput | Prisma.HouseholdOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.HouseholdWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Households from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Households.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Households
  **/
  _count?: true | HouseholdCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: HouseholdMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: HouseholdMaxAggregateInputType
}

export type GetHouseholdAggregateType<T extends HouseholdAggregateArgs> = {
      [P in keyof T & keyof AggregateHousehold]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateHousehold[P]>
    : Prisma.GetScalarType<T[P], AggregateHousehold[P]>
}




export type HouseholdGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.HouseholdWhereInput
  orderBy?: Prisma.HouseholdOrderByWithAggregationInput | Prisma.HouseholdOrderByWithAggregationInput[]
  by: Prisma.HouseholdScalarFieldEnum[] | Prisma.HouseholdScalarFieldEnum
  having?: Prisma.HouseholdScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: HouseholdCountAggregateInputType | true
  _min?: HouseholdMinAggregateInputType
  _max?: HouseholdMaxAggregateInputType
}

export type HouseholdGroupByOutputType = {
  id: string
  name: string
  createdAt: Date
  ownerId: string | null
  _count: HouseholdCountAggregateOutputType | null
  _min: HouseholdMinAggregateOutputType | null
  _max: HouseholdMaxAggregateOutputType | null
}

export type GetHouseholdGroupByPayload<T extends HouseholdGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<HouseholdGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof HouseholdGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], HouseholdGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], HouseholdGroupByOutputType[P]>
      }
    >
  >



export type HouseholdWhereInput = {
  AND?: Prisma.HouseholdWhereInput | Prisma.HouseholdWhereInput[]
  OR?: Prisma.HouseholdWhereInput[]
  NOT?: Prisma.HouseholdWhereInput | Prisma.HouseholdWhereInput[]
  id?: Prisma.StringFilter<"Household"> | string
  name?: Prisma.StringFilter<"Household"> | string
  createdAt?: Prisma.DateTimeFilter<"Household"> | Date | string
  ownerId?: Prisma.StringNullableFilter<"Household"> | string | null
  owner?: Prisma.XOR<Prisma.UserNullableScalarRelationFilter, Prisma.UserWhereInput> | null
  members?: Prisma.HouseholdMemberListRelationFilter
  accounts?: Prisma.AccountListRelationFilter
  pots?: Prisma.PotListRelationFilter
}

export type HouseholdOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  ownerId?: Prisma.SortOrderInput | Prisma.SortOrder
  owner?: Prisma.UserOrderByWithRelationInput
  members?: Prisma.HouseholdMemberOrderByRelationAggregateInput
  accounts?: Prisma.AccountOrderByRelationAggregateInput
  pots?: Prisma.PotOrderByRelationAggregateInput
}

export type HouseholdWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  ownerId?: string
  AND?: Prisma.HouseholdWhereInput | Prisma.HouseholdWhereInput[]
  OR?: Prisma.HouseholdWhereInput[]
  NOT?: Prisma.HouseholdWhereInput | Prisma.HouseholdWhereInput[]
  name?: Prisma.StringFilter<"Household"> | string
  createdAt?: Prisma.DateTimeFilter<"Household"> | Date | string
  owner?: Prisma.XOR<Prisma.UserNullableScalarRelationFilter, Prisma.UserWhereInput> | null
  members?: Prisma.HouseholdMemberListRelationFilter
  accounts?: Prisma.AccountListRelationFilter
  pots?: Prisma.PotListRelationFilter
}, "id" | "ownerId">

export type HouseholdOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  ownerId?: Prisma.SortOrderInput | Prisma.SortOrder
  _count?: Prisma.HouseholdCountOrderByAggregateInput
  _max?: Prisma.HouseholdMaxOrderByAggregateInput
  _min?: Prisma.HouseholdMinOrderByAggregateInput
}

export type HouseholdScalarWhereWithAggregatesInput = {
  AND?: Prisma.HouseholdScalarWhereWithAggregatesInput | Prisma.HouseholdScalarWhereWithAggregatesInput[]
  OR?: Prisma.HouseholdScalarWhereWithAggregatesInput[]
  NOT?: Prisma.HouseholdScalarWhereWithAggregatesInput | Prisma.HouseholdScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"Household"> | string
  name?: Prisma.StringWithAggregatesFilter<"Household"> | string
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"Household"> | Date | string
  ownerId?: Prisma.StringNullableWithAggregatesFilter<"Household"> | string | null
}

export type HouseholdCreateInput = {
  id?: string
  name?: string
  createdAt?: Date | string
  owner?: Prisma.UserCreateNestedOneWithoutHouseholdInput
  members?: Prisma.HouseholdMemberCreateNestedManyWithoutHouseholdInput
  accounts?: Prisma.AccountCreateNestedManyWithoutHouseholdInput
  pots?: Prisma.PotCreateNestedManyWithoutHouseholdInput
}

export type HouseholdUncheckedCreateInput = {
  id?: string
  name?: string
  createdAt?: Date | string
  ownerId?: string | null
  members?: Prisma.HouseholdMemberUncheckedCreateNestedManyWithoutHouseholdInput
  accounts?: Prisma.AccountUncheckedCreateNestedManyWithoutHouseholdInput
  pots?: Prisma.PotUncheckedCreateNestedManyWithoutHouseholdInput
}

export type HouseholdUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  owner?: Prisma.UserUpdateOneWithoutHouseholdNestedInput
  members?: Prisma.HouseholdMemberUpdateManyWithoutHouseholdNestedInput
  accounts?: Prisma.AccountUpdateManyWithoutHouseholdNestedInput
  pots?: Prisma.PotUpdateManyWithoutHouseholdNestedInput
}

export type HouseholdUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  ownerId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  members?: Prisma.HouseholdMemberUncheckedUpdateManyWithoutHouseholdNestedInput
  accounts?: Prisma.AccountUncheckedUpdateManyWithoutHouseholdNestedInput
  pots?: Prisma.PotUncheckedUpdateManyWithoutHouseholdNestedInput
}

export type HouseholdCreateManyInput = {
  id?: string
  name?: string
  createdAt?: Date | string
  ownerId?: string | null
}

export type HouseholdUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type HouseholdUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  ownerId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type HouseholdNullableScalarRelationFilter = {
  is?: Prisma.HouseholdWhereInput | null
  isNot?: Prisma.HouseholdWhereInput | null
}

export type HouseholdCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  ownerId?: Prisma.SortOrder
}

export type HouseholdMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  ownerId?: Prisma.SortOrder
}

export type HouseholdMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  ownerId?: Prisma.SortOrder
}

export type HouseholdScalarRelationFilter = {
  is?: Prisma.HouseholdWhereInput
  isNot?: Prisma.HouseholdWhereInput
}

export type HouseholdCreateNestedOneWithoutOwnerInput = {
  create?: Prisma.XOR<Prisma.HouseholdCreateWithoutOwnerInput, Prisma.HouseholdUncheckedCreateWithoutOwnerInput>
  connectOrCreate?: Prisma.HouseholdCreateOrConnectWithoutOwnerInput
  connect?: Prisma.HouseholdWhereUniqueInput
}

export type HouseholdUncheckedCreateNestedOneWithoutOwnerInput = {
  create?: Prisma.XOR<Prisma.HouseholdCreateWithoutOwnerInput, Prisma.HouseholdUncheckedCreateWithoutOwnerInput>
  connectOrCreate?: Prisma.HouseholdCreateOrConnectWithoutOwnerInput
  connect?: Prisma.HouseholdWhereUniqueInput
}

export type HouseholdUpdateOneWithoutOwnerNestedInput = {
  create?: Prisma.XOR<Prisma.HouseholdCreateWithoutOwnerInput, Prisma.HouseholdUncheckedCreateWithoutOwnerInput>
  connectOrCreate?: Prisma.HouseholdCreateOrConnectWithoutOwnerInput
  upsert?: Prisma.HouseholdUpsertWithoutOwnerInput
  disconnect?: Prisma.HouseholdWhereInput | boolean
  delete?: Prisma.HouseholdWhereInput | boolean
  connect?: Prisma.HouseholdWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.HouseholdUpdateToOneWithWhereWithoutOwnerInput, Prisma.HouseholdUpdateWithoutOwnerInput>, Prisma.HouseholdUncheckedUpdateWithoutOwnerInput>
}

export type HouseholdUncheckedUpdateOneWithoutOwnerNestedInput = {
  create?: Prisma.XOR<Prisma.HouseholdCreateWithoutOwnerInput, Prisma.HouseholdUncheckedCreateWithoutOwnerInput>
  connectOrCreate?: Prisma.HouseholdCreateOrConnectWithoutOwnerInput
  upsert?: Prisma.HouseholdUpsertWithoutOwnerInput
  disconnect?: Prisma.HouseholdWhereInput | boolean
  delete?: Prisma.HouseholdWhereInput | boolean
  connect?: Prisma.HouseholdWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.HouseholdUpdateToOneWithWhereWithoutOwnerInput, Prisma.HouseholdUpdateWithoutOwnerInput>, Prisma.HouseholdUncheckedUpdateWithoutOwnerInput>
}

export type HouseholdCreateNestedOneWithoutMembersInput = {
  create?: Prisma.XOR<Prisma.HouseholdCreateWithoutMembersInput, Prisma.HouseholdUncheckedCreateWithoutMembersInput>
  connectOrCreate?: Prisma.HouseholdCreateOrConnectWithoutMembersInput
  connect?: Prisma.HouseholdWhereUniqueInput
}

export type HouseholdUpdateOneRequiredWithoutMembersNestedInput = {
  create?: Prisma.XOR<Prisma.HouseholdCreateWithoutMembersInput, Prisma.HouseholdUncheckedCreateWithoutMembersInput>
  connectOrCreate?: Prisma.HouseholdCreateOrConnectWithoutMembersInput
  upsert?: Prisma.HouseholdUpsertWithoutMembersInput
  connect?: Prisma.HouseholdWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.HouseholdUpdateToOneWithWhereWithoutMembersInput, Prisma.HouseholdUpdateWithoutMembersInput>, Prisma.HouseholdUncheckedUpdateWithoutMembersInput>
}

export type HouseholdCreateNestedOneWithoutAccountsInput = {
  create?: Prisma.XOR<Prisma.HouseholdCreateWithoutAccountsInput, Prisma.HouseholdUncheckedCreateWithoutAccountsInput>
  connectOrCreate?: Prisma.HouseholdCreateOrConnectWithoutAccountsInput
  connect?: Prisma.HouseholdWhereUniqueInput
}

export type HouseholdUpdateOneRequiredWithoutAccountsNestedInput = {
  create?: Prisma.XOR<Prisma.HouseholdCreateWithoutAccountsInput, Prisma.HouseholdUncheckedCreateWithoutAccountsInput>
  connectOrCreate?: Prisma.HouseholdCreateOrConnectWithoutAccountsInput
  upsert?: Prisma.HouseholdUpsertWithoutAccountsInput
  connect?: Prisma.HouseholdWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.HouseholdUpdateToOneWithWhereWithoutAccountsInput, Prisma.HouseholdUpdateWithoutAccountsInput>, Prisma.HouseholdUncheckedUpdateWithoutAccountsInput>
}

export type HouseholdCreateNestedOneWithoutPotsInput = {
  create?: Prisma.XOR<Prisma.HouseholdCreateWithoutPotsInput, Prisma.HouseholdUncheckedCreateWithoutPotsInput>
  connectOrCreate?: Prisma.HouseholdCreateOrConnectWithoutPotsInput
  connect?: Prisma.HouseholdWhereUniqueInput
}

export type HouseholdUpdateOneRequiredWithoutPotsNestedInput = {
  create?: Prisma.XOR<Prisma.HouseholdCreateWithoutPotsInput, Prisma.HouseholdUncheckedCreateWithoutPotsInput>
  connectOrCreate?: Prisma.HouseholdCreateOrConnectWithoutPotsInput
  upsert?: Prisma.HouseholdUpsertWithoutPotsInput
  connect?: Prisma.HouseholdWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.HouseholdUpdateToOneWithWhereWithoutPotsInput, Prisma.HouseholdUpdateWithoutPotsInput>, Prisma.HouseholdUncheckedUpdateWithoutPotsInput>
}

export type HouseholdCreateWithoutOwnerInput = {
  id?: string
  name?: string
  createdAt?: Date | string
  members?: Prisma.HouseholdMemberCreateNestedManyWithoutHouseholdInput
  accounts?: Prisma.AccountCreateNestedManyWithoutHouseholdInput
  pots?: Prisma.PotCreateNestedManyWithoutHouseholdInput
}

export type HouseholdUncheckedCreateWithoutOwnerInput = {
  id?: string
  name?: string
  createdAt?: Date | string
  members?: Prisma.HouseholdMemberUncheckedCreateNestedManyWithoutHouseholdInput
  accounts?: Prisma.AccountUncheckedCreateNestedManyWithoutHouseholdInput
  pots?: Prisma.PotUncheckedCreateNestedManyWithoutHouseholdInput
}

export type HouseholdCreateOrConnectWithoutOwnerInput = {
  where: Prisma.HouseholdWhereUniqueInput
  create: Prisma.XOR<Prisma.HouseholdCreateWithoutOwnerInput, Prisma.HouseholdUncheckedCreateWithoutOwnerInput>
}

export type HouseholdUpsertWithoutOwnerInput = {
  update: Prisma.XOR<Prisma.HouseholdUpdateWithoutOwnerInput, Prisma.HouseholdUncheckedUpdateWithoutOwnerInput>
  create: Prisma.XOR<Prisma.HouseholdCreateWithoutOwnerInput, Prisma.HouseholdUncheckedCreateWithoutOwnerInput>
  where?: Prisma.HouseholdWhereInput
}

export type HouseholdUpdateToOneWithWhereWithoutOwnerInput = {
  where?: Prisma.HouseholdWhereInput
  data: Prisma.XOR<Prisma.HouseholdUpdateWithoutOwnerInput, Prisma.HouseholdUncheckedUpdateWithoutOwnerInput>
}

export type HouseholdUpdateWithoutOwnerInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  members?: Prisma.HouseholdMemberUpdateManyWithoutHouseholdNestedInput
  accounts?: Prisma.AccountUpdateManyWithoutHouseholdNestedInput
  pots?: Prisma.PotUpdateManyWithoutHouseholdNestedInput
}

export type HouseholdUncheckedUpdateWithoutOwnerInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  members?: Prisma.HouseholdMemberUncheckedUpdateManyWithoutHouseholdNestedInput
  accounts?: Prisma.AccountUncheckedUpdateManyWithoutHouseholdNestedInput
  pots?: Prisma.PotUncheckedUpdateManyWithoutHouseholdNestedInput
}

export type HouseholdCreateWithoutMembersInput = {
  id?: string
  name?: string
  createdAt?: Date | string
  owner?: Prisma.UserCreateNestedOneWithoutHouseholdInput
  accounts?: Prisma.AccountCreateNestedManyWithoutHouseholdInput
  pots?: Prisma.PotCreateNestedManyWithoutHouseholdInput
}

export type HouseholdUncheckedCreateWithoutMembersInput = {
  id?: string
  name?: string
  createdAt?: Date | string
  ownerId?: string | null
  accounts?: Prisma.AccountUncheckedCreateNestedManyWithoutHouseholdInput
  pots?: Prisma.PotUncheckedCreateNestedManyWithoutHouseholdInput
}

export type HouseholdCreateOrConnectWithoutMembersInput = {
  where: Prisma.HouseholdWhereUniqueInput
  create: Prisma.XOR<Prisma.HouseholdCreateWithoutMembersInput, Prisma.HouseholdUncheckedCreateWithoutMembersInput>
}

export type HouseholdUpsertWithoutMembersInput = {
  update: Prisma.XOR<Prisma.HouseholdUpdateWithoutMembersInput, Prisma.HouseholdUncheckedUpdateWithoutMembersInput>
  create: Prisma.XOR<Prisma.HouseholdCreateWithoutMembersInput, Prisma.HouseholdUncheckedCreateWithoutMembersInput>
  where?: Prisma.HouseholdWhereInput
}

export type HouseholdUpdateToOneWithWhereWithoutMembersInput = {
  where?: Prisma.HouseholdWhereInput
  data: Prisma.XOR<Prisma.HouseholdUpdateWithoutMembersInput, Prisma.HouseholdUncheckedUpdateWithoutMembersInput>
}

export type HouseholdUpdateWithoutMembersInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  owner?: Prisma.UserUpdateOneWithoutHouseholdNestedInput
  accounts?: Prisma.AccountUpdateManyWithoutHouseholdNestedInput
  pots?: Prisma.PotUpdateManyWithoutHouseholdNestedInput
}

export type HouseholdUncheckedUpdateWithoutMembersInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  ownerId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  accounts?: Prisma.AccountUncheckedUpdateManyWithoutHouseholdNestedInput
  pots?: Prisma.PotUncheckedUpdateManyWithoutHouseholdNestedInput
}

export type HouseholdCreateWithoutAccountsInput = {
  id?: string
  name?: string
  createdAt?: Date | string
  owner?: Prisma.UserCreateNestedOneWithoutHouseholdInput
  members?: Prisma.HouseholdMemberCreateNestedManyWithoutHouseholdInput
  pots?: Prisma.PotCreateNestedManyWithoutHouseholdInput
}

export type HouseholdUncheckedCreateWithoutAccountsInput = {
  id?: string
  name?: string
  createdAt?: Date | string
  ownerId?: string | null
  members?: Prisma.HouseholdMemberUncheckedCreateNestedManyWithoutHouseholdInput
  pots?: Prisma.PotUncheckedCreateNestedManyWithoutHouseholdInput
}

export type HouseholdCreateOrConnectWithoutAccountsInput = {
  where: Prisma.HouseholdWhereUniqueInput
  create: Prisma.XOR<Prisma.HouseholdCreateWithoutAccountsInput, Prisma.HouseholdUncheckedCreateWithoutAccountsInput>
}

export type HouseholdUpsertWithoutAccountsInput = {
  update: Prisma.XOR<Prisma.HouseholdUpdateWithoutAccountsInput, Prisma.HouseholdUncheckedUpdateWithoutAccountsInput>
  create: Prisma.XOR<Prisma.HouseholdCreateWithoutAccountsInput, Prisma.HouseholdUncheckedCreateWithoutAccountsInput>
  where?: Prisma.HouseholdWhereInput
}

export type HouseholdUpdateToOneWithWhereWithoutAccountsInput = {
  where?: Prisma.HouseholdWhereInput
  data: Prisma.XOR<Prisma.HouseholdUpdateWithoutAccountsInput, Prisma.HouseholdUncheckedUpdateWithoutAccountsInput>
}

export type HouseholdUpdateWithoutAccountsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  owner?: Prisma.UserUpdateOneWithoutHouseholdNestedInput
  members?: Prisma.HouseholdMemberUpdateManyWithoutHouseholdNestedInput
  pots?: Prisma.PotUpdateManyWithoutHouseholdNestedInput
}

export type HouseholdUncheckedUpdateWithoutAccountsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  ownerId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  members?: Prisma.HouseholdMemberUncheckedUpdateManyWithoutHouseholdNestedInput
  pots?: Prisma.PotUncheckedUpdateManyWithoutHouseholdNestedInput
}

export type HouseholdCreateWithoutPotsInput = {
  id?: string
  name?: string
  createdAt?: Date | string
  owner?: Prisma.UserCreateNestedOneWithoutHouseholdInput
  members?: Prisma.HouseholdMemberCreateNestedManyWithoutHouseholdInput
  accounts?: Prisma.AccountCreateNestedManyWithoutHouseholdInput
}

export type HouseholdUncheckedCreateWithoutPotsInput = {
  id?: string
  name?: string
  createdAt?: Date | string
  ownerId?: string | null
  members?: Prisma.HouseholdMemberUncheckedCreateNestedManyWithoutHouseholdInput
  accounts?: Prisma.AccountUncheckedCreateNestedManyWithoutHouseholdInput
}

export type HouseholdCreateOrConnectWithoutPotsInput = {
  where: Prisma.HouseholdWhereUniqueInput
  create: Prisma.XOR<Prisma.HouseholdCreateWithoutPotsInput, Prisma.HouseholdUncheckedCreateWithoutPotsInput>
}

export type HouseholdUpsertWithoutPotsInput = {
  update: Prisma.XOR<Prisma.HouseholdUpdateWithoutPotsInput, Prisma.HouseholdUncheckedUpdateWithoutPotsInput>
  create: Prisma.XOR<Prisma.HouseholdCreateWithoutPotsInput, Prisma.HouseholdUncheckedCreateWithoutPotsInput>
  where?: Prisma.HouseholdWhereInput
}

export type HouseholdUpdateToOneWithWhereWithoutPotsInput = {
  where?: Prisma.HouseholdWhereInput
  data: Prisma.XOR<Prisma.HouseholdUpdateWithoutPotsInput, Prisma.HouseholdUncheckedUpdateWithoutPotsInput>
}

export type HouseholdUpdateWithoutPotsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  owner?: Prisma.UserUpdateOneWithoutHouseholdNestedInput
  members?: Prisma.HouseholdMemberUpdateManyWithoutHouseholdNestedInput
  accounts?: Prisma.AccountUpdateManyWithoutHouseholdNestedInput
}

export type HouseholdUncheckedUpdateWithoutPotsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  ownerId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  members?: Prisma.HouseholdMemberUncheckedUpdateManyWithoutHouseholdNestedInput
  accounts?: Prisma.AccountUncheckedUpdateManyWithoutHouseholdNestedInput
}


/**
 * Count Type HouseholdCountOutputType
 */

export type HouseholdCountOutputType = {
  members: number
  accounts: number
  pots: number
}

export type HouseholdCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  members?: boolean | HouseholdCountOutputTypeCountMembersArgs
  accounts?: boolean | HouseholdCountOutputTypeCountAccountsArgs
  pots?: boolean | HouseholdCountOutputTypeCountPotsArgs
}

/**
 * HouseholdCountOutputType without action
 */
export type HouseholdCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the HouseholdCountOutputType
   */
  select?: Prisma.HouseholdCountOutputTypeSelect<ExtArgs> | null
}

/**
 * HouseholdCountOutputType without action
 */
export type HouseholdCountOutputTypeCountMembersArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.HouseholdMemberWhereInput
}

/**
 * HouseholdCountOutputType without action
 */
export type HouseholdCountOutputTypeCountAccountsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.AccountWhereInput
}

/**
 * HouseholdCountOutputType without action
 */
export type HouseholdCountOutputTypeCountPotsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.PotWhereInput
}


export type HouseholdSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  createdAt?: boolean
  ownerId?: boolean
  owner?: boolean | Prisma.Household$ownerArgs<ExtArgs>
  members?: boolean | Prisma.Household$membersArgs<ExtArgs>
  accounts?: boolean | Prisma.Household$accountsArgs<ExtArgs>
  pots?: boolean | Prisma.Household$potsArgs<ExtArgs>
  _count?: boolean | Prisma.HouseholdCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["household"]>

export type HouseholdSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  createdAt?: boolean
  ownerId?: boolean
  owner?: boolean | Prisma.Household$ownerArgs<ExtArgs>
}, ExtArgs["result"]["household"]>

export type HouseholdSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  createdAt?: boolean
  ownerId?: boolean
  owner?: boolean | Prisma.Household$ownerArgs<ExtArgs>
}, ExtArgs["result"]["household"]>

export type HouseholdSelectScalar = {
  id?: boolean
  name?: boolean
  createdAt?: boolean
  ownerId?: boolean
}

export type HouseholdOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "name" | "createdAt" | "ownerId", ExtArgs["result"]["household"]>
export type HouseholdInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  owner?: boolean | Prisma.Household$ownerArgs<ExtArgs>
  members?: boolean | Prisma.Household$membersArgs<ExtArgs>
  accounts?: boolean | Prisma.Household$accountsArgs<ExtArgs>
  pots?: boolean | Prisma.Household$potsArgs<ExtArgs>
  _count?: boolean | Prisma.HouseholdCountOutputTypeDefaultArgs<ExtArgs>
}
export type HouseholdIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  owner?: boolean | Prisma.Household$ownerArgs<ExtArgs>
}
export type HouseholdIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  owner?: boolean | Prisma.Household$ownerArgs<ExtArgs>
}

export type $HouseholdPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "Household"
  objects: {
    owner: Prisma.$UserPayload<ExtArgs> | null
    members: Prisma.$HouseholdMemberPayload<ExtArgs>[]
    accounts: Prisma.$AccountPayload<ExtArgs>[]
    pots: Prisma.$PotPayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    name: string
    createdAt: Date
    ownerId: string | null
  }, ExtArgs["result"]["household"]>
  composites: {}
}

export type HouseholdGetPayload<S extends boolean | null | undefined | HouseholdDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$HouseholdPayload, S>

export type HouseholdCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<HouseholdFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: HouseholdCountAggregateInputType | true
  }

export interface HouseholdDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['Household'], meta: { name: 'Household' } }
  /**
   * Find zero or one Household that matches the filter.
   * @param {HouseholdFindUniqueArgs} args - Arguments to find a Household
   * @example
   * // Get one Household
   * const household = await prisma.household.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends HouseholdFindUniqueArgs>(args: Prisma.SelectSubset<T, HouseholdFindUniqueArgs<ExtArgs>>): Prisma.Prisma__HouseholdClient<runtime.Types.Result.GetResult<Prisma.$HouseholdPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Household that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {HouseholdFindUniqueOrThrowArgs} args - Arguments to find a Household
   * @example
   * // Get one Household
   * const household = await prisma.household.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends HouseholdFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, HouseholdFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__HouseholdClient<runtime.Types.Result.GetResult<Prisma.$HouseholdPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Household that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {HouseholdFindFirstArgs} args - Arguments to find a Household
   * @example
   * // Get one Household
   * const household = await prisma.household.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends HouseholdFindFirstArgs>(args?: Prisma.SelectSubset<T, HouseholdFindFirstArgs<ExtArgs>>): Prisma.Prisma__HouseholdClient<runtime.Types.Result.GetResult<Prisma.$HouseholdPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Household that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {HouseholdFindFirstOrThrowArgs} args - Arguments to find a Household
   * @example
   * // Get one Household
   * const household = await prisma.household.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends HouseholdFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, HouseholdFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__HouseholdClient<runtime.Types.Result.GetResult<Prisma.$HouseholdPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Households that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {HouseholdFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Households
   * const households = await prisma.household.findMany()
   * 
   * // Get first 10 Households
   * const households = await prisma.household.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const householdWithIdOnly = await prisma.household.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends HouseholdFindManyArgs>(args?: Prisma.SelectSubset<T, HouseholdFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$HouseholdPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Household.
   * @param {HouseholdCreateArgs} args - Arguments to create a Household.
   * @example
   * // Create one Household
   * const Household = await prisma.household.create({
   *   data: {
   *     // ... data to create a Household
   *   }
   * })
   * 
   */
  create<T extends HouseholdCreateArgs>(args: Prisma.SelectSubset<T, HouseholdCreateArgs<ExtArgs>>): Prisma.Prisma__HouseholdClient<runtime.Types.Result.GetResult<Prisma.$HouseholdPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Households.
   * @param {HouseholdCreateManyArgs} args - Arguments to create many Households.
   * @example
   * // Create many Households
   * const household = await prisma.household.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends HouseholdCreateManyArgs>(args?: Prisma.SelectSubset<T, HouseholdCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Households and returns the data saved in the database.
   * @param {HouseholdCreateManyAndReturnArgs} args - Arguments to create many Households.
   * @example
   * // Create many Households
   * const household = await prisma.household.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Households and only return the `id`
   * const householdWithIdOnly = await prisma.household.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends HouseholdCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, HouseholdCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$HouseholdPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Household.
   * @param {HouseholdDeleteArgs} args - Arguments to delete one Household.
   * @example
   * // Delete one Household
   * const Household = await prisma.household.delete({
   *   where: {
   *     // ... filter to delete one Household
   *   }
   * })
   * 
   */
  delete<T extends HouseholdDeleteArgs>(args: Prisma.SelectSubset<T, HouseholdDeleteArgs<ExtArgs>>): Prisma.Prisma__HouseholdClient<runtime.Types.Result.GetResult<Prisma.$HouseholdPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Household.
   * @param {HouseholdUpdateArgs} args - Arguments to update one Household.
   * @example
   * // Update one Household
   * const household = await prisma.household.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends HouseholdUpdateArgs>(args: Prisma.SelectSubset<T, HouseholdUpdateArgs<ExtArgs>>): Prisma.Prisma__HouseholdClient<runtime.Types.Result.GetResult<Prisma.$HouseholdPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Households.
   * @param {HouseholdDeleteManyArgs} args - Arguments to filter Households to delete.
   * @example
   * // Delete a few Households
   * const { count } = await prisma.household.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends HouseholdDeleteManyArgs>(args?: Prisma.SelectSubset<T, HouseholdDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Households.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {HouseholdUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Households
   * const household = await prisma.household.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends HouseholdUpdateManyArgs>(args: Prisma.SelectSubset<T, HouseholdUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Households and returns the data updated in the database.
   * @param {HouseholdUpdateManyAndReturnArgs} args - Arguments to update many Households.
   * @example
   * // Update many Households
   * const household = await prisma.household.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Households and only return the `id`
   * const householdWithIdOnly = await prisma.household.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends HouseholdUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, HouseholdUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$HouseholdPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Household.
   * @param {HouseholdUpsertArgs} args - Arguments to update or create a Household.
   * @example
   * // Update or create a Household
   * const household = await prisma.household.upsert({
   *   create: {
   *     // ... data to create a Household
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Household we want to update
   *   }
   * })
   */
  upsert<T extends HouseholdUpsertArgs>(args: Prisma.SelectSubset<T, HouseholdUpsertArgs<ExtArgs>>): Prisma.Prisma__HouseholdClient<runtime.Types.Result.GetResult<Prisma.$HouseholdPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Households.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {HouseholdCountArgs} args - Arguments to filter Households to count.
   * @example
   * // Count the number of Households
   * const count = await prisma.household.count({
   *   where: {
   *     // ... the filter for the Households we want to count
   *   }
   * })
  **/
  count<T extends HouseholdCountArgs>(
    args?: Prisma.Subset<T, HouseholdCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], HouseholdCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Household.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {HouseholdAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends HouseholdAggregateArgs>(args: Prisma.Subset<T, HouseholdAggregateArgs>): Prisma.PrismaPromise<GetHouseholdAggregateType<T>>

  /**
   * Group by Household.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {HouseholdGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends HouseholdGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: HouseholdGroupByArgs['orderBy'] }
      : { orderBy?: HouseholdGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, HouseholdGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetHouseholdGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the Household model
 */
readonly fields: HouseholdFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for Household.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__HouseholdClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  owner<T extends Prisma.Household$ownerArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Household$ownerArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>
  members<T extends Prisma.Household$membersArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Household$membersArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$HouseholdMemberPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  accounts<T extends Prisma.Household$accountsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Household$accountsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$AccountPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  pots<T extends Prisma.Household$potsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Household$potsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$PotPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the Household model
 */
export interface HouseholdFieldRefs {
  readonly id: Prisma.FieldRef<"Household", 'String'>
  readonly name: Prisma.FieldRef<"Household", 'String'>
  readonly createdAt: Prisma.FieldRef<"Household", 'DateTime'>
  readonly ownerId: Prisma.FieldRef<"Household", 'String'>
}
    

// Custom InputTypes
/**
 * Household findUnique
 */
export type HouseholdFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Household
   */
  select?: Prisma.HouseholdSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Household
   */
  omit?: Prisma.HouseholdOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.HouseholdInclude<ExtArgs> | null
  /**
   * Filter, which Household to fetch.
   */
  where: Prisma.HouseholdWhereUniqueInput
}

/**
 * Household findUniqueOrThrow
 */
export type HouseholdFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Household
   */
  select?: Prisma.HouseholdSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Household
   */
  omit?: Prisma.HouseholdOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.HouseholdInclude<ExtArgs> | null
  /**
   * Filter, which Household to fetch.
   */
  where: Prisma.HouseholdWhereUniqueInput
}

/**
 * Household findFirst
 */
export type HouseholdFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Household
   */
  select?: Prisma.HouseholdSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Household
   */
  omit?: Prisma.HouseholdOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.HouseholdInclude<ExtArgs> | null
  /**
   * Filter, which Household to fetch.
   */
  where?: Prisma.HouseholdWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Households to fetch.
   */
  orderBy?: Prisma.HouseholdOrderByWithRelationInput | Prisma.HouseholdOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Households.
   */
  cursor?: Prisma.HouseholdWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Households from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Households.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Households.
   */
  distinct?: Prisma.HouseholdScalarFieldEnum | Prisma.HouseholdScalarFieldEnum[]
}

/**
 * Household findFirstOrThrow
 */
export type HouseholdFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Household
   */
  select?: Prisma.HouseholdSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Household
   */
  omit?: Prisma.HouseholdOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.HouseholdInclude<ExtArgs> | null
  /**
   * Filter, which Household to fetch.
   */
  where?: Prisma.HouseholdWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Households to fetch.
   */
  orderBy?: Prisma.HouseholdOrderByWithRelationInput | Prisma.HouseholdOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Households.
   */
  cursor?: Prisma.HouseholdWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Households from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Households.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Households.
   */
  distinct?: Prisma.HouseholdScalarFieldEnum | Prisma.HouseholdScalarFieldEnum[]
}

/**
 * Household findMany
 */
export type HouseholdFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Household
   */
  select?: Prisma.HouseholdSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Household
   */
  omit?: Prisma.HouseholdOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.HouseholdInclude<ExtArgs> | null
  /**
   * Filter, which Households to fetch.
   */
  where?: Prisma.HouseholdWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Households to fetch.
   */
  orderBy?: Prisma.HouseholdOrderByWithRelationInput | Prisma.HouseholdOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Households.
   */
  cursor?: Prisma.HouseholdWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Households from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Households.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Households.
   */
  distinct?: Prisma.HouseholdScalarFieldEnum | Prisma.HouseholdScalarFieldEnum[]
}

/**
 * Household create
 */
export type HouseholdCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Household
   */
  select?: Prisma.HouseholdSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Household
   */
  omit?: Prisma.HouseholdOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.HouseholdInclude<ExtArgs> | null
  /**
   * The data needed to create a Household.
   */
  data?: Prisma.XOR<Prisma.HouseholdCreateInput, Prisma.HouseholdUncheckedCreateInput>
}

/**
 * Household createMany
 */
export type HouseholdCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Households.
   */
  data: Prisma.HouseholdCreateManyInput | Prisma.HouseholdCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Household createManyAndReturn
 */
export type HouseholdCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Household
   */
  select?: Prisma.HouseholdSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Household
   */
  omit?: Prisma.HouseholdOmit<ExtArgs> | null
  /**
   * The data used to create many Households.
   */
  data: Prisma.HouseholdCreateManyInput | Prisma.HouseholdCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.HouseholdIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * Household update
 */
export type HouseholdUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Household
   */
  select?: Prisma.HouseholdSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Household
   */
  omit?: Prisma.HouseholdOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.HouseholdInclude<ExtArgs> | null
  /**
   * The data needed to update a Household.
   */
  data: Prisma.XOR<Prisma.HouseholdUpdateInput, Prisma.HouseholdUncheckedUpdateInput>
  /**
   * Choose, which Household to update.
   */
  where: Prisma.HouseholdWhereUniqueInput
}

/**
 * Household updateMany
 */
export type HouseholdUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Households.
   */
  data: Prisma.XOR<Prisma.HouseholdUpdateManyMutationInput, Prisma.HouseholdUncheckedUpdateManyInput>
  /**
   * Filter which Households to update
   */
  where?: Prisma.HouseholdWhereInput
  /**
   * Limit how many Households to update.
   */
  limit?: number
}

/**
 * Household updateManyAndReturn
 */
export type HouseholdUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Household
   */
  select?: Prisma.HouseholdSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Household
   */
  omit?: Prisma.HouseholdOmit<ExtArgs> | null
  /**
   * The data used to update Households.
   */
  data: Prisma.XOR<Prisma.HouseholdUpdateManyMutationInput, Prisma.HouseholdUncheckedUpdateManyInput>
  /**
   * Filter which Households to update
   */
  where?: Prisma.HouseholdWhereInput
  /**
   * Limit how many Households to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.HouseholdIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * Household upsert
 */
export type HouseholdUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Household
   */
  select?: Prisma.HouseholdSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Household
   */
  omit?: Prisma.HouseholdOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.HouseholdInclude<ExtArgs> | null
  /**
   * The filter to search for the Household to update in case it exists.
   */
  where: Prisma.HouseholdWhereUniqueInput
  /**
   * In case the Household found by the `where` argument doesn't exist, create a new Household with this data.
   */
  create: Prisma.XOR<Prisma.HouseholdCreateInput, Prisma.HouseholdUncheckedCreateInput>
  /**
   * In case the Household was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.HouseholdUpdateInput, Prisma.HouseholdUncheckedUpdateInput>
}

/**
 * Household delete
 */
export type HouseholdDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Household
   */
  select?: Prisma.HouseholdSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Household
   */
  omit?: Prisma.HouseholdOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.HouseholdInclude<ExtArgs> | null
  /**
   * Filter which Household to delete.
   */
  where: Prisma.HouseholdWhereUniqueInput
}

/**
 * Household deleteMany
 */
export type HouseholdDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Households to delete
   */
  where?: Prisma.HouseholdWhereInput
  /**
   * Limit how many Households to delete.
   */
  limit?: number
}

/**
 * Household.owner
 */
export type Household$ownerArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the User
   */
  select?: Prisma.UserSelect<ExtArgs> | null
  /**
   * Omit specific fields from the User
   */
  omit?: Prisma.UserOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserInclude<ExtArgs> | null
  where?: Prisma.UserWhereInput
}

/**
 * Household.members
 */
export type Household$membersArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the HouseholdMember
   */
  select?: Prisma.HouseholdMemberSelect<ExtArgs> | null
  /**
   * Omit specific fields from the HouseholdMember
   */
  omit?: Prisma.HouseholdMemberOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.HouseholdMemberInclude<ExtArgs> | null
  where?: Prisma.HouseholdMemberWhereInput
  orderBy?: Prisma.HouseholdMemberOrderByWithRelationInput | Prisma.HouseholdMemberOrderByWithRelationInput[]
  cursor?: Prisma.HouseholdMemberWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.HouseholdMemberScalarFieldEnum | Prisma.HouseholdMemberScalarFieldEnum[]
}

/**
 * Household.accounts
 */
export type Household$accountsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Account
   */
  select?: Prisma.AccountSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Account
   */
  omit?: Prisma.AccountOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AccountInclude<ExtArgs> | null
  where?: Prisma.AccountWhereInput
  orderBy?: Prisma.AccountOrderByWithRelationInput | Prisma.AccountOrderByWithRelationInput[]
  cursor?: Prisma.AccountWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.AccountScalarFieldEnum | Prisma.AccountScalarFieldEnum[]
}

/**
 * Household.pots
 */
export type Household$potsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Pot
   */
  select?: Prisma.PotSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Pot
   */
  omit?: Prisma.PotOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PotInclude<ExtArgs> | null
  where?: Prisma.PotWhereInput
  orderBy?: Prisma.PotOrderByWithRelationInput | Prisma.PotOrderByWithRelationInput[]
  cursor?: Prisma.PotWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.PotScalarFieldEnum | Prisma.PotScalarFieldEnum[]
}

/**
 * Household without action
 */
export type HouseholdDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Household
   */
  select?: Prisma.HouseholdSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Household
   */
  omit?: Prisma.HouseholdOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.HouseholdInclude<ExtArgs> | null
}
