
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `LinkedBankAccount` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model LinkedBankAccount
 * 
 */
export type LinkedBankAccountModel = runtime.Types.Result.DefaultSelection<Prisma.$LinkedBankAccountPayload>

export type AggregateLinkedBankAccount = {
  _count: LinkedBankAccountCountAggregateOutputType | null
  _avg: LinkedBankAccountAvgAggregateOutputType | null
  _sum: LinkedBankAccountSumAggregateOutputType | null
  _min: LinkedBankAccountMinAggregateOutputType | null
  _max: LinkedBankAccountMaxAggregateOutputType | null
}

export type LinkedBankAccountAvgAggregateOutputType = {
  balance: number | null
}

export type LinkedBankAccountSumAggregateOutputType = {
  balance: number | null
}

export type LinkedBankAccountMinAggregateOutputType = {
  id: string | null
  plaidItemId: string | null
  bankName: string | null
  accountName: string | null
  accountNumber: string | null
  balance: number | null
  currency: string | null
  plaidAccessToken: string | null
  lastSync: Date | null
  createdAt: Date | null
  updatedAt: Date | null
  userId: string | null
}

export type LinkedBankAccountMaxAggregateOutputType = {
  id: string | null
  plaidItemId: string | null
  bankName: string | null
  accountName: string | null
  accountNumber: string | null
  balance: number | null
  currency: string | null
  plaidAccessToken: string | null
  lastSync: Date | null
  createdAt: Date | null
  updatedAt: Date | null
  userId: string | null
}

export type LinkedBankAccountCountAggregateOutputType = {
  id: number
  plaidItemId: number
  bankName: number
  accountName: number
  accountNumber: number
  balance: number
  currency: number
  plaidAccessToken: number
  lastSync: number
  createdAt: number
  updatedAt: number
  userId: number
  _all: number
}


export type LinkedBankAccountAvgAggregateInputType = {
  balance?: true
}

export type LinkedBankAccountSumAggregateInputType = {
  balance?: true
}

export type LinkedBankAccountMinAggregateInputType = {
  id?: true
  plaidItemId?: true
  bankName?: true
  accountName?: true
  accountNumber?: true
  balance?: true
  currency?: true
  plaidAccessToken?: true
  lastSync?: true
  createdAt?: true
  updatedAt?: true
  userId?: true
}

export type LinkedBankAccountMaxAggregateInputType = {
  id?: true
  plaidItemId?: true
  bankName?: true
  accountName?: true
  accountNumber?: true
  balance?: true
  currency?: true
  plaidAccessToken?: true
  lastSync?: true
  createdAt?: true
  updatedAt?: true
  userId?: true
}

export type LinkedBankAccountCountAggregateInputType = {
  id?: true
  plaidItemId?: true
  bankName?: true
  accountName?: true
  accountNumber?: true
  balance?: true
  currency?: true
  plaidAccessToken?: true
  lastSync?: true
  createdAt?: true
  updatedAt?: true
  userId?: true
  _all?: true
}

export type LinkedBankAccountAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which LinkedBankAccount to aggregate.
   */
  where?: Prisma.LinkedBankAccountWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of LinkedBankAccounts to fetch.
   */
  orderBy?: Prisma.LinkedBankAccountOrderByWithRelationInput | Prisma.LinkedBankAccountOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.LinkedBankAccountWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` LinkedBankAccounts from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` LinkedBankAccounts.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned LinkedBankAccounts
  **/
  _count?: true | LinkedBankAccountCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: LinkedBankAccountAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: LinkedBankAccountSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: LinkedBankAccountMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: LinkedBankAccountMaxAggregateInputType
}

export type GetLinkedBankAccountAggregateType<T extends LinkedBankAccountAggregateArgs> = {
      [P in keyof T & keyof AggregateLinkedBankAccount]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateLinkedBankAccount[P]>
    : Prisma.GetScalarType<T[P], AggregateLinkedBankAccount[P]>
}




export type LinkedBankAccountGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.LinkedBankAccountWhereInput
  orderBy?: Prisma.LinkedBankAccountOrderByWithAggregationInput | Prisma.LinkedBankAccountOrderByWithAggregationInput[]
  by: Prisma.LinkedBankAccountScalarFieldEnum[] | Prisma.LinkedBankAccountScalarFieldEnum
  having?: Prisma.LinkedBankAccountScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: LinkedBankAccountCountAggregateInputType | true
  _avg?: LinkedBankAccountAvgAggregateInputType
  _sum?: LinkedBankAccountSumAggregateInputType
  _min?: LinkedBankAccountMinAggregateInputType
  _max?: LinkedBankAccountMaxAggregateInputType
}

export type LinkedBankAccountGroupByOutputType = {
  id: string
  plaidItemId: string
  bankName: string
  accountName: string
  accountNumber: string | null
  balance: number
  currency: string
  plaidAccessToken: string
  lastSync: Date | null
  createdAt: Date
  updatedAt: Date
  userId: string
  _count: LinkedBankAccountCountAggregateOutputType | null
  _avg: LinkedBankAccountAvgAggregateOutputType | null
  _sum: LinkedBankAccountSumAggregateOutputType | null
  _min: LinkedBankAccountMinAggregateOutputType | null
  _max: LinkedBankAccountMaxAggregateOutputType | null
}

export type GetLinkedBankAccountGroupByPayload<T extends LinkedBankAccountGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<LinkedBankAccountGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof LinkedBankAccountGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], LinkedBankAccountGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], LinkedBankAccountGroupByOutputType[P]>
      }
    >
  >



export type LinkedBankAccountWhereInput = {
  AND?: Prisma.LinkedBankAccountWhereInput | Prisma.LinkedBankAccountWhereInput[]
  OR?: Prisma.LinkedBankAccountWhereInput[]
  NOT?: Prisma.LinkedBankAccountWhereInput | Prisma.LinkedBankAccountWhereInput[]
  id?: Prisma.StringFilter<"LinkedBankAccount"> | string
  plaidItemId?: Prisma.StringFilter<"LinkedBankAccount"> | string
  bankName?: Prisma.StringFilter<"LinkedBankAccount"> | string
  accountName?: Prisma.StringFilter<"LinkedBankAccount"> | string
  accountNumber?: Prisma.StringNullableFilter<"LinkedBankAccount"> | string | null
  balance?: Prisma.FloatFilter<"LinkedBankAccount"> | number
  currency?: Prisma.StringFilter<"LinkedBankAccount"> | string
  plaidAccessToken?: Prisma.StringFilter<"LinkedBankAccount"> | string
  lastSync?: Prisma.DateTimeNullableFilter<"LinkedBankAccount"> | Date | string | null
  createdAt?: Prisma.DateTimeFilter<"LinkedBankAccount"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"LinkedBankAccount"> | Date | string
  userId?: Prisma.StringFilter<"LinkedBankAccount"> | string
  user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
  transactions?: Prisma.PlaidTransactionListRelationFilter
}

export type LinkedBankAccountOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  plaidItemId?: Prisma.SortOrder
  bankName?: Prisma.SortOrder
  accountName?: Prisma.SortOrder
  accountNumber?: Prisma.SortOrderInput | Prisma.SortOrder
  balance?: Prisma.SortOrder
  currency?: Prisma.SortOrder
  plaidAccessToken?: Prisma.SortOrder
  lastSync?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  user?: Prisma.UserOrderByWithRelationInput
  transactions?: Prisma.PlaidTransactionOrderByRelationAggregateInput
}

export type LinkedBankAccountWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  plaidItemId?: string
  AND?: Prisma.LinkedBankAccountWhereInput | Prisma.LinkedBankAccountWhereInput[]
  OR?: Prisma.LinkedBankAccountWhereInput[]
  NOT?: Prisma.LinkedBankAccountWhereInput | Prisma.LinkedBankAccountWhereInput[]
  bankName?: Prisma.StringFilter<"LinkedBankAccount"> | string
  accountName?: Prisma.StringFilter<"LinkedBankAccount"> | string
  accountNumber?: Prisma.StringNullableFilter<"LinkedBankAccount"> | string | null
  balance?: Prisma.FloatFilter<"LinkedBankAccount"> | number
  currency?: Prisma.StringFilter<"LinkedBankAccount"> | string
  plaidAccessToken?: Prisma.StringFilter<"LinkedBankAccount"> | string
  lastSync?: Prisma.DateTimeNullableFilter<"LinkedBankAccount"> | Date | string | null
  createdAt?: Prisma.DateTimeFilter<"LinkedBankAccount"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"LinkedBankAccount"> | Date | string
  userId?: Prisma.StringFilter<"LinkedBankAccount"> | string
  user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
  transactions?: Prisma.PlaidTransactionListRelationFilter
}, "id" | "plaidItemId">

export type LinkedBankAccountOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  plaidItemId?: Prisma.SortOrder
  bankName?: Prisma.SortOrder
  accountName?: Prisma.SortOrder
  accountNumber?: Prisma.SortOrderInput | Prisma.SortOrder
  balance?: Prisma.SortOrder
  currency?: Prisma.SortOrder
  plaidAccessToken?: Prisma.SortOrder
  lastSync?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  _count?: Prisma.LinkedBankAccountCountOrderByAggregateInput
  _avg?: Prisma.LinkedBankAccountAvgOrderByAggregateInput
  _max?: Prisma.LinkedBankAccountMaxOrderByAggregateInput
  _min?: Prisma.LinkedBankAccountMinOrderByAggregateInput
  _sum?: Prisma.LinkedBankAccountSumOrderByAggregateInput
}

export type LinkedBankAccountScalarWhereWithAggregatesInput = {
  AND?: Prisma.LinkedBankAccountScalarWhereWithAggregatesInput | Prisma.LinkedBankAccountScalarWhereWithAggregatesInput[]
  OR?: Prisma.LinkedBankAccountScalarWhereWithAggregatesInput[]
  NOT?: Prisma.LinkedBankAccountScalarWhereWithAggregatesInput | Prisma.LinkedBankAccountScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"LinkedBankAccount"> | string
  plaidItemId?: Prisma.StringWithAggregatesFilter<"LinkedBankAccount"> | string
  bankName?: Prisma.StringWithAggregatesFilter<"LinkedBankAccount"> | string
  accountName?: Prisma.StringWithAggregatesFilter<"LinkedBankAccount"> | string
  accountNumber?: Prisma.StringNullableWithAggregatesFilter<"LinkedBankAccount"> | string | null
  balance?: Prisma.FloatWithAggregatesFilter<"LinkedBankAccount"> | number
  currency?: Prisma.StringWithAggregatesFilter<"LinkedBankAccount"> | string
  plaidAccessToken?: Prisma.StringWithAggregatesFilter<"LinkedBankAccount"> | string
  lastSync?: Prisma.DateTimeNullableWithAggregatesFilter<"LinkedBankAccount"> | Date | string | null
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"LinkedBankAccount"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"LinkedBankAccount"> | Date | string
  userId?: Prisma.StringWithAggregatesFilter<"LinkedBankAccount"> | string
}

export type LinkedBankAccountCreateInput = {
  id?: string
  plaidItemId: string
  bankName: string
  accountName: string
  accountNumber?: string | null
  balance?: number
  currency?: string
  plaidAccessToken: string
  lastSync?: Date | string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  user: Prisma.UserCreateNestedOneWithoutLinkedAccountsInput
  transactions?: Prisma.PlaidTransactionCreateNestedManyWithoutLinkedAccountInput
}

export type LinkedBankAccountUncheckedCreateInput = {
  id?: string
  plaidItemId: string
  bankName: string
  accountName: string
  accountNumber?: string | null
  balance?: number
  currency?: string
  plaidAccessToken: string
  lastSync?: Date | string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  userId: string
  transactions?: Prisma.PlaidTransactionUncheckedCreateNestedManyWithoutLinkedAccountInput
}

export type LinkedBankAccountUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  plaidItemId?: Prisma.StringFieldUpdateOperationsInput | string
  bankName?: Prisma.StringFieldUpdateOperationsInput | string
  accountName?: Prisma.StringFieldUpdateOperationsInput | string
  accountNumber?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  balance?: Prisma.FloatFieldUpdateOperationsInput | number
  currency?: Prisma.StringFieldUpdateOperationsInput | string
  plaidAccessToken?: Prisma.StringFieldUpdateOperationsInput | string
  lastSync?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  user?: Prisma.UserUpdateOneRequiredWithoutLinkedAccountsNestedInput
  transactions?: Prisma.PlaidTransactionUpdateManyWithoutLinkedAccountNestedInput
}

export type LinkedBankAccountUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  plaidItemId?: Prisma.StringFieldUpdateOperationsInput | string
  bankName?: Prisma.StringFieldUpdateOperationsInput | string
  accountName?: Prisma.StringFieldUpdateOperationsInput | string
  accountNumber?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  balance?: Prisma.FloatFieldUpdateOperationsInput | number
  currency?: Prisma.StringFieldUpdateOperationsInput | string
  plaidAccessToken?: Prisma.StringFieldUpdateOperationsInput | string
  lastSync?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  transactions?: Prisma.PlaidTransactionUncheckedUpdateManyWithoutLinkedAccountNestedInput
}

export type LinkedBankAccountCreateManyInput = {
  id?: string
  plaidItemId: string
  bankName: string
  accountName: string
  accountNumber?: string | null
  balance?: number
  currency?: string
  plaidAccessToken: string
  lastSync?: Date | string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  userId: string
}

export type LinkedBankAccountUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  plaidItemId?: Prisma.StringFieldUpdateOperationsInput | string
  bankName?: Prisma.StringFieldUpdateOperationsInput | string
  accountName?: Prisma.StringFieldUpdateOperationsInput | string
  accountNumber?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  balance?: Prisma.FloatFieldUpdateOperationsInput | number
  currency?: Prisma.StringFieldUpdateOperationsInput | string
  plaidAccessToken?: Prisma.StringFieldUpdateOperationsInput | string
  lastSync?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type LinkedBankAccountUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  plaidItemId?: Prisma.StringFieldUpdateOperationsInput | string
  bankName?: Prisma.StringFieldUpdateOperationsInput | string
  accountName?: Prisma.StringFieldUpdateOperationsInput | string
  accountNumber?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  balance?: Prisma.FloatFieldUpdateOperationsInput | number
  currency?: Prisma.StringFieldUpdateOperationsInput | string
  plaidAccessToken?: Prisma.StringFieldUpdateOperationsInput | string
  lastSync?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type LinkedBankAccountListRelationFilter = {
  every?: Prisma.LinkedBankAccountWhereInput
  some?: Prisma.LinkedBankAccountWhereInput
  none?: Prisma.LinkedBankAccountWhereInput
}

export type LinkedBankAccountOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type LinkedBankAccountCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  plaidItemId?: Prisma.SortOrder
  bankName?: Prisma.SortOrder
  accountName?: Prisma.SortOrder
  accountNumber?: Prisma.SortOrder
  balance?: Prisma.SortOrder
  currency?: Prisma.SortOrder
  plaidAccessToken?: Prisma.SortOrder
  lastSync?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  userId?: Prisma.SortOrder
}

export type LinkedBankAccountAvgOrderByAggregateInput = {
  balance?: Prisma.SortOrder
}

export type LinkedBankAccountMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  plaidItemId?: Prisma.SortOrder
  bankName?: Prisma.SortOrder
  accountName?: Prisma.SortOrder
  accountNumber?: Prisma.SortOrder
  balance?: Prisma.SortOrder
  currency?: Prisma.SortOrder
  plaidAccessToken?: Prisma.SortOrder
  lastSync?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  userId?: Prisma.SortOrder
}

export type LinkedBankAccountMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  plaidItemId?: Prisma.SortOrder
  bankName?: Prisma.SortOrder
  accountName?: Prisma.SortOrder
  accountNumber?: Prisma.SortOrder
  balance?: Prisma.SortOrder
  currency?: Prisma.SortOrder
  plaidAccessToken?: Prisma.SortOrder
  lastSync?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  userId?: Prisma.SortOrder
}

export type LinkedBankAccountSumOrderByAggregateInput = {
  balance?: Prisma.SortOrder
}

export type LinkedBankAccountScalarRelationFilter = {
  is?: Prisma.LinkedBankAccountWhereInput
  isNot?: Prisma.LinkedBankAccountWhereInput
}

export type LinkedBankAccountCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.LinkedBankAccountCreateWithoutUserInput, Prisma.LinkedBankAccountUncheckedCreateWithoutUserInput> | Prisma.LinkedBankAccountCreateWithoutUserInput[] | Prisma.LinkedBankAccountUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.LinkedBankAccountCreateOrConnectWithoutUserInput | Prisma.LinkedBankAccountCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.LinkedBankAccountCreateManyUserInputEnvelope
  connect?: Prisma.LinkedBankAccountWhereUniqueInput | Prisma.LinkedBankAccountWhereUniqueInput[]
}

export type LinkedBankAccountUncheckedCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.LinkedBankAccountCreateWithoutUserInput, Prisma.LinkedBankAccountUncheckedCreateWithoutUserInput> | Prisma.LinkedBankAccountCreateWithoutUserInput[] | Prisma.LinkedBankAccountUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.LinkedBankAccountCreateOrConnectWithoutUserInput | Prisma.LinkedBankAccountCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.LinkedBankAccountCreateManyUserInputEnvelope
  connect?: Prisma.LinkedBankAccountWhereUniqueInput | Prisma.LinkedBankAccountWhereUniqueInput[]
}

export type LinkedBankAccountUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.LinkedBankAccountCreateWithoutUserInput, Prisma.LinkedBankAccountUncheckedCreateWithoutUserInput> | Prisma.LinkedBankAccountCreateWithoutUserInput[] | Prisma.LinkedBankAccountUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.LinkedBankAccountCreateOrConnectWithoutUserInput | Prisma.LinkedBankAccountCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.LinkedBankAccountUpsertWithWhereUniqueWithoutUserInput | Prisma.LinkedBankAccountUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.LinkedBankAccountCreateManyUserInputEnvelope
  set?: Prisma.LinkedBankAccountWhereUniqueInput | Prisma.LinkedBankAccountWhereUniqueInput[]
  disconnect?: Prisma.LinkedBankAccountWhereUniqueInput | Prisma.LinkedBankAccountWhereUniqueInput[]
  delete?: Prisma.LinkedBankAccountWhereUniqueInput | Prisma.LinkedBankAccountWhereUniqueInput[]
  connect?: Prisma.LinkedBankAccountWhereUniqueInput | Prisma.LinkedBankAccountWhereUniqueInput[]
  update?: Prisma.LinkedBankAccountUpdateWithWhereUniqueWithoutUserInput | Prisma.LinkedBankAccountUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.LinkedBankAccountUpdateManyWithWhereWithoutUserInput | Prisma.LinkedBankAccountUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.LinkedBankAccountScalarWhereInput | Prisma.LinkedBankAccountScalarWhereInput[]
}

export type LinkedBankAccountUncheckedUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.LinkedBankAccountCreateWithoutUserInput, Prisma.LinkedBankAccountUncheckedCreateWithoutUserInput> | Prisma.LinkedBankAccountCreateWithoutUserInput[] | Prisma.LinkedBankAccountUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.LinkedBankAccountCreateOrConnectWithoutUserInput | Prisma.LinkedBankAccountCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.LinkedBankAccountUpsertWithWhereUniqueWithoutUserInput | Prisma.LinkedBankAccountUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.LinkedBankAccountCreateManyUserInputEnvelope
  set?: Prisma.LinkedBankAccountWhereUniqueInput | Prisma.LinkedBankAccountWhereUniqueInput[]
  disconnect?: Prisma.LinkedBankAccountWhereUniqueInput | Prisma.LinkedBankAccountWhereUniqueInput[]
  delete?: Prisma.LinkedBankAccountWhereUniqueInput | Prisma.LinkedBankAccountWhereUniqueInput[]
  connect?: Prisma.LinkedBankAccountWhereUniqueInput | Prisma.LinkedBankAccountWhereUniqueInput[]
  update?: Prisma.LinkedBankAccountUpdateWithWhereUniqueWithoutUserInput | Prisma.LinkedBankAccountUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.LinkedBankAccountUpdateManyWithWhereWithoutUserInput | Prisma.LinkedBankAccountUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.LinkedBankAccountScalarWhereInput | Prisma.LinkedBankAccountScalarWhereInput[]
}

export type NullableDateTimeFieldUpdateOperationsInput = {
  set?: Date | string | null
}

export type LinkedBankAccountCreateNestedOneWithoutTransactionsInput = {
  create?: Prisma.XOR<Prisma.LinkedBankAccountCreateWithoutTransactionsInput, Prisma.LinkedBankAccountUncheckedCreateWithoutTransactionsInput>
  connectOrCreate?: Prisma.LinkedBankAccountCreateOrConnectWithoutTransactionsInput
  connect?: Prisma.LinkedBankAccountWhereUniqueInput
}

export type LinkedBankAccountUpdateOneRequiredWithoutTransactionsNestedInput = {
  create?: Prisma.XOR<Prisma.LinkedBankAccountCreateWithoutTransactionsInput, Prisma.LinkedBankAccountUncheckedCreateWithoutTransactionsInput>
  connectOrCreate?: Prisma.LinkedBankAccountCreateOrConnectWithoutTransactionsInput
  upsert?: Prisma.LinkedBankAccountUpsertWithoutTransactionsInput
  connect?: Prisma.LinkedBankAccountWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.LinkedBankAccountUpdateToOneWithWhereWithoutTransactionsInput, Prisma.LinkedBankAccountUpdateWithoutTransactionsInput>, Prisma.LinkedBankAccountUncheckedUpdateWithoutTransactionsInput>
}

export type LinkedBankAccountCreateWithoutUserInput = {
  id?: string
  plaidItemId: string
  bankName: string
  accountName: string
  accountNumber?: string | null
  balance?: number
  currency?: string
  plaidAccessToken: string
  lastSync?: Date | string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  transactions?: Prisma.PlaidTransactionCreateNestedManyWithoutLinkedAccountInput
}

export type LinkedBankAccountUncheckedCreateWithoutUserInput = {
  id?: string
  plaidItemId: string
  bankName: string
  accountName: string
  accountNumber?: string | null
  balance?: number
  currency?: string
  plaidAccessToken: string
  lastSync?: Date | string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  transactions?: Prisma.PlaidTransactionUncheckedCreateNestedManyWithoutLinkedAccountInput
}

export type LinkedBankAccountCreateOrConnectWithoutUserInput = {
  where: Prisma.LinkedBankAccountWhereUniqueInput
  create: Prisma.XOR<Prisma.LinkedBankAccountCreateWithoutUserInput, Prisma.LinkedBankAccountUncheckedCreateWithoutUserInput>
}

export type LinkedBankAccountCreateManyUserInputEnvelope = {
  data: Prisma.LinkedBankAccountCreateManyUserInput | Prisma.LinkedBankAccountCreateManyUserInput[]
  skipDuplicates?: boolean
}

export type LinkedBankAccountUpsertWithWhereUniqueWithoutUserInput = {
  where: Prisma.LinkedBankAccountWhereUniqueInput
  update: Prisma.XOR<Prisma.LinkedBankAccountUpdateWithoutUserInput, Prisma.LinkedBankAccountUncheckedUpdateWithoutUserInput>
  create: Prisma.XOR<Prisma.LinkedBankAccountCreateWithoutUserInput, Prisma.LinkedBankAccountUncheckedCreateWithoutUserInput>
}

export type LinkedBankAccountUpdateWithWhereUniqueWithoutUserInput = {
  where: Prisma.LinkedBankAccountWhereUniqueInput
  data: Prisma.XOR<Prisma.LinkedBankAccountUpdateWithoutUserInput, Prisma.LinkedBankAccountUncheckedUpdateWithoutUserInput>
}

export type LinkedBankAccountUpdateManyWithWhereWithoutUserInput = {
  where: Prisma.LinkedBankAccountScalarWhereInput
  data: Prisma.XOR<Prisma.LinkedBankAccountUpdateManyMutationInput, Prisma.LinkedBankAccountUncheckedUpdateManyWithoutUserInput>
}

export type LinkedBankAccountScalarWhereInput = {
  AND?: Prisma.LinkedBankAccountScalarWhereInput | Prisma.LinkedBankAccountScalarWhereInput[]
  OR?: Prisma.LinkedBankAccountScalarWhereInput[]
  NOT?: Prisma.LinkedBankAccountScalarWhereInput | Prisma.LinkedBankAccountScalarWhereInput[]
  id?: Prisma.StringFilter<"LinkedBankAccount"> | string
  plaidItemId?: Prisma.StringFilter<"LinkedBankAccount"> | string
  bankName?: Prisma.StringFilter<"LinkedBankAccount"> | string
  accountName?: Prisma.StringFilter<"LinkedBankAccount"> | string
  accountNumber?: Prisma.StringNullableFilter<"LinkedBankAccount"> | string | null
  balance?: Prisma.FloatFilter<"LinkedBankAccount"> | number
  currency?: Prisma.StringFilter<"LinkedBankAccount"> | string
  plaidAccessToken?: Prisma.StringFilter<"LinkedBankAccount"> | string
  lastSync?: Prisma.DateTimeNullableFilter<"LinkedBankAccount"> | Date | string | null
  createdAt?: Prisma.DateTimeFilter<"LinkedBankAccount"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"LinkedBankAccount"> | Date | string
  userId?: Prisma.StringFilter<"LinkedBankAccount"> | string
}

export type LinkedBankAccountCreateWithoutTransactionsInput = {
  id?: string
  plaidItemId: string
  bankName: string
  accountName: string
  accountNumber?: string | null
  balance?: number
  currency?: string
  plaidAccessToken: string
  lastSync?: Date | string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  user: Prisma.UserCreateNestedOneWithoutLinkedAccountsInput
}

export type LinkedBankAccountUncheckedCreateWithoutTransactionsInput = {
  id?: string
  plaidItemId: string
  bankName: string
  accountName: string
  accountNumber?: string | null
  balance?: number
  currency?: string
  plaidAccessToken: string
  lastSync?: Date | string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  userId: string
}

export type LinkedBankAccountCreateOrConnectWithoutTransactionsInput = {
  where: Prisma.LinkedBankAccountWhereUniqueInput
  create: Prisma.XOR<Prisma.LinkedBankAccountCreateWithoutTransactionsInput, Prisma.LinkedBankAccountUncheckedCreateWithoutTransactionsInput>
}

export type LinkedBankAccountUpsertWithoutTransactionsInput = {
  update: Prisma.XOR<Prisma.LinkedBankAccountUpdateWithoutTransactionsInput, Prisma.LinkedBankAccountUncheckedUpdateWithoutTransactionsInput>
  create: Prisma.XOR<Prisma.LinkedBankAccountCreateWithoutTransactionsInput, Prisma.LinkedBankAccountUncheckedCreateWithoutTransactionsInput>
  where?: Prisma.LinkedBankAccountWhereInput
}

export type LinkedBankAccountUpdateToOneWithWhereWithoutTransactionsInput = {
  where?: Prisma.LinkedBankAccountWhereInput
  data: Prisma.XOR<Prisma.LinkedBankAccountUpdateWithoutTransactionsInput, Prisma.LinkedBankAccountUncheckedUpdateWithoutTransactionsInput>
}

export type LinkedBankAccountUpdateWithoutTransactionsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  plaidItemId?: Prisma.StringFieldUpdateOperationsInput | string
  bankName?: Prisma.StringFieldUpdateOperationsInput | string
  accountName?: Prisma.StringFieldUpdateOperationsInput | string
  accountNumber?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  balance?: Prisma.FloatFieldUpdateOperationsInput | number
  currency?: Prisma.StringFieldUpdateOperationsInput | string
  plaidAccessToken?: Prisma.StringFieldUpdateOperationsInput | string
  lastSync?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  user?: Prisma.UserUpdateOneRequiredWithoutLinkedAccountsNestedInput
}

export type LinkedBankAccountUncheckedUpdateWithoutTransactionsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  plaidItemId?: Prisma.StringFieldUpdateOperationsInput | string
  bankName?: Prisma.StringFieldUpdateOperationsInput | string
  accountName?: Prisma.StringFieldUpdateOperationsInput | string
  accountNumber?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  balance?: Prisma.FloatFieldUpdateOperationsInput | number
  currency?: Prisma.StringFieldUpdateOperationsInput | string
  plaidAccessToken?: Prisma.StringFieldUpdateOperationsInput | string
  lastSync?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type LinkedBankAccountCreateManyUserInput = {
  id?: string
  plaidItemId: string
  bankName: string
  accountName: string
  accountNumber?: string | null
  balance?: number
  currency?: string
  plaidAccessToken: string
  lastSync?: Date | string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type LinkedBankAccountUpdateWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  plaidItemId?: Prisma.StringFieldUpdateOperationsInput | string
  bankName?: Prisma.StringFieldUpdateOperationsInput | string
  accountName?: Prisma.StringFieldUpdateOperationsInput | string
  accountNumber?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  balance?: Prisma.FloatFieldUpdateOperationsInput | number
  currency?: Prisma.StringFieldUpdateOperationsInput | string
  plaidAccessToken?: Prisma.StringFieldUpdateOperationsInput | string
  lastSync?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  transactions?: Prisma.PlaidTransactionUpdateManyWithoutLinkedAccountNestedInput
}

export type LinkedBankAccountUncheckedUpdateWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  plaidItemId?: Prisma.StringFieldUpdateOperationsInput | string
  bankName?: Prisma.StringFieldUpdateOperationsInput | string
  accountName?: Prisma.StringFieldUpdateOperationsInput | string
  accountNumber?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  balance?: Prisma.FloatFieldUpdateOperationsInput | number
  currency?: Prisma.StringFieldUpdateOperationsInput | string
  plaidAccessToken?: Prisma.StringFieldUpdateOperationsInput | string
  lastSync?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  transactions?: Prisma.PlaidTransactionUncheckedUpdateManyWithoutLinkedAccountNestedInput
}

export type LinkedBankAccountUncheckedUpdateManyWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  plaidItemId?: Prisma.StringFieldUpdateOperationsInput | string
  bankName?: Prisma.StringFieldUpdateOperationsInput | string
  accountName?: Prisma.StringFieldUpdateOperationsInput | string
  accountNumber?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  balance?: Prisma.FloatFieldUpdateOperationsInput | number
  currency?: Prisma.StringFieldUpdateOperationsInput | string
  plaidAccessToken?: Prisma.StringFieldUpdateOperationsInput | string
  lastSync?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}


/**
 * Count Type LinkedBankAccountCountOutputType
 */

export type LinkedBankAccountCountOutputType = {
  transactions: number
}

export type LinkedBankAccountCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  transactions?: boolean | LinkedBankAccountCountOutputTypeCountTransactionsArgs
}

/**
 * LinkedBankAccountCountOutputType without action
 */
export type LinkedBankAccountCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the LinkedBankAccountCountOutputType
   */
  select?: Prisma.LinkedBankAccountCountOutputTypeSelect<ExtArgs> | null
}

/**
 * LinkedBankAccountCountOutputType without action
 */
export type LinkedBankAccountCountOutputTypeCountTransactionsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.PlaidTransactionWhereInput
}


export type LinkedBankAccountSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  plaidItemId?: boolean
  bankName?: boolean
  accountName?: boolean
  accountNumber?: boolean
  balance?: boolean
  currency?: boolean
  plaidAccessToken?: boolean
  lastSync?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  userId?: boolean
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  transactions?: boolean | Prisma.LinkedBankAccount$transactionsArgs<ExtArgs>
  _count?: boolean | Prisma.LinkedBankAccountCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["linkedBankAccount"]>

export type LinkedBankAccountSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  plaidItemId?: boolean
  bankName?: boolean
  accountName?: boolean
  accountNumber?: boolean
  balance?: boolean
  currency?: boolean
  plaidAccessToken?: boolean
  lastSync?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  userId?: boolean
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["linkedBankAccount"]>

export type LinkedBankAccountSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  plaidItemId?: boolean
  bankName?: boolean
  accountName?: boolean
  accountNumber?: boolean
  balance?: boolean
  currency?: boolean
  plaidAccessToken?: boolean
  lastSync?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  userId?: boolean
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["linkedBankAccount"]>

export type LinkedBankAccountSelectScalar = {
  id?: boolean
  plaidItemId?: boolean
  bankName?: boolean
  accountName?: boolean
  accountNumber?: boolean
  balance?: boolean
  currency?: boolean
  plaidAccessToken?: boolean
  lastSync?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  userId?: boolean
}

export type LinkedBankAccountOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "plaidItemId" | "bankName" | "accountName" | "accountNumber" | "balance" | "currency" | "plaidAccessToken" | "lastSync" | "createdAt" | "updatedAt" | "userId", ExtArgs["result"]["linkedBankAccount"]>
export type LinkedBankAccountInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  transactions?: boolean | Prisma.LinkedBankAccount$transactionsArgs<ExtArgs>
  _count?: boolean | Prisma.LinkedBankAccountCountOutputTypeDefaultArgs<ExtArgs>
}
export type LinkedBankAccountIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}
export type LinkedBankAccountIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}

export type $LinkedBankAccountPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "LinkedBankAccount"
  objects: {
    user: Prisma.$UserPayload<ExtArgs>
    transactions: Prisma.$PlaidTransactionPayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    plaidItemId: string
    bankName: string
    accountName: string
    accountNumber: string | null
    balance: number
    currency: string
    plaidAccessToken: string
    lastSync: Date | null
    createdAt: Date
    updatedAt: Date
    userId: string
  }, ExtArgs["result"]["linkedBankAccount"]>
  composites: {}
}

export type LinkedBankAccountGetPayload<S extends boolean | null | undefined | LinkedBankAccountDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$LinkedBankAccountPayload, S>

export type LinkedBankAccountCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<LinkedBankAccountFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: LinkedBankAccountCountAggregateInputType | true
  }

export interface LinkedBankAccountDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['LinkedBankAccount'], meta: { name: 'LinkedBankAccount' } }
  /**
   * Find zero or one LinkedBankAccount that matches the filter.
   * @param {LinkedBankAccountFindUniqueArgs} args - Arguments to find a LinkedBankAccount
   * @example
   * // Get one LinkedBankAccount
   * const linkedBankAccount = await prisma.linkedBankAccount.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends LinkedBankAccountFindUniqueArgs>(args: Prisma.SelectSubset<T, LinkedBankAccountFindUniqueArgs<ExtArgs>>): Prisma.Prisma__LinkedBankAccountClient<runtime.Types.Result.GetResult<Prisma.$LinkedBankAccountPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one LinkedBankAccount that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {LinkedBankAccountFindUniqueOrThrowArgs} args - Arguments to find a LinkedBankAccount
   * @example
   * // Get one LinkedBankAccount
   * const linkedBankAccount = await prisma.linkedBankAccount.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends LinkedBankAccountFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, LinkedBankAccountFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__LinkedBankAccountClient<runtime.Types.Result.GetResult<Prisma.$LinkedBankAccountPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first LinkedBankAccount that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {LinkedBankAccountFindFirstArgs} args - Arguments to find a LinkedBankAccount
   * @example
   * // Get one LinkedBankAccount
   * const linkedBankAccount = await prisma.linkedBankAccount.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends LinkedBankAccountFindFirstArgs>(args?: Prisma.SelectSubset<T, LinkedBankAccountFindFirstArgs<ExtArgs>>): Prisma.Prisma__LinkedBankAccountClient<runtime.Types.Result.GetResult<Prisma.$LinkedBankAccountPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first LinkedBankAccount that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {LinkedBankAccountFindFirstOrThrowArgs} args - Arguments to find a LinkedBankAccount
   * @example
   * // Get one LinkedBankAccount
   * const linkedBankAccount = await prisma.linkedBankAccount.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends LinkedBankAccountFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, LinkedBankAccountFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__LinkedBankAccountClient<runtime.Types.Result.GetResult<Prisma.$LinkedBankAccountPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more LinkedBankAccounts that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {LinkedBankAccountFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all LinkedBankAccounts
   * const linkedBankAccounts = await prisma.linkedBankAccount.findMany()
   * 
   * // Get first 10 LinkedBankAccounts
   * const linkedBankAccounts = await prisma.linkedBankAccount.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const linkedBankAccountWithIdOnly = await prisma.linkedBankAccount.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends LinkedBankAccountFindManyArgs>(args?: Prisma.SelectSubset<T, LinkedBankAccountFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$LinkedBankAccountPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a LinkedBankAccount.
   * @param {LinkedBankAccountCreateArgs} args - Arguments to create a LinkedBankAccount.
   * @example
   * // Create one LinkedBankAccount
   * const LinkedBankAccount = await prisma.linkedBankAccount.create({
   *   data: {
   *     // ... data to create a LinkedBankAccount
   *   }
   * })
   * 
   */
  create<T extends LinkedBankAccountCreateArgs>(args: Prisma.SelectSubset<T, LinkedBankAccountCreateArgs<ExtArgs>>): Prisma.Prisma__LinkedBankAccountClient<runtime.Types.Result.GetResult<Prisma.$LinkedBankAccountPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many LinkedBankAccounts.
   * @param {LinkedBankAccountCreateManyArgs} args - Arguments to create many LinkedBankAccounts.
   * @example
   * // Create many LinkedBankAccounts
   * const linkedBankAccount = await prisma.linkedBankAccount.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends LinkedBankAccountCreateManyArgs>(args?: Prisma.SelectSubset<T, LinkedBankAccountCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many LinkedBankAccounts and returns the data saved in the database.
   * @param {LinkedBankAccountCreateManyAndReturnArgs} args - Arguments to create many LinkedBankAccounts.
   * @example
   * // Create many LinkedBankAccounts
   * const linkedBankAccount = await prisma.linkedBankAccount.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many LinkedBankAccounts and only return the `id`
   * const linkedBankAccountWithIdOnly = await prisma.linkedBankAccount.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends LinkedBankAccountCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, LinkedBankAccountCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$LinkedBankAccountPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a LinkedBankAccount.
   * @param {LinkedBankAccountDeleteArgs} args - Arguments to delete one LinkedBankAccount.
   * @example
   * // Delete one LinkedBankAccount
   * const LinkedBankAccount = await prisma.linkedBankAccount.delete({
   *   where: {
   *     // ... filter to delete one LinkedBankAccount
   *   }
   * })
   * 
   */
  delete<T extends LinkedBankAccountDeleteArgs>(args: Prisma.SelectSubset<T, LinkedBankAccountDeleteArgs<ExtArgs>>): Prisma.Prisma__LinkedBankAccountClient<runtime.Types.Result.GetResult<Prisma.$LinkedBankAccountPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one LinkedBankAccount.
   * @param {LinkedBankAccountUpdateArgs} args - Arguments to update one LinkedBankAccount.
   * @example
   * // Update one LinkedBankAccount
   * const linkedBankAccount = await prisma.linkedBankAccount.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends LinkedBankAccountUpdateArgs>(args: Prisma.SelectSubset<T, LinkedBankAccountUpdateArgs<ExtArgs>>): Prisma.Prisma__LinkedBankAccountClient<runtime.Types.Result.GetResult<Prisma.$LinkedBankAccountPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more LinkedBankAccounts.
   * @param {LinkedBankAccountDeleteManyArgs} args - Arguments to filter LinkedBankAccounts to delete.
   * @example
   * // Delete a few LinkedBankAccounts
   * const { count } = await prisma.linkedBankAccount.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends LinkedBankAccountDeleteManyArgs>(args?: Prisma.SelectSubset<T, LinkedBankAccountDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more LinkedBankAccounts.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {LinkedBankAccountUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many LinkedBankAccounts
   * const linkedBankAccount = await prisma.linkedBankAccount.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends LinkedBankAccountUpdateManyArgs>(args: Prisma.SelectSubset<T, LinkedBankAccountUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more LinkedBankAccounts and returns the data updated in the database.
   * @param {LinkedBankAccountUpdateManyAndReturnArgs} args - Arguments to update many LinkedBankAccounts.
   * @example
   * // Update many LinkedBankAccounts
   * const linkedBankAccount = await prisma.linkedBankAccount.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more LinkedBankAccounts and only return the `id`
   * const linkedBankAccountWithIdOnly = await prisma.linkedBankAccount.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends LinkedBankAccountUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, LinkedBankAccountUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$LinkedBankAccountPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one LinkedBankAccount.
   * @param {LinkedBankAccountUpsertArgs} args - Arguments to update or create a LinkedBankAccount.
   * @example
   * // Update or create a LinkedBankAccount
   * const linkedBankAccount = await prisma.linkedBankAccount.upsert({
   *   create: {
   *     // ... data to create a LinkedBankAccount
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the LinkedBankAccount we want to update
   *   }
   * })
   */
  upsert<T extends LinkedBankAccountUpsertArgs>(args: Prisma.SelectSubset<T, LinkedBankAccountUpsertArgs<ExtArgs>>): Prisma.Prisma__LinkedBankAccountClient<runtime.Types.Result.GetResult<Prisma.$LinkedBankAccountPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of LinkedBankAccounts.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {LinkedBankAccountCountArgs} args - Arguments to filter LinkedBankAccounts to count.
   * @example
   * // Count the number of LinkedBankAccounts
   * const count = await prisma.linkedBankAccount.count({
   *   where: {
   *     // ... the filter for the LinkedBankAccounts we want to count
   *   }
   * })
  **/
  count<T extends LinkedBankAccountCountArgs>(
    args?: Prisma.Subset<T, LinkedBankAccountCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], LinkedBankAccountCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a LinkedBankAccount.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {LinkedBankAccountAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends LinkedBankAccountAggregateArgs>(args: Prisma.Subset<T, LinkedBankAccountAggregateArgs>): Prisma.PrismaPromise<GetLinkedBankAccountAggregateType<T>>

  /**
   * Group by LinkedBankAccount.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {LinkedBankAccountGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends LinkedBankAccountGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: LinkedBankAccountGroupByArgs['orderBy'] }
      : { orderBy?: LinkedBankAccountGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, LinkedBankAccountGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetLinkedBankAccountGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the LinkedBankAccount model
 */
readonly fields: LinkedBankAccountFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for LinkedBankAccount.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__LinkedBankAccountClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  user<T extends Prisma.UserDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.UserDefaultArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  transactions<T extends Prisma.LinkedBankAccount$transactionsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.LinkedBankAccount$transactionsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$PlaidTransactionPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the LinkedBankAccount model
 */
export interface LinkedBankAccountFieldRefs {
  readonly id: Prisma.FieldRef<"LinkedBankAccount", 'String'>
  readonly plaidItemId: Prisma.FieldRef<"LinkedBankAccount", 'String'>
  readonly bankName: Prisma.FieldRef<"LinkedBankAccount", 'String'>
  readonly accountName: Prisma.FieldRef<"LinkedBankAccount", 'String'>
  readonly accountNumber: Prisma.FieldRef<"LinkedBankAccount", 'String'>
  readonly balance: Prisma.FieldRef<"LinkedBankAccount", 'Float'>
  readonly currency: Prisma.FieldRef<"LinkedBankAccount", 'String'>
  readonly plaidAccessToken: Prisma.FieldRef<"LinkedBankAccount", 'String'>
  readonly lastSync: Prisma.FieldRef<"LinkedBankAccount", 'DateTime'>
  readonly createdAt: Prisma.FieldRef<"LinkedBankAccount", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"LinkedBankAccount", 'DateTime'>
  readonly userId: Prisma.FieldRef<"LinkedBankAccount", 'String'>
}
    

// Custom InputTypes
/**
 * LinkedBankAccount findUnique
 */
export type LinkedBankAccountFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the LinkedBankAccount
   */
  select?: Prisma.LinkedBankAccountSelect<ExtArgs> | null
  /**
   * Omit specific fields from the LinkedBankAccount
   */
  omit?: Prisma.LinkedBankAccountOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.LinkedBankAccountInclude<ExtArgs> | null
  /**
   * Filter, which LinkedBankAccount to fetch.
   */
  where: Prisma.LinkedBankAccountWhereUniqueInput
}

/**
 * LinkedBankAccount findUniqueOrThrow
 */
export type LinkedBankAccountFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the LinkedBankAccount
   */
  select?: Prisma.LinkedBankAccountSelect<ExtArgs> | null
  /**
   * Omit specific fields from the LinkedBankAccount
   */
  omit?: Prisma.LinkedBankAccountOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.LinkedBankAccountInclude<ExtArgs> | null
  /**
   * Filter, which LinkedBankAccount to fetch.
   */
  where: Prisma.LinkedBankAccountWhereUniqueInput
}

/**
 * LinkedBankAccount findFirst
 */
export type LinkedBankAccountFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the LinkedBankAccount
   */
  select?: Prisma.LinkedBankAccountSelect<ExtArgs> | null
  /**
   * Omit specific fields from the LinkedBankAccount
   */
  omit?: Prisma.LinkedBankAccountOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.LinkedBankAccountInclude<ExtArgs> | null
  /**
   * Filter, which LinkedBankAccount to fetch.
   */
  where?: Prisma.LinkedBankAccountWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of LinkedBankAccounts to fetch.
   */
  orderBy?: Prisma.LinkedBankAccountOrderByWithRelationInput | Prisma.LinkedBankAccountOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for LinkedBankAccounts.
   */
  cursor?: Prisma.LinkedBankAccountWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` LinkedBankAccounts from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` LinkedBankAccounts.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of LinkedBankAccounts.
   */
  distinct?: Prisma.LinkedBankAccountScalarFieldEnum | Prisma.LinkedBankAccountScalarFieldEnum[]
}

/**
 * LinkedBankAccount findFirstOrThrow
 */
export type LinkedBankAccountFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the LinkedBankAccount
   */
  select?: Prisma.LinkedBankAccountSelect<ExtArgs> | null
  /**
   * Omit specific fields from the LinkedBankAccount
   */
  omit?: Prisma.LinkedBankAccountOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.LinkedBankAccountInclude<ExtArgs> | null
  /**
   * Filter, which LinkedBankAccount to fetch.
   */
  where?: Prisma.LinkedBankAccountWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of LinkedBankAccounts to fetch.
   */
  orderBy?: Prisma.LinkedBankAccountOrderByWithRelationInput | Prisma.LinkedBankAccountOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for LinkedBankAccounts.
   */
  cursor?: Prisma.LinkedBankAccountWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` LinkedBankAccounts from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` LinkedBankAccounts.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of LinkedBankAccounts.
   */
  distinct?: Prisma.LinkedBankAccountScalarFieldEnum | Prisma.LinkedBankAccountScalarFieldEnum[]
}

/**
 * LinkedBankAccount findMany
 */
export type LinkedBankAccountFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the LinkedBankAccount
   */
  select?: Prisma.LinkedBankAccountSelect<ExtArgs> | null
  /**
   * Omit specific fields from the LinkedBankAccount
   */
  omit?: Prisma.LinkedBankAccountOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.LinkedBankAccountInclude<ExtArgs> | null
  /**
   * Filter, which LinkedBankAccounts to fetch.
   */
  where?: Prisma.LinkedBankAccountWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of LinkedBankAccounts to fetch.
   */
  orderBy?: Prisma.LinkedBankAccountOrderByWithRelationInput | Prisma.LinkedBankAccountOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing LinkedBankAccounts.
   */
  cursor?: Prisma.LinkedBankAccountWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` LinkedBankAccounts from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` LinkedBankAccounts.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of LinkedBankAccounts.
   */
  distinct?: Prisma.LinkedBankAccountScalarFieldEnum | Prisma.LinkedBankAccountScalarFieldEnum[]
}

/**
 * LinkedBankAccount create
 */
export type LinkedBankAccountCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the LinkedBankAccount
   */
  select?: Prisma.LinkedBankAccountSelect<ExtArgs> | null
  /**
   * Omit specific fields from the LinkedBankAccount
   */
  omit?: Prisma.LinkedBankAccountOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.LinkedBankAccountInclude<ExtArgs> | null
  /**
   * The data needed to create a LinkedBankAccount.
   */
  data: Prisma.XOR<Prisma.LinkedBankAccountCreateInput, Prisma.LinkedBankAccountUncheckedCreateInput>
}

/**
 * LinkedBankAccount createMany
 */
export type LinkedBankAccountCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many LinkedBankAccounts.
   */
  data: Prisma.LinkedBankAccountCreateManyInput | Prisma.LinkedBankAccountCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * LinkedBankAccount createManyAndReturn
 */
export type LinkedBankAccountCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the LinkedBankAccount
   */
  select?: Prisma.LinkedBankAccountSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the LinkedBankAccount
   */
  omit?: Prisma.LinkedBankAccountOmit<ExtArgs> | null
  /**
   * The data used to create many LinkedBankAccounts.
   */
  data: Prisma.LinkedBankAccountCreateManyInput | Prisma.LinkedBankAccountCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.LinkedBankAccountIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * LinkedBankAccount update
 */
export type LinkedBankAccountUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the LinkedBankAccount
   */
  select?: Prisma.LinkedBankAccountSelect<ExtArgs> | null
  /**
   * Omit specific fields from the LinkedBankAccount
   */
  omit?: Prisma.LinkedBankAccountOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.LinkedBankAccountInclude<ExtArgs> | null
  /**
   * The data needed to update a LinkedBankAccount.
   */
  data: Prisma.XOR<Prisma.LinkedBankAccountUpdateInput, Prisma.LinkedBankAccountUncheckedUpdateInput>
  /**
   * Choose, which LinkedBankAccount to update.
   */
  where: Prisma.LinkedBankAccountWhereUniqueInput
}

/**
 * LinkedBankAccount updateMany
 */
export type LinkedBankAccountUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update LinkedBankAccounts.
   */
  data: Prisma.XOR<Prisma.LinkedBankAccountUpdateManyMutationInput, Prisma.LinkedBankAccountUncheckedUpdateManyInput>
  /**
   * Filter which LinkedBankAccounts to update
   */
  where?: Prisma.LinkedBankAccountWhereInput
  /**
   * Limit how many LinkedBankAccounts to update.
   */
  limit?: number
}

/**
 * LinkedBankAccount updateManyAndReturn
 */
export type LinkedBankAccountUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the LinkedBankAccount
   */
  select?: Prisma.LinkedBankAccountSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the LinkedBankAccount
   */
  omit?: Prisma.LinkedBankAccountOmit<ExtArgs> | null
  /**
   * The data used to update LinkedBankAccounts.
   */
  data: Prisma.XOR<Prisma.LinkedBankAccountUpdateManyMutationInput, Prisma.LinkedBankAccountUncheckedUpdateManyInput>
  /**
   * Filter which LinkedBankAccounts to update
   */
  where?: Prisma.LinkedBankAccountWhereInput
  /**
   * Limit how many LinkedBankAccounts to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.LinkedBankAccountIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * LinkedBankAccount upsert
 */
export type LinkedBankAccountUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the LinkedBankAccount
   */
  select?: Prisma.LinkedBankAccountSelect<ExtArgs> | null
  /**
   * Omit specific fields from the LinkedBankAccount
   */
  omit?: Prisma.LinkedBankAccountOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.LinkedBankAccountInclude<ExtArgs> | null
  /**
   * The filter to search for the LinkedBankAccount to update in case it exists.
   */
  where: Prisma.LinkedBankAccountWhereUniqueInput
  /**
   * In case the LinkedBankAccount found by the `where` argument doesn't exist, create a new LinkedBankAccount with this data.
   */
  create: Prisma.XOR<Prisma.LinkedBankAccountCreateInput, Prisma.LinkedBankAccountUncheckedCreateInput>
  /**
   * In case the LinkedBankAccount was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.LinkedBankAccountUpdateInput, Prisma.LinkedBankAccountUncheckedUpdateInput>
}

/**
 * LinkedBankAccount delete
 */
export type LinkedBankAccountDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the LinkedBankAccount
   */
  select?: Prisma.LinkedBankAccountSelect<ExtArgs> | null
  /**
   * Omit specific fields from the LinkedBankAccount
   */
  omit?: Prisma.LinkedBankAccountOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.LinkedBankAccountInclude<ExtArgs> | null
  /**
   * Filter which LinkedBankAccount to delete.
   */
  where: Prisma.LinkedBankAccountWhereUniqueInput
}

/**
 * LinkedBankAccount deleteMany
 */
export type LinkedBankAccountDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which LinkedBankAccounts to delete
   */
  where?: Prisma.LinkedBankAccountWhereInput
  /**
   * Limit how many LinkedBankAccounts to delete.
   */
  limit?: number
}

/**
 * LinkedBankAccount.transactions
 */
export type LinkedBankAccount$transactionsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PlaidTransaction
   */
  select?: Prisma.PlaidTransactionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PlaidTransaction
   */
  omit?: Prisma.PlaidTransactionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PlaidTransactionInclude<ExtArgs> | null
  where?: Prisma.PlaidTransactionWhereInput
  orderBy?: Prisma.PlaidTransactionOrderByWithRelationInput | Prisma.PlaidTransactionOrderByWithRelationInput[]
  cursor?: Prisma.PlaidTransactionWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.PlaidTransactionScalarFieldEnum | Prisma.PlaidTransactionScalarFieldEnum[]
}

/**
 * LinkedBankAccount without action
 */
export type LinkedBankAccountDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the LinkedBankAccount
   */
  select?: Prisma.LinkedBankAccountSelect<ExtArgs> | null
  /**
   * Omit specific fields from the LinkedBankAccount
   */
  omit?: Prisma.LinkedBankAccountOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.LinkedBankAccountInclude<ExtArgs> | null
}
