
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `PlaidTransaction` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model PlaidTransaction
 * 
 */
export type PlaidTransactionModel = runtime.Types.Result.DefaultSelection<Prisma.$PlaidTransactionPayload>

export type AggregatePlaidTransaction = {
  _count: PlaidTransactionCountAggregateOutputType | null
  _avg: PlaidTransactionAvgAggregateOutputType | null
  _sum: PlaidTransactionSumAggregateOutputType | null
  _min: PlaidTransactionMinAggregateOutputType | null
  _max: PlaidTransactionMaxAggregateOutputType | null
}

export type PlaidTransactionAvgAggregateOutputType = {
  amount: number | null
}

export type PlaidTransactionSumAggregateOutputType = {
  amount: number | null
}

export type PlaidTransactionMinAggregateOutputType = {
  id: string | null
  plaidTransactionId: string | null
  date: Date | null
  amount: number | null
  description: string | null
  merchant: string | null
  category: string | null
  createdAt: Date | null
  linkedAccountId: string | null
}

export type PlaidTransactionMaxAggregateOutputType = {
  id: string | null
  plaidTransactionId: string | null
  date: Date | null
  amount: number | null
  description: string | null
  merchant: string | null
  category: string | null
  createdAt: Date | null
  linkedAccountId: string | null
}

export type PlaidTransactionCountAggregateOutputType = {
  id: number
  plaidTransactionId: number
  date: number
  amount: number
  description: number
  merchant: number
  category: number
  createdAt: number
  linkedAccountId: number
  _all: number
}


export type PlaidTransactionAvgAggregateInputType = {
  amount?: true
}

export type PlaidTransactionSumAggregateInputType = {
  amount?: true
}

export type PlaidTransactionMinAggregateInputType = {
  id?: true
  plaidTransactionId?: true
  date?: true
  amount?: true
  description?: true
  merchant?: true
  category?: true
  createdAt?: true
  linkedAccountId?: true
}

export type PlaidTransactionMaxAggregateInputType = {
  id?: true
  plaidTransactionId?: true
  date?: true
  amount?: true
  description?: true
  merchant?: true
  category?: true
  createdAt?: true
  linkedAccountId?: true
}

export type PlaidTransactionCountAggregateInputType = {
  id?: true
  plaidTransactionId?: true
  date?: true
  amount?: true
  description?: true
  merchant?: true
  category?: true
  createdAt?: true
  linkedAccountId?: true
  _all?: true
}

export type PlaidTransactionAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which PlaidTransaction to aggregate.
   */
  where?: Prisma.PlaidTransactionWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of PlaidTransactions to fetch.
   */
  orderBy?: Prisma.PlaidTransactionOrderByWithRelationInput | Prisma.PlaidTransactionOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.PlaidTransactionWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` PlaidTransactions from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` PlaidTransactions.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned PlaidTransactions
  **/
  _count?: true | PlaidTransactionCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: PlaidTransactionAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: PlaidTransactionSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: PlaidTransactionMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: PlaidTransactionMaxAggregateInputType
}

export type GetPlaidTransactionAggregateType<T extends PlaidTransactionAggregateArgs> = {
      [P in keyof T & keyof AggregatePlaidTransaction]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregatePlaidTransaction[P]>
    : Prisma.GetScalarType<T[P], AggregatePlaidTransaction[P]>
}




export type PlaidTransactionGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.PlaidTransactionWhereInput
  orderBy?: Prisma.PlaidTransactionOrderByWithAggregationInput | Prisma.PlaidTransactionOrderByWithAggregationInput[]
  by: Prisma.PlaidTransactionScalarFieldEnum[] | Prisma.PlaidTransactionScalarFieldEnum
  having?: Prisma.PlaidTransactionScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: PlaidTransactionCountAggregateInputType | true
  _avg?: PlaidTransactionAvgAggregateInputType
  _sum?: PlaidTransactionSumAggregateInputType
  _min?: PlaidTransactionMinAggregateInputType
  _max?: PlaidTransactionMaxAggregateInputType
}

export type PlaidTransactionGroupByOutputType = {
  id: string
  plaidTransactionId: string
  date: Date
  amount: number
  description: string
  merchant: string | null
  category: string | null
  createdAt: Date
  linkedAccountId: string
  _count: PlaidTransactionCountAggregateOutputType | null
  _avg: PlaidTransactionAvgAggregateOutputType | null
  _sum: PlaidTransactionSumAggregateOutputType | null
  _min: PlaidTransactionMinAggregateOutputType | null
  _max: PlaidTransactionMaxAggregateOutputType | null
}

export type GetPlaidTransactionGroupByPayload<T extends PlaidTransactionGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<PlaidTransactionGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof PlaidTransactionGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], PlaidTransactionGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], PlaidTransactionGroupByOutputType[P]>
      }
    >
  >



export type PlaidTransactionWhereInput = {
  AND?: Prisma.PlaidTransactionWhereInput | Prisma.PlaidTransactionWhereInput[]
  OR?: Prisma.PlaidTransactionWhereInput[]
  NOT?: Prisma.PlaidTransactionWhereInput | Prisma.PlaidTransactionWhereInput[]
  id?: Prisma.StringFilter<"PlaidTransaction"> | string
  plaidTransactionId?: Prisma.StringFilter<"PlaidTransaction"> | string
  date?: Prisma.DateTimeFilter<"PlaidTransaction"> | Date | string
  amount?: Prisma.FloatFilter<"PlaidTransaction"> | number
  description?: Prisma.StringFilter<"PlaidTransaction"> | string
  merchant?: Prisma.StringNullableFilter<"PlaidTransaction"> | string | null
  category?: Prisma.StringNullableFilter<"PlaidTransaction"> | string | null
  createdAt?: Prisma.DateTimeFilter<"PlaidTransaction"> | Date | string
  linkedAccountId?: Prisma.StringFilter<"PlaidTransaction"> | string
  linkedAccount?: Prisma.XOR<Prisma.LinkedBankAccountScalarRelationFilter, Prisma.LinkedBankAccountWhereInput>
}

export type PlaidTransactionOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  plaidTransactionId?: Prisma.SortOrder
  date?: Prisma.SortOrder
  amount?: Prisma.SortOrder
  description?: Prisma.SortOrder
  merchant?: Prisma.SortOrderInput | Prisma.SortOrder
  category?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  linkedAccountId?: Prisma.SortOrder
  linkedAccount?: Prisma.LinkedBankAccountOrderByWithRelationInput
}

export type PlaidTransactionWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  plaidTransactionId?: string
  AND?: Prisma.PlaidTransactionWhereInput | Prisma.PlaidTransactionWhereInput[]
  OR?: Prisma.PlaidTransactionWhereInput[]
  NOT?: Prisma.PlaidTransactionWhereInput | Prisma.PlaidTransactionWhereInput[]
  date?: Prisma.DateTimeFilter<"PlaidTransaction"> | Date | string
  amount?: Prisma.FloatFilter<"PlaidTransaction"> | number
  description?: Prisma.StringFilter<"PlaidTransaction"> | string
  merchant?: Prisma.StringNullableFilter<"PlaidTransaction"> | string | null
  category?: Prisma.StringNullableFilter<"PlaidTransaction"> | string | null
  createdAt?: Prisma.DateTimeFilter<"PlaidTransaction"> | Date | string
  linkedAccountId?: Prisma.StringFilter<"PlaidTransaction"> | string
  linkedAccount?: Prisma.XOR<Prisma.LinkedBankAccountScalarRelationFilter, Prisma.LinkedBankAccountWhereInput>
}, "id" | "plaidTransactionId">

export type PlaidTransactionOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  plaidTransactionId?: Prisma.SortOrder
  date?: Prisma.SortOrder
  amount?: Prisma.SortOrder
  description?: Prisma.SortOrder
  merchant?: Prisma.SortOrderInput | Prisma.SortOrder
  category?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  linkedAccountId?: Prisma.SortOrder
  _count?: Prisma.PlaidTransactionCountOrderByAggregateInput
  _avg?: Prisma.PlaidTransactionAvgOrderByAggregateInput
  _max?: Prisma.PlaidTransactionMaxOrderByAggregateInput
  _min?: Prisma.PlaidTransactionMinOrderByAggregateInput
  _sum?: Prisma.PlaidTransactionSumOrderByAggregateInput
}

export type PlaidTransactionScalarWhereWithAggregatesInput = {
  AND?: Prisma.PlaidTransactionScalarWhereWithAggregatesInput | Prisma.PlaidTransactionScalarWhereWithAggregatesInput[]
  OR?: Prisma.PlaidTransactionScalarWhereWithAggregatesInput[]
  NOT?: Prisma.PlaidTransactionScalarWhereWithAggregatesInput | Prisma.PlaidTransactionScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"PlaidTransaction"> | string
  plaidTransactionId?: Prisma.StringWithAggregatesFilter<"PlaidTransaction"> | string
  date?: Prisma.DateTimeWithAggregatesFilter<"PlaidTransaction"> | Date | string
  amount?: Prisma.FloatWithAggregatesFilter<"PlaidTransaction"> | number
  description?: Prisma.StringWithAggregatesFilter<"PlaidTransaction"> | string
  merchant?: Prisma.StringNullableWithAggregatesFilter<"PlaidTransaction"> | string | null
  category?: Prisma.StringNullableWithAggregatesFilter<"PlaidTransaction"> | string | null
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"PlaidTransaction"> | Date | string
  linkedAccountId?: Prisma.StringWithAggregatesFilter<"PlaidTransaction"> | string
}

export type PlaidTransactionCreateInput = {
  id?: string
  plaidTransactionId: string
  date: Date | string
  amount: number
  description: string
  merchant?: string | null
  category?: string | null
  createdAt?: Date | string
  linkedAccount: Prisma.LinkedBankAccountCreateNestedOneWithoutTransactionsInput
}

export type PlaidTransactionUncheckedCreateInput = {
  id?: string
  plaidTransactionId: string
  date: Date | string
  amount: number
  description: string
  merchant?: string | null
  category?: string | null
  createdAt?: Date | string
  linkedAccountId: string
}

export type PlaidTransactionUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  plaidTransactionId?: Prisma.StringFieldUpdateOperationsInput | string
  date?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  amount?: Prisma.FloatFieldUpdateOperationsInput | number
  description?: Prisma.StringFieldUpdateOperationsInput | string
  merchant?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  category?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  linkedAccount?: Prisma.LinkedBankAccountUpdateOneRequiredWithoutTransactionsNestedInput
}

export type PlaidTransactionUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  plaidTransactionId?: Prisma.StringFieldUpdateOperationsInput | string
  date?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  amount?: Prisma.FloatFieldUpdateOperationsInput | number
  description?: Prisma.StringFieldUpdateOperationsInput | string
  merchant?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  category?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  linkedAccountId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type PlaidTransactionCreateManyInput = {
  id?: string
  plaidTransactionId: string
  date: Date | string
  amount: number
  description: string
  merchant?: string | null
  category?: string | null
  createdAt?: Date | string
  linkedAccountId: string
}

export type PlaidTransactionUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  plaidTransactionId?: Prisma.StringFieldUpdateOperationsInput | string
  date?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  amount?: Prisma.FloatFieldUpdateOperationsInput | number
  description?: Prisma.StringFieldUpdateOperationsInput | string
  merchant?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  category?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type PlaidTransactionUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  plaidTransactionId?: Prisma.StringFieldUpdateOperationsInput | string
  date?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  amount?: Prisma.FloatFieldUpdateOperationsInput | number
  description?: Prisma.StringFieldUpdateOperationsInput | string
  merchant?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  category?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  linkedAccountId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type PlaidTransactionListRelationFilter = {
  every?: Prisma.PlaidTransactionWhereInput
  some?: Prisma.PlaidTransactionWhereInput
  none?: Prisma.PlaidTransactionWhereInput
}

export type PlaidTransactionOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type PlaidTransactionCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  plaidTransactionId?: Prisma.SortOrder
  date?: Prisma.SortOrder
  amount?: Prisma.SortOrder
  description?: Prisma.SortOrder
  merchant?: Prisma.SortOrder
  category?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  linkedAccountId?: Prisma.SortOrder
}

export type PlaidTransactionAvgOrderByAggregateInput = {
  amount?: Prisma.SortOrder
}

export type PlaidTransactionMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  plaidTransactionId?: Prisma.SortOrder
  date?: Prisma.SortOrder
  amount?: Prisma.SortOrder
  description?: Prisma.SortOrder
  merchant?: Prisma.SortOrder
  category?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  linkedAccountId?: Prisma.SortOrder
}

export type PlaidTransactionMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  plaidTransactionId?: Prisma.SortOrder
  date?: Prisma.SortOrder
  amount?: Prisma.SortOrder
  description?: Prisma.SortOrder
  merchant?: Prisma.SortOrder
  category?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  linkedAccountId?: Prisma.SortOrder
}

export type PlaidTransactionSumOrderByAggregateInput = {
  amount?: Prisma.SortOrder
}

export type PlaidTransactionCreateNestedManyWithoutLinkedAccountInput = {
  create?: Prisma.XOR<Prisma.PlaidTransactionCreateWithoutLinkedAccountInput, Prisma.PlaidTransactionUncheckedCreateWithoutLinkedAccountInput> | Prisma.PlaidTransactionCreateWithoutLinkedAccountInput[] | Prisma.PlaidTransactionUncheckedCreateWithoutLinkedAccountInput[]
  connectOrCreate?: Prisma.PlaidTransactionCreateOrConnectWithoutLinkedAccountInput | Prisma.PlaidTransactionCreateOrConnectWithoutLinkedAccountInput[]
  createMany?: Prisma.PlaidTransactionCreateManyLinkedAccountInputEnvelope
  connect?: Prisma.PlaidTransactionWhereUniqueInput | Prisma.PlaidTransactionWhereUniqueInput[]
}

export type PlaidTransactionUncheckedCreateNestedManyWithoutLinkedAccountInput = {
  create?: Prisma.XOR<Prisma.PlaidTransactionCreateWithoutLinkedAccountInput, Prisma.PlaidTransactionUncheckedCreateWithoutLinkedAccountInput> | Prisma.PlaidTransactionCreateWithoutLinkedAccountInput[] | Prisma.PlaidTransactionUncheckedCreateWithoutLinkedAccountInput[]
  connectOrCreate?: Prisma.PlaidTransactionCreateOrConnectWithoutLinkedAccountInput | Prisma.PlaidTransactionCreateOrConnectWithoutLinkedAccountInput[]
  createMany?: Prisma.PlaidTransactionCreateManyLinkedAccountInputEnvelope
  connect?: Prisma.PlaidTransactionWhereUniqueInput | Prisma.PlaidTransactionWhereUniqueInput[]
}

export type PlaidTransactionUpdateManyWithoutLinkedAccountNestedInput = {
  create?: Prisma.XOR<Prisma.PlaidTransactionCreateWithoutLinkedAccountInput, Prisma.PlaidTransactionUncheckedCreateWithoutLinkedAccountInput> | Prisma.PlaidTransactionCreateWithoutLinkedAccountInput[] | Prisma.PlaidTransactionUncheckedCreateWithoutLinkedAccountInput[]
  connectOrCreate?: Prisma.PlaidTransactionCreateOrConnectWithoutLinkedAccountInput | Prisma.PlaidTransactionCreateOrConnectWithoutLinkedAccountInput[]
  upsert?: Prisma.PlaidTransactionUpsertWithWhereUniqueWithoutLinkedAccountInput | Prisma.PlaidTransactionUpsertWithWhereUniqueWithoutLinkedAccountInput[]
  createMany?: Prisma.PlaidTransactionCreateManyLinkedAccountInputEnvelope
  set?: Prisma.PlaidTransactionWhereUniqueInput | Prisma.PlaidTransactionWhereUniqueInput[]
  disconnect?: Prisma.PlaidTransactionWhereUniqueInput | Prisma.PlaidTransactionWhereUniqueInput[]
  delete?: Prisma.PlaidTransactionWhereUniqueInput | Prisma.PlaidTransactionWhereUniqueInput[]
  connect?: Prisma.PlaidTransactionWhereUniqueInput | Prisma.PlaidTransactionWhereUniqueInput[]
  update?: Prisma.PlaidTransactionUpdateWithWhereUniqueWithoutLinkedAccountInput | Prisma.PlaidTransactionUpdateWithWhereUniqueWithoutLinkedAccountInput[]
  updateMany?: Prisma.PlaidTransactionUpdateManyWithWhereWithoutLinkedAccountInput | Prisma.PlaidTransactionUpdateManyWithWhereWithoutLinkedAccountInput[]
  deleteMany?: Prisma.PlaidTransactionScalarWhereInput | Prisma.PlaidTransactionScalarWhereInput[]
}

export type PlaidTransactionUncheckedUpdateManyWithoutLinkedAccountNestedInput = {
  create?: Prisma.XOR<Prisma.PlaidTransactionCreateWithoutLinkedAccountInput, Prisma.PlaidTransactionUncheckedCreateWithoutLinkedAccountInput> | Prisma.PlaidTransactionCreateWithoutLinkedAccountInput[] | Prisma.PlaidTransactionUncheckedCreateWithoutLinkedAccountInput[]
  connectOrCreate?: Prisma.PlaidTransactionCreateOrConnectWithoutLinkedAccountInput | Prisma.PlaidTransactionCreateOrConnectWithoutLinkedAccountInput[]
  upsert?: Prisma.PlaidTransactionUpsertWithWhereUniqueWithoutLinkedAccountInput | Prisma.PlaidTransactionUpsertWithWhereUniqueWithoutLinkedAccountInput[]
  createMany?: Prisma.PlaidTransactionCreateManyLinkedAccountInputEnvelope
  set?: Prisma.PlaidTransactionWhereUniqueInput | Prisma.PlaidTransactionWhereUniqueInput[]
  disconnect?: Prisma.PlaidTransactionWhereUniqueInput | Prisma.PlaidTransactionWhereUniqueInput[]
  delete?: Prisma.PlaidTransactionWhereUniqueInput | Prisma.PlaidTransactionWhereUniqueInput[]
  connect?: Prisma.PlaidTransactionWhereUniqueInput | Prisma.PlaidTransactionWhereUniqueInput[]
  update?: Prisma.PlaidTransactionUpdateWithWhereUniqueWithoutLinkedAccountInput | Prisma.PlaidTransactionUpdateWithWhereUniqueWithoutLinkedAccountInput[]
  updateMany?: Prisma.PlaidTransactionUpdateManyWithWhereWithoutLinkedAccountInput | Prisma.PlaidTransactionUpdateManyWithWhereWithoutLinkedAccountInput[]
  deleteMany?: Prisma.PlaidTransactionScalarWhereInput | Prisma.PlaidTransactionScalarWhereInput[]
}

export type PlaidTransactionCreateWithoutLinkedAccountInput = {
  id?: string
  plaidTransactionId: string
  date: Date | string
  amount: number
  description: string
  merchant?: string | null
  category?: string | null
  createdAt?: Date | string
}

export type PlaidTransactionUncheckedCreateWithoutLinkedAccountInput = {
  id?: string
  plaidTransactionId: string
  date: Date | string
  amount: number
  description: string
  merchant?: string | null
  category?: string | null
  createdAt?: Date | string
}

export type PlaidTransactionCreateOrConnectWithoutLinkedAccountInput = {
  where: Prisma.PlaidTransactionWhereUniqueInput
  create: Prisma.XOR<Prisma.PlaidTransactionCreateWithoutLinkedAccountInput, Prisma.PlaidTransactionUncheckedCreateWithoutLinkedAccountInput>
}

export type PlaidTransactionCreateManyLinkedAccountInputEnvelope = {
  data: Prisma.PlaidTransactionCreateManyLinkedAccountInput | Prisma.PlaidTransactionCreateManyLinkedAccountInput[]
  skipDuplicates?: boolean
}

export type PlaidTransactionUpsertWithWhereUniqueWithoutLinkedAccountInput = {
  where: Prisma.PlaidTransactionWhereUniqueInput
  update: Prisma.XOR<Prisma.PlaidTransactionUpdateWithoutLinkedAccountInput, Prisma.PlaidTransactionUncheckedUpdateWithoutLinkedAccountInput>
  create: Prisma.XOR<Prisma.PlaidTransactionCreateWithoutLinkedAccountInput, Prisma.PlaidTransactionUncheckedCreateWithoutLinkedAccountInput>
}

export type PlaidTransactionUpdateWithWhereUniqueWithoutLinkedAccountInput = {
  where: Prisma.PlaidTransactionWhereUniqueInput
  data: Prisma.XOR<Prisma.PlaidTransactionUpdateWithoutLinkedAccountInput, Prisma.PlaidTransactionUncheckedUpdateWithoutLinkedAccountInput>
}

export type PlaidTransactionUpdateManyWithWhereWithoutLinkedAccountInput = {
  where: Prisma.PlaidTransactionScalarWhereInput
  data: Prisma.XOR<Prisma.PlaidTransactionUpdateManyMutationInput, Prisma.PlaidTransactionUncheckedUpdateManyWithoutLinkedAccountInput>
}

export type PlaidTransactionScalarWhereInput = {
  AND?: Prisma.PlaidTransactionScalarWhereInput | Prisma.PlaidTransactionScalarWhereInput[]
  OR?: Prisma.PlaidTransactionScalarWhereInput[]
  NOT?: Prisma.PlaidTransactionScalarWhereInput | Prisma.PlaidTransactionScalarWhereInput[]
  id?: Prisma.StringFilter<"PlaidTransaction"> | string
  plaidTransactionId?: Prisma.StringFilter<"PlaidTransaction"> | string
  date?: Prisma.DateTimeFilter<"PlaidTransaction"> | Date | string
  amount?: Prisma.FloatFilter<"PlaidTransaction"> | number
  description?: Prisma.StringFilter<"PlaidTransaction"> | string
  merchant?: Prisma.StringNullableFilter<"PlaidTransaction"> | string | null
  category?: Prisma.StringNullableFilter<"PlaidTransaction"> | string | null
  createdAt?: Prisma.DateTimeFilter<"PlaidTransaction"> | Date | string
  linkedAccountId?: Prisma.StringFilter<"PlaidTransaction"> | string
}

export type PlaidTransactionCreateManyLinkedAccountInput = {
  id?: string
  plaidTransactionId: string
  date: Date | string
  amount: number
  description: string
  merchant?: string | null
  category?: string | null
  createdAt?: Date | string
}

export type PlaidTransactionUpdateWithoutLinkedAccountInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  plaidTransactionId?: Prisma.StringFieldUpdateOperationsInput | string
  date?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  amount?: Prisma.FloatFieldUpdateOperationsInput | number
  description?: Prisma.StringFieldUpdateOperationsInput | string
  merchant?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  category?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type PlaidTransactionUncheckedUpdateWithoutLinkedAccountInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  plaidTransactionId?: Prisma.StringFieldUpdateOperationsInput | string
  date?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  amount?: Prisma.FloatFieldUpdateOperationsInput | number
  description?: Prisma.StringFieldUpdateOperationsInput | string
  merchant?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  category?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type PlaidTransactionUncheckedUpdateManyWithoutLinkedAccountInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  plaidTransactionId?: Prisma.StringFieldUpdateOperationsInput | string
  date?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  amount?: Prisma.FloatFieldUpdateOperationsInput | number
  description?: Prisma.StringFieldUpdateOperationsInput | string
  merchant?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  category?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type PlaidTransactionSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  plaidTransactionId?: boolean
  date?: boolean
  amount?: boolean
  description?: boolean
  merchant?: boolean
  category?: boolean
  createdAt?: boolean
  linkedAccountId?: boolean
  linkedAccount?: boolean | Prisma.LinkedBankAccountDefaultArgs<ExtArgs>
}, ExtArgs["result"]["plaidTransaction"]>

export type PlaidTransactionSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  plaidTransactionId?: boolean
  date?: boolean
  amount?: boolean
  description?: boolean
  merchant?: boolean
  category?: boolean
  createdAt?: boolean
  linkedAccountId?: boolean
  linkedAccount?: boolean | Prisma.LinkedBankAccountDefaultArgs<ExtArgs>
}, ExtArgs["result"]["plaidTransaction"]>

export type PlaidTransactionSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  plaidTransactionId?: boolean
  date?: boolean
  amount?: boolean
  description?: boolean
  merchant?: boolean
  category?: boolean
  createdAt?: boolean
  linkedAccountId?: boolean
  linkedAccount?: boolean | Prisma.LinkedBankAccountDefaultArgs<ExtArgs>
}, ExtArgs["result"]["plaidTransaction"]>

export type PlaidTransactionSelectScalar = {
  id?: boolean
  plaidTransactionId?: boolean
  date?: boolean
  amount?: boolean
  description?: boolean
  merchant?: boolean
  category?: boolean
  createdAt?: boolean
  linkedAccountId?: boolean
}

export type PlaidTransactionOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "plaidTransactionId" | "date" | "amount" | "description" | "merchant" | "category" | "createdAt" | "linkedAccountId", ExtArgs["result"]["plaidTransaction"]>
export type PlaidTransactionInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  linkedAccount?: boolean | Prisma.LinkedBankAccountDefaultArgs<ExtArgs>
}
export type PlaidTransactionIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  linkedAccount?: boolean | Prisma.LinkedBankAccountDefaultArgs<ExtArgs>
}
export type PlaidTransactionIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  linkedAccount?: boolean | Prisma.LinkedBankAccountDefaultArgs<ExtArgs>
}

export type $PlaidTransactionPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "PlaidTransaction"
  objects: {
    linkedAccount: Prisma.$LinkedBankAccountPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    plaidTransactionId: string
    date: Date
    amount: number
    description: string
    merchant: string | null
    category: string | null
    createdAt: Date
    linkedAccountId: string
  }, ExtArgs["result"]["plaidTransaction"]>
  composites: {}
}

export type PlaidTransactionGetPayload<S extends boolean | null | undefined | PlaidTransactionDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$PlaidTransactionPayload, S>

export type PlaidTransactionCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<PlaidTransactionFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: PlaidTransactionCountAggregateInputType | true
  }

export interface PlaidTransactionDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['PlaidTransaction'], meta: { name: 'PlaidTransaction' } }
  /**
   * Find zero or one PlaidTransaction that matches the filter.
   * @param {PlaidTransactionFindUniqueArgs} args - Arguments to find a PlaidTransaction
   * @example
   * // Get one PlaidTransaction
   * const plaidTransaction = await prisma.plaidTransaction.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends PlaidTransactionFindUniqueArgs>(args: Prisma.SelectSubset<T, PlaidTransactionFindUniqueArgs<ExtArgs>>): Prisma.Prisma__PlaidTransactionClient<runtime.Types.Result.GetResult<Prisma.$PlaidTransactionPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one PlaidTransaction that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {PlaidTransactionFindUniqueOrThrowArgs} args - Arguments to find a PlaidTransaction
   * @example
   * // Get one PlaidTransaction
   * const plaidTransaction = await prisma.plaidTransaction.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends PlaidTransactionFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, PlaidTransactionFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__PlaidTransactionClient<runtime.Types.Result.GetResult<Prisma.$PlaidTransactionPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first PlaidTransaction that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PlaidTransactionFindFirstArgs} args - Arguments to find a PlaidTransaction
   * @example
   * // Get one PlaidTransaction
   * const plaidTransaction = await prisma.plaidTransaction.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends PlaidTransactionFindFirstArgs>(args?: Prisma.SelectSubset<T, PlaidTransactionFindFirstArgs<ExtArgs>>): Prisma.Prisma__PlaidTransactionClient<runtime.Types.Result.GetResult<Prisma.$PlaidTransactionPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first PlaidTransaction that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PlaidTransactionFindFirstOrThrowArgs} args - Arguments to find a PlaidTransaction
   * @example
   * // Get one PlaidTransaction
   * const plaidTransaction = await prisma.plaidTransaction.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends PlaidTransactionFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, PlaidTransactionFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__PlaidTransactionClient<runtime.Types.Result.GetResult<Prisma.$PlaidTransactionPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more PlaidTransactions that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PlaidTransactionFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all PlaidTransactions
   * const plaidTransactions = await prisma.plaidTransaction.findMany()
   * 
   * // Get first 10 PlaidTransactions
   * const plaidTransactions = await prisma.plaidTransaction.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const plaidTransactionWithIdOnly = await prisma.plaidTransaction.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends PlaidTransactionFindManyArgs>(args?: Prisma.SelectSubset<T, PlaidTransactionFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$PlaidTransactionPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a PlaidTransaction.
   * @param {PlaidTransactionCreateArgs} args - Arguments to create a PlaidTransaction.
   * @example
   * // Create one PlaidTransaction
   * const PlaidTransaction = await prisma.plaidTransaction.create({
   *   data: {
   *     // ... data to create a PlaidTransaction
   *   }
   * })
   * 
   */
  create<T extends PlaidTransactionCreateArgs>(args: Prisma.SelectSubset<T, PlaidTransactionCreateArgs<ExtArgs>>): Prisma.Prisma__PlaidTransactionClient<runtime.Types.Result.GetResult<Prisma.$PlaidTransactionPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many PlaidTransactions.
   * @param {PlaidTransactionCreateManyArgs} args - Arguments to create many PlaidTransactions.
   * @example
   * // Create many PlaidTransactions
   * const plaidTransaction = await prisma.plaidTransaction.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends PlaidTransactionCreateManyArgs>(args?: Prisma.SelectSubset<T, PlaidTransactionCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many PlaidTransactions and returns the data saved in the database.
   * @param {PlaidTransactionCreateManyAndReturnArgs} args - Arguments to create many PlaidTransactions.
   * @example
   * // Create many PlaidTransactions
   * const plaidTransaction = await prisma.plaidTransaction.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many PlaidTransactions and only return the `id`
   * const plaidTransactionWithIdOnly = await prisma.plaidTransaction.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends PlaidTransactionCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, PlaidTransactionCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$PlaidTransactionPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a PlaidTransaction.
   * @param {PlaidTransactionDeleteArgs} args - Arguments to delete one PlaidTransaction.
   * @example
   * // Delete one PlaidTransaction
   * const PlaidTransaction = await prisma.plaidTransaction.delete({
   *   where: {
   *     // ... filter to delete one PlaidTransaction
   *   }
   * })
   * 
   */
  delete<T extends PlaidTransactionDeleteArgs>(args: Prisma.SelectSubset<T, PlaidTransactionDeleteArgs<ExtArgs>>): Prisma.Prisma__PlaidTransactionClient<runtime.Types.Result.GetResult<Prisma.$PlaidTransactionPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one PlaidTransaction.
   * @param {PlaidTransactionUpdateArgs} args - Arguments to update one PlaidTransaction.
   * @example
   * // Update one PlaidTransaction
   * const plaidTransaction = await prisma.plaidTransaction.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends PlaidTransactionUpdateArgs>(args: Prisma.SelectSubset<T, PlaidTransactionUpdateArgs<ExtArgs>>): Prisma.Prisma__PlaidTransactionClient<runtime.Types.Result.GetResult<Prisma.$PlaidTransactionPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more PlaidTransactions.
   * @param {PlaidTransactionDeleteManyArgs} args - Arguments to filter PlaidTransactions to delete.
   * @example
   * // Delete a few PlaidTransactions
   * const { count } = await prisma.plaidTransaction.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends PlaidTransactionDeleteManyArgs>(args?: Prisma.SelectSubset<T, PlaidTransactionDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more PlaidTransactions.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PlaidTransactionUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many PlaidTransactions
   * const plaidTransaction = await prisma.plaidTransaction.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends PlaidTransactionUpdateManyArgs>(args: Prisma.SelectSubset<T, PlaidTransactionUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more PlaidTransactions and returns the data updated in the database.
   * @param {PlaidTransactionUpdateManyAndReturnArgs} args - Arguments to update many PlaidTransactions.
   * @example
   * // Update many PlaidTransactions
   * const plaidTransaction = await prisma.plaidTransaction.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more PlaidTransactions and only return the `id`
   * const plaidTransactionWithIdOnly = await prisma.plaidTransaction.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends PlaidTransactionUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, PlaidTransactionUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$PlaidTransactionPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one PlaidTransaction.
   * @param {PlaidTransactionUpsertArgs} args - Arguments to update or create a PlaidTransaction.
   * @example
   * // Update or create a PlaidTransaction
   * const plaidTransaction = await prisma.plaidTransaction.upsert({
   *   create: {
   *     // ... data to create a PlaidTransaction
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the PlaidTransaction we want to update
   *   }
   * })
   */
  upsert<T extends PlaidTransactionUpsertArgs>(args: Prisma.SelectSubset<T, PlaidTransactionUpsertArgs<ExtArgs>>): Prisma.Prisma__PlaidTransactionClient<runtime.Types.Result.GetResult<Prisma.$PlaidTransactionPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of PlaidTransactions.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PlaidTransactionCountArgs} args - Arguments to filter PlaidTransactions to count.
   * @example
   * // Count the number of PlaidTransactions
   * const count = await prisma.plaidTransaction.count({
   *   where: {
   *     // ... the filter for the PlaidTransactions we want to count
   *   }
   * })
  **/
  count<T extends PlaidTransactionCountArgs>(
    args?: Prisma.Subset<T, PlaidTransactionCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], PlaidTransactionCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a PlaidTransaction.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PlaidTransactionAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends PlaidTransactionAggregateArgs>(args: Prisma.Subset<T, PlaidTransactionAggregateArgs>): Prisma.PrismaPromise<GetPlaidTransactionAggregateType<T>>

  /**
   * Group by PlaidTransaction.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PlaidTransactionGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends PlaidTransactionGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: PlaidTransactionGroupByArgs['orderBy'] }
      : { orderBy?: PlaidTransactionGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, PlaidTransactionGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetPlaidTransactionGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the PlaidTransaction model
 */
readonly fields: PlaidTransactionFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for PlaidTransaction.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__PlaidTransactionClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  linkedAccount<T extends Prisma.LinkedBankAccountDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.LinkedBankAccountDefaultArgs<ExtArgs>>): Prisma.Prisma__LinkedBankAccountClient<runtime.Types.Result.GetResult<Prisma.$LinkedBankAccountPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the PlaidTransaction model
 */
export interface PlaidTransactionFieldRefs {
  readonly id: Prisma.FieldRef<"PlaidTransaction", 'String'>
  readonly plaidTransactionId: Prisma.FieldRef<"PlaidTransaction", 'String'>
  readonly date: Prisma.FieldRef<"PlaidTransaction", 'DateTime'>
  readonly amount: Prisma.FieldRef<"PlaidTransaction", 'Float'>
  readonly description: Prisma.FieldRef<"PlaidTransaction", 'String'>
  readonly merchant: Prisma.FieldRef<"PlaidTransaction", 'String'>
  readonly category: Prisma.FieldRef<"PlaidTransaction", 'String'>
  readonly createdAt: Prisma.FieldRef<"PlaidTransaction", 'DateTime'>
  readonly linkedAccountId: Prisma.FieldRef<"PlaidTransaction", 'String'>
}
    

// Custom InputTypes
/**
 * PlaidTransaction findUnique
 */
export type PlaidTransactionFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PlaidTransaction
   */
  select?: Prisma.PlaidTransactionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PlaidTransaction
   */
  omit?: Prisma.PlaidTransactionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PlaidTransactionInclude<ExtArgs> | null
  /**
   * Filter, which PlaidTransaction to fetch.
   */
  where: Prisma.PlaidTransactionWhereUniqueInput
}

/**
 * PlaidTransaction findUniqueOrThrow
 */
export type PlaidTransactionFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PlaidTransaction
   */
  select?: Prisma.PlaidTransactionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PlaidTransaction
   */
  omit?: Prisma.PlaidTransactionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PlaidTransactionInclude<ExtArgs> | null
  /**
   * Filter, which PlaidTransaction to fetch.
   */
  where: Prisma.PlaidTransactionWhereUniqueInput
}

/**
 * PlaidTransaction findFirst
 */
export type PlaidTransactionFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PlaidTransaction
   */
  select?: Prisma.PlaidTransactionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PlaidTransaction
   */
  omit?: Prisma.PlaidTransactionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PlaidTransactionInclude<ExtArgs> | null
  /**
   * Filter, which PlaidTransaction to fetch.
   */
  where?: Prisma.PlaidTransactionWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of PlaidTransactions to fetch.
   */
  orderBy?: Prisma.PlaidTransactionOrderByWithRelationInput | Prisma.PlaidTransactionOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for PlaidTransactions.
   */
  cursor?: Prisma.PlaidTransactionWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` PlaidTransactions from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` PlaidTransactions.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of PlaidTransactions.
   */
  distinct?: Prisma.PlaidTransactionScalarFieldEnum | Prisma.PlaidTransactionScalarFieldEnum[]
}

/**
 * PlaidTransaction findFirstOrThrow
 */
export type PlaidTransactionFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PlaidTransaction
   */
  select?: Prisma.PlaidTransactionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PlaidTransaction
   */
  omit?: Prisma.PlaidTransactionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PlaidTransactionInclude<ExtArgs> | null
  /**
   * Filter, which PlaidTransaction to fetch.
   */
  where?: Prisma.PlaidTransactionWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of PlaidTransactions to fetch.
   */
  orderBy?: Prisma.PlaidTransactionOrderByWithRelationInput | Prisma.PlaidTransactionOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for PlaidTransactions.
   */
  cursor?: Prisma.PlaidTransactionWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` PlaidTransactions from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` PlaidTransactions.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of PlaidTransactions.
   */
  distinct?: Prisma.PlaidTransactionScalarFieldEnum | Prisma.PlaidTransactionScalarFieldEnum[]
}

/**
 * PlaidTransaction findMany
 */
export type PlaidTransactionFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PlaidTransaction
   */
  select?: Prisma.PlaidTransactionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PlaidTransaction
   */
  omit?: Prisma.PlaidTransactionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PlaidTransactionInclude<ExtArgs> | null
  /**
   * Filter, which PlaidTransactions to fetch.
   */
  where?: Prisma.PlaidTransactionWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of PlaidTransactions to fetch.
   */
  orderBy?: Prisma.PlaidTransactionOrderByWithRelationInput | Prisma.PlaidTransactionOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing PlaidTransactions.
   */
  cursor?: Prisma.PlaidTransactionWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` PlaidTransactions from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` PlaidTransactions.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of PlaidTransactions.
   */
  distinct?: Prisma.PlaidTransactionScalarFieldEnum | Prisma.PlaidTransactionScalarFieldEnum[]
}

/**
 * PlaidTransaction create
 */
export type PlaidTransactionCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PlaidTransaction
   */
  select?: Prisma.PlaidTransactionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PlaidTransaction
   */
  omit?: Prisma.PlaidTransactionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PlaidTransactionInclude<ExtArgs> | null
  /**
   * The data needed to create a PlaidTransaction.
   */
  data: Prisma.XOR<Prisma.PlaidTransactionCreateInput, Prisma.PlaidTransactionUncheckedCreateInput>
}

/**
 * PlaidTransaction createMany
 */
export type PlaidTransactionCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many PlaidTransactions.
   */
  data: Prisma.PlaidTransactionCreateManyInput | Prisma.PlaidTransactionCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * PlaidTransaction createManyAndReturn
 */
export type PlaidTransactionCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PlaidTransaction
   */
  select?: Prisma.PlaidTransactionSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the PlaidTransaction
   */
  omit?: Prisma.PlaidTransactionOmit<ExtArgs> | null
  /**
   * The data used to create many PlaidTransactions.
   */
  data: Prisma.PlaidTransactionCreateManyInput | Prisma.PlaidTransactionCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PlaidTransactionIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * PlaidTransaction update
 */
export type PlaidTransactionUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PlaidTransaction
   */
  select?: Prisma.PlaidTransactionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PlaidTransaction
   */
  omit?: Prisma.PlaidTransactionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PlaidTransactionInclude<ExtArgs> | null
  /**
   * The data needed to update a PlaidTransaction.
   */
  data: Prisma.XOR<Prisma.PlaidTransactionUpdateInput, Prisma.PlaidTransactionUncheckedUpdateInput>
  /**
   * Choose, which PlaidTransaction to update.
   */
  where: Prisma.PlaidTransactionWhereUniqueInput
}

/**
 * PlaidTransaction updateMany
 */
export type PlaidTransactionUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update PlaidTransactions.
   */
  data: Prisma.XOR<Prisma.PlaidTransactionUpdateManyMutationInput, Prisma.PlaidTransactionUncheckedUpdateManyInput>
  /**
   * Filter which PlaidTransactions to update
   */
  where?: Prisma.PlaidTransactionWhereInput
  /**
   * Limit how many PlaidTransactions to update.
   */
  limit?: number
}

/**
 * PlaidTransaction updateManyAndReturn
 */
export type PlaidTransactionUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PlaidTransaction
   */
  select?: Prisma.PlaidTransactionSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the PlaidTransaction
   */
  omit?: Prisma.PlaidTransactionOmit<ExtArgs> | null
  /**
   * The data used to update PlaidTransactions.
   */
  data: Prisma.XOR<Prisma.PlaidTransactionUpdateManyMutationInput, Prisma.PlaidTransactionUncheckedUpdateManyInput>
  /**
   * Filter which PlaidTransactions to update
   */
  where?: Prisma.PlaidTransactionWhereInput
  /**
   * Limit how many PlaidTransactions to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PlaidTransactionIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * PlaidTransaction upsert
 */
export type PlaidTransactionUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PlaidTransaction
   */
  select?: Prisma.PlaidTransactionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PlaidTransaction
   */
  omit?: Prisma.PlaidTransactionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PlaidTransactionInclude<ExtArgs> | null
  /**
   * The filter to search for the PlaidTransaction to update in case it exists.
   */
  where: Prisma.PlaidTransactionWhereUniqueInput
  /**
   * In case the PlaidTransaction found by the `where` argument doesn't exist, create a new PlaidTransaction with this data.
   */
  create: Prisma.XOR<Prisma.PlaidTransactionCreateInput, Prisma.PlaidTransactionUncheckedCreateInput>
  /**
   * In case the PlaidTransaction was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.PlaidTransactionUpdateInput, Prisma.PlaidTransactionUncheckedUpdateInput>
}

/**
 * PlaidTransaction delete
 */
export type PlaidTransactionDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PlaidTransaction
   */
  select?: Prisma.PlaidTransactionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PlaidTransaction
   */
  omit?: Prisma.PlaidTransactionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PlaidTransactionInclude<ExtArgs> | null
  /**
   * Filter which PlaidTransaction to delete.
   */
  where: Prisma.PlaidTransactionWhereUniqueInput
}

/**
 * PlaidTransaction deleteMany
 */
export type PlaidTransactionDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which PlaidTransactions to delete
   */
  where?: Prisma.PlaidTransactionWhereInput
  /**
   * Limit how many PlaidTransactions to delete.
   */
  limit?: number
}

/**
 * PlaidTransaction without action
 */
export type PlaidTransactionDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PlaidTransaction
   */
  select?: Prisma.PlaidTransactionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PlaidTransaction
   */
  omit?: Prisma.PlaidTransactionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PlaidTransactionInclude<ExtArgs> | null
}
