
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `PotContribution` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model PotContribution
 * 
 */
export type PotContributionModel = runtime.Types.Result.DefaultSelection<Prisma.$PotContributionPayload>

export type AggregatePotContribution = {
  _count: PotContributionCountAggregateOutputType | null
  _avg: PotContributionAvgAggregateOutputType | null
  _sum: PotContributionSumAggregateOutputType | null
  _min: PotContributionMinAggregateOutputType | null
  _max: PotContributionMaxAggregateOutputType | null
}

export type PotContributionAvgAggregateOutputType = {
  amount: number | null
}

export type PotContributionSumAggregateOutputType = {
  amount: number | null
}

export type PotContributionMinAggregateOutputType = {
  id: string | null
  amount: number | null
  date: Date | null
  potId: string | null
  memberId: string | null
}

export type PotContributionMaxAggregateOutputType = {
  id: string | null
  amount: number | null
  date: Date | null
  potId: string | null
  memberId: string | null
}

export type PotContributionCountAggregateOutputType = {
  id: number
  amount: number
  date: number
  potId: number
  memberId: number
  _all: number
}


export type PotContributionAvgAggregateInputType = {
  amount?: true
}

export type PotContributionSumAggregateInputType = {
  amount?: true
}

export type PotContributionMinAggregateInputType = {
  id?: true
  amount?: true
  date?: true
  potId?: true
  memberId?: true
}

export type PotContributionMaxAggregateInputType = {
  id?: true
  amount?: true
  date?: true
  potId?: true
  memberId?: true
}

export type PotContributionCountAggregateInputType = {
  id?: true
  amount?: true
  date?: true
  potId?: true
  memberId?: true
  _all?: true
}

export type PotContributionAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which PotContribution to aggregate.
   */
  where?: Prisma.PotContributionWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of PotContributions to fetch.
   */
  orderBy?: Prisma.PotContributionOrderByWithRelationInput | Prisma.PotContributionOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.PotContributionWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` PotContributions from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` PotContributions.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned PotContributions
  **/
  _count?: true | PotContributionCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: PotContributionAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: PotContributionSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: PotContributionMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: PotContributionMaxAggregateInputType
}

export type GetPotContributionAggregateType<T extends PotContributionAggregateArgs> = {
      [P in keyof T & keyof AggregatePotContribution]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregatePotContribution[P]>
    : Prisma.GetScalarType<T[P], AggregatePotContribution[P]>
}




export type PotContributionGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.PotContributionWhereInput
  orderBy?: Prisma.PotContributionOrderByWithAggregationInput | Prisma.PotContributionOrderByWithAggregationInput[]
  by: Prisma.PotContributionScalarFieldEnum[] | Prisma.PotContributionScalarFieldEnum
  having?: Prisma.PotContributionScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: PotContributionCountAggregateInputType | true
  _avg?: PotContributionAvgAggregateInputType
  _sum?: PotContributionSumAggregateInputType
  _min?: PotContributionMinAggregateInputType
  _max?: PotContributionMaxAggregateInputType
}

export type PotContributionGroupByOutputType = {
  id: string
  amount: number
  date: Date
  potId: string
  memberId: string
  _count: PotContributionCountAggregateOutputType | null
  _avg: PotContributionAvgAggregateOutputType | null
  _sum: PotContributionSumAggregateOutputType | null
  _min: PotContributionMinAggregateOutputType | null
  _max: PotContributionMaxAggregateOutputType | null
}

export type GetPotContributionGroupByPayload<T extends PotContributionGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<PotContributionGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof PotContributionGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], PotContributionGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], PotContributionGroupByOutputType[P]>
      }
    >
  >



export type PotContributionWhereInput = {
  AND?: Prisma.PotContributionWhereInput | Prisma.PotContributionWhereInput[]
  OR?: Prisma.PotContributionWhereInput[]
  NOT?: Prisma.PotContributionWhereInput | Prisma.PotContributionWhereInput[]
  id?: Prisma.StringFilter<"PotContribution"> | string
  amount?: Prisma.FloatFilter<"PotContribution"> | number
  date?: Prisma.DateTimeFilter<"PotContribution"> | Date | string
  potId?: Prisma.StringFilter<"PotContribution"> | string
  memberId?: Prisma.StringFilter<"PotContribution"> | string
  pot?: Prisma.XOR<Prisma.PotScalarRelationFilter, Prisma.PotWhereInput>
  member?: Prisma.XOR<Prisma.HouseholdMemberScalarRelationFilter, Prisma.HouseholdMemberWhereInput>
}

export type PotContributionOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  amount?: Prisma.SortOrder
  date?: Prisma.SortOrder
  potId?: Prisma.SortOrder
  memberId?: Prisma.SortOrder
  pot?: Prisma.PotOrderByWithRelationInput
  member?: Prisma.HouseholdMemberOrderByWithRelationInput
}

export type PotContributionWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.PotContributionWhereInput | Prisma.PotContributionWhereInput[]
  OR?: Prisma.PotContributionWhereInput[]
  NOT?: Prisma.PotContributionWhereInput | Prisma.PotContributionWhereInput[]
  amount?: Prisma.FloatFilter<"PotContribution"> | number
  date?: Prisma.DateTimeFilter<"PotContribution"> | Date | string
  potId?: Prisma.StringFilter<"PotContribution"> | string
  memberId?: Prisma.StringFilter<"PotContribution"> | string
  pot?: Prisma.XOR<Prisma.PotScalarRelationFilter, Prisma.PotWhereInput>
  member?: Prisma.XOR<Prisma.HouseholdMemberScalarRelationFilter, Prisma.HouseholdMemberWhereInput>
}, "id">

export type PotContributionOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  amount?: Prisma.SortOrder
  date?: Prisma.SortOrder
  potId?: Prisma.SortOrder
  memberId?: Prisma.SortOrder
  _count?: Prisma.PotContributionCountOrderByAggregateInput
  _avg?: Prisma.PotContributionAvgOrderByAggregateInput
  _max?: Prisma.PotContributionMaxOrderByAggregateInput
  _min?: Prisma.PotContributionMinOrderByAggregateInput
  _sum?: Prisma.PotContributionSumOrderByAggregateInput
}

export type PotContributionScalarWhereWithAggregatesInput = {
  AND?: Prisma.PotContributionScalarWhereWithAggregatesInput | Prisma.PotContributionScalarWhereWithAggregatesInput[]
  OR?: Prisma.PotContributionScalarWhereWithAggregatesInput[]
  NOT?: Prisma.PotContributionScalarWhereWithAggregatesInput | Prisma.PotContributionScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"PotContribution"> | string
  amount?: Prisma.FloatWithAggregatesFilter<"PotContribution"> | number
  date?: Prisma.DateTimeWithAggregatesFilter<"PotContribution"> | Date | string
  potId?: Prisma.StringWithAggregatesFilter<"PotContribution"> | string
  memberId?: Prisma.StringWithAggregatesFilter<"PotContribution"> | string
}

export type PotContributionCreateInput = {
  id?: string
  amount: number
  date?: Date | string
  pot: Prisma.PotCreateNestedOneWithoutContributionsInput
  member: Prisma.HouseholdMemberCreateNestedOneWithoutPotContributionsInput
}

export type PotContributionUncheckedCreateInput = {
  id?: string
  amount: number
  date?: Date | string
  potId: string
  memberId: string
}

export type PotContributionUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  amount?: Prisma.FloatFieldUpdateOperationsInput | number
  date?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  pot?: Prisma.PotUpdateOneRequiredWithoutContributionsNestedInput
  member?: Prisma.HouseholdMemberUpdateOneRequiredWithoutPotContributionsNestedInput
}

export type PotContributionUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  amount?: Prisma.FloatFieldUpdateOperationsInput | number
  date?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  potId?: Prisma.StringFieldUpdateOperationsInput | string
  memberId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type PotContributionCreateManyInput = {
  id?: string
  amount: number
  date?: Date | string
  potId: string
  memberId: string
}

export type PotContributionUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  amount?: Prisma.FloatFieldUpdateOperationsInput | number
  date?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type PotContributionUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  amount?: Prisma.FloatFieldUpdateOperationsInput | number
  date?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  potId?: Prisma.StringFieldUpdateOperationsInput | string
  memberId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type PotContributionListRelationFilter = {
  every?: Prisma.PotContributionWhereInput
  some?: Prisma.PotContributionWhereInput
  none?: Prisma.PotContributionWhereInput
}

export type PotContributionOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type PotContributionCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  amount?: Prisma.SortOrder
  date?: Prisma.SortOrder
  potId?: Prisma.SortOrder
  memberId?: Prisma.SortOrder
}

export type PotContributionAvgOrderByAggregateInput = {
  amount?: Prisma.SortOrder
}

export type PotContributionMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  amount?: Prisma.SortOrder
  date?: Prisma.SortOrder
  potId?: Prisma.SortOrder
  memberId?: Prisma.SortOrder
}

export type PotContributionMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  amount?: Prisma.SortOrder
  date?: Prisma.SortOrder
  potId?: Prisma.SortOrder
  memberId?: Prisma.SortOrder
}

export type PotContributionSumOrderByAggregateInput = {
  amount?: Prisma.SortOrder
}

export type PotContributionCreateNestedManyWithoutMemberInput = {
  create?: Prisma.XOR<Prisma.PotContributionCreateWithoutMemberInput, Prisma.PotContributionUncheckedCreateWithoutMemberInput> | Prisma.PotContributionCreateWithoutMemberInput[] | Prisma.PotContributionUncheckedCreateWithoutMemberInput[]
  connectOrCreate?: Prisma.PotContributionCreateOrConnectWithoutMemberInput | Prisma.PotContributionCreateOrConnectWithoutMemberInput[]
  createMany?: Prisma.PotContributionCreateManyMemberInputEnvelope
  connect?: Prisma.PotContributionWhereUniqueInput | Prisma.PotContributionWhereUniqueInput[]
}

export type PotContributionUncheckedCreateNestedManyWithoutMemberInput = {
  create?: Prisma.XOR<Prisma.PotContributionCreateWithoutMemberInput, Prisma.PotContributionUncheckedCreateWithoutMemberInput> | Prisma.PotContributionCreateWithoutMemberInput[] | Prisma.PotContributionUncheckedCreateWithoutMemberInput[]
  connectOrCreate?: Prisma.PotContributionCreateOrConnectWithoutMemberInput | Prisma.PotContributionCreateOrConnectWithoutMemberInput[]
  createMany?: Prisma.PotContributionCreateManyMemberInputEnvelope
  connect?: Prisma.PotContributionWhereUniqueInput | Prisma.PotContributionWhereUniqueInput[]
}

export type PotContributionUpdateManyWithoutMemberNestedInput = {
  create?: Prisma.XOR<Prisma.PotContributionCreateWithoutMemberInput, Prisma.PotContributionUncheckedCreateWithoutMemberInput> | Prisma.PotContributionCreateWithoutMemberInput[] | Prisma.PotContributionUncheckedCreateWithoutMemberInput[]
  connectOrCreate?: Prisma.PotContributionCreateOrConnectWithoutMemberInput | Prisma.PotContributionCreateOrConnectWithoutMemberInput[]
  upsert?: Prisma.PotContributionUpsertWithWhereUniqueWithoutMemberInput | Prisma.PotContributionUpsertWithWhereUniqueWithoutMemberInput[]
  createMany?: Prisma.PotContributionCreateManyMemberInputEnvelope
  set?: Prisma.PotContributionWhereUniqueInput | Prisma.PotContributionWhereUniqueInput[]
  disconnect?: Prisma.PotContributionWhereUniqueInput | Prisma.PotContributionWhereUniqueInput[]
  delete?: Prisma.PotContributionWhereUniqueInput | Prisma.PotContributionWhereUniqueInput[]
  connect?: Prisma.PotContributionWhereUniqueInput | Prisma.PotContributionWhereUniqueInput[]
  update?: Prisma.PotContributionUpdateWithWhereUniqueWithoutMemberInput | Prisma.PotContributionUpdateWithWhereUniqueWithoutMemberInput[]
  updateMany?: Prisma.PotContributionUpdateManyWithWhereWithoutMemberInput | Prisma.PotContributionUpdateManyWithWhereWithoutMemberInput[]
  deleteMany?: Prisma.PotContributionScalarWhereInput | Prisma.PotContributionScalarWhereInput[]
}

export type PotContributionUncheckedUpdateManyWithoutMemberNestedInput = {
  create?: Prisma.XOR<Prisma.PotContributionCreateWithoutMemberInput, Prisma.PotContributionUncheckedCreateWithoutMemberInput> | Prisma.PotContributionCreateWithoutMemberInput[] | Prisma.PotContributionUncheckedCreateWithoutMemberInput[]
  connectOrCreate?: Prisma.PotContributionCreateOrConnectWithoutMemberInput | Prisma.PotContributionCreateOrConnectWithoutMemberInput[]
  upsert?: Prisma.PotContributionUpsertWithWhereUniqueWithoutMemberInput | Prisma.PotContributionUpsertWithWhereUniqueWithoutMemberInput[]
  createMany?: Prisma.PotContributionCreateManyMemberInputEnvelope
  set?: Prisma.PotContributionWhereUniqueInput | Prisma.PotContributionWhereUniqueInput[]
  disconnect?: Prisma.PotContributionWhereUniqueInput | Prisma.PotContributionWhereUniqueInput[]
  delete?: Prisma.PotContributionWhereUniqueInput | Prisma.PotContributionWhereUniqueInput[]
  connect?: Prisma.PotContributionWhereUniqueInput | Prisma.PotContributionWhereUniqueInput[]
  update?: Prisma.PotContributionUpdateWithWhereUniqueWithoutMemberInput | Prisma.PotContributionUpdateWithWhereUniqueWithoutMemberInput[]
  updateMany?: Prisma.PotContributionUpdateManyWithWhereWithoutMemberInput | Prisma.PotContributionUpdateManyWithWhereWithoutMemberInput[]
  deleteMany?: Prisma.PotContributionScalarWhereInput | Prisma.PotContributionScalarWhereInput[]
}

export type PotContributionCreateNestedManyWithoutPotInput = {
  create?: Prisma.XOR<Prisma.PotContributionCreateWithoutPotInput, Prisma.PotContributionUncheckedCreateWithoutPotInput> | Prisma.PotContributionCreateWithoutPotInput[] | Prisma.PotContributionUncheckedCreateWithoutPotInput[]
  connectOrCreate?: Prisma.PotContributionCreateOrConnectWithoutPotInput | Prisma.PotContributionCreateOrConnectWithoutPotInput[]
  createMany?: Prisma.PotContributionCreateManyPotInputEnvelope
  connect?: Prisma.PotContributionWhereUniqueInput | Prisma.PotContributionWhereUniqueInput[]
}

export type PotContributionUncheckedCreateNestedManyWithoutPotInput = {
  create?: Prisma.XOR<Prisma.PotContributionCreateWithoutPotInput, Prisma.PotContributionUncheckedCreateWithoutPotInput> | Prisma.PotContributionCreateWithoutPotInput[] | Prisma.PotContributionUncheckedCreateWithoutPotInput[]
  connectOrCreate?: Prisma.PotContributionCreateOrConnectWithoutPotInput | Prisma.PotContributionCreateOrConnectWithoutPotInput[]
  createMany?: Prisma.PotContributionCreateManyPotInputEnvelope
  connect?: Prisma.PotContributionWhereUniqueInput | Prisma.PotContributionWhereUniqueInput[]
}

export type PotContributionUpdateManyWithoutPotNestedInput = {
  create?: Prisma.XOR<Prisma.PotContributionCreateWithoutPotInput, Prisma.PotContributionUncheckedCreateWithoutPotInput> | Prisma.PotContributionCreateWithoutPotInput[] | Prisma.PotContributionUncheckedCreateWithoutPotInput[]
  connectOrCreate?: Prisma.PotContributionCreateOrConnectWithoutPotInput | Prisma.PotContributionCreateOrConnectWithoutPotInput[]
  upsert?: Prisma.PotContributionUpsertWithWhereUniqueWithoutPotInput | Prisma.PotContributionUpsertWithWhereUniqueWithoutPotInput[]
  createMany?: Prisma.PotContributionCreateManyPotInputEnvelope
  set?: Prisma.PotContributionWhereUniqueInput | Prisma.PotContributionWhereUniqueInput[]
  disconnect?: Prisma.PotContributionWhereUniqueInput | Prisma.PotContributionWhereUniqueInput[]
  delete?: Prisma.PotContributionWhereUniqueInput | Prisma.PotContributionWhereUniqueInput[]
  connect?: Prisma.PotContributionWhereUniqueInput | Prisma.PotContributionWhereUniqueInput[]
  update?: Prisma.PotContributionUpdateWithWhereUniqueWithoutPotInput | Prisma.PotContributionUpdateWithWhereUniqueWithoutPotInput[]
  updateMany?: Prisma.PotContributionUpdateManyWithWhereWithoutPotInput | Prisma.PotContributionUpdateManyWithWhereWithoutPotInput[]
  deleteMany?: Prisma.PotContributionScalarWhereInput | Prisma.PotContributionScalarWhereInput[]
}

export type PotContributionUncheckedUpdateManyWithoutPotNestedInput = {
  create?: Prisma.XOR<Prisma.PotContributionCreateWithoutPotInput, Prisma.PotContributionUncheckedCreateWithoutPotInput> | Prisma.PotContributionCreateWithoutPotInput[] | Prisma.PotContributionUncheckedCreateWithoutPotInput[]
  connectOrCreate?: Prisma.PotContributionCreateOrConnectWithoutPotInput | Prisma.PotContributionCreateOrConnectWithoutPotInput[]
  upsert?: Prisma.PotContributionUpsertWithWhereUniqueWithoutPotInput | Prisma.PotContributionUpsertWithWhereUniqueWithoutPotInput[]
  createMany?: Prisma.PotContributionCreateManyPotInputEnvelope
  set?: Prisma.PotContributionWhereUniqueInput | Prisma.PotContributionWhereUniqueInput[]
  disconnect?: Prisma.PotContributionWhereUniqueInput | Prisma.PotContributionWhereUniqueInput[]
  delete?: Prisma.PotContributionWhereUniqueInput | Prisma.PotContributionWhereUniqueInput[]
  connect?: Prisma.PotContributionWhereUniqueInput | Prisma.PotContributionWhereUniqueInput[]
  update?: Prisma.PotContributionUpdateWithWhereUniqueWithoutPotInput | Prisma.PotContributionUpdateWithWhereUniqueWithoutPotInput[]
  updateMany?: Prisma.PotContributionUpdateManyWithWhereWithoutPotInput | Prisma.PotContributionUpdateManyWithWhereWithoutPotInput[]
  deleteMany?: Prisma.PotContributionScalarWhereInput | Prisma.PotContributionScalarWhereInput[]
}

export type PotContributionCreateWithoutMemberInput = {
  id?: string
  amount: number
  date?: Date | string
  pot: Prisma.PotCreateNestedOneWithoutContributionsInput
}

export type PotContributionUncheckedCreateWithoutMemberInput = {
  id?: string
  amount: number
  date?: Date | string
  potId: string
}

export type PotContributionCreateOrConnectWithoutMemberInput = {
  where: Prisma.PotContributionWhereUniqueInput
  create: Prisma.XOR<Prisma.PotContributionCreateWithoutMemberInput, Prisma.PotContributionUncheckedCreateWithoutMemberInput>
}

export type PotContributionCreateManyMemberInputEnvelope = {
  data: Prisma.PotContributionCreateManyMemberInput | Prisma.PotContributionCreateManyMemberInput[]
  skipDuplicates?: boolean
}

export type PotContributionUpsertWithWhereUniqueWithoutMemberInput = {
  where: Prisma.PotContributionWhereUniqueInput
  update: Prisma.XOR<Prisma.PotContributionUpdateWithoutMemberInput, Prisma.PotContributionUncheckedUpdateWithoutMemberInput>
  create: Prisma.XOR<Prisma.PotContributionCreateWithoutMemberInput, Prisma.PotContributionUncheckedCreateWithoutMemberInput>
}

export type PotContributionUpdateWithWhereUniqueWithoutMemberInput = {
  where: Prisma.PotContributionWhereUniqueInput
  data: Prisma.XOR<Prisma.PotContributionUpdateWithoutMemberInput, Prisma.PotContributionUncheckedUpdateWithoutMemberInput>
}

export type PotContributionUpdateManyWithWhereWithoutMemberInput = {
  where: Prisma.PotContributionScalarWhereInput
  data: Prisma.XOR<Prisma.PotContributionUpdateManyMutationInput, Prisma.PotContributionUncheckedUpdateManyWithoutMemberInput>
}

export type PotContributionScalarWhereInput = {
  AND?: Prisma.PotContributionScalarWhereInput | Prisma.PotContributionScalarWhereInput[]
  OR?: Prisma.PotContributionScalarWhereInput[]
  NOT?: Prisma.PotContributionScalarWhereInput | Prisma.PotContributionScalarWhereInput[]
  id?: Prisma.StringFilter<"PotContribution"> | string
  amount?: Prisma.FloatFilter<"PotContribution"> | number
  date?: Prisma.DateTimeFilter<"PotContribution"> | Date | string
  potId?: Prisma.StringFilter<"PotContribution"> | string
  memberId?: Prisma.StringFilter<"PotContribution"> | string
}

export type PotContributionCreateWithoutPotInput = {
  id?: string
  amount: number
  date?: Date | string
  member: Prisma.HouseholdMemberCreateNestedOneWithoutPotContributionsInput
}

export type PotContributionUncheckedCreateWithoutPotInput = {
  id?: string
  amount: number
  date?: Date | string
  memberId: string
}

export type PotContributionCreateOrConnectWithoutPotInput = {
  where: Prisma.PotContributionWhereUniqueInput
  create: Prisma.XOR<Prisma.PotContributionCreateWithoutPotInput, Prisma.PotContributionUncheckedCreateWithoutPotInput>
}

export type PotContributionCreateManyPotInputEnvelope = {
  data: Prisma.PotContributionCreateManyPotInput | Prisma.PotContributionCreateManyPotInput[]
  skipDuplicates?: boolean
}

export type PotContributionUpsertWithWhereUniqueWithoutPotInput = {
  where: Prisma.PotContributionWhereUniqueInput
  update: Prisma.XOR<Prisma.PotContributionUpdateWithoutPotInput, Prisma.PotContributionUncheckedUpdateWithoutPotInput>
  create: Prisma.XOR<Prisma.PotContributionCreateWithoutPotInput, Prisma.PotContributionUncheckedCreateWithoutPotInput>
}

export type PotContributionUpdateWithWhereUniqueWithoutPotInput = {
  where: Prisma.PotContributionWhereUniqueInput
  data: Prisma.XOR<Prisma.PotContributionUpdateWithoutPotInput, Prisma.PotContributionUncheckedUpdateWithoutPotInput>
}

export type PotContributionUpdateManyWithWhereWithoutPotInput = {
  where: Prisma.PotContributionScalarWhereInput
  data: Prisma.XOR<Prisma.PotContributionUpdateManyMutationInput, Prisma.PotContributionUncheckedUpdateManyWithoutPotInput>
}

export type PotContributionCreateManyMemberInput = {
  id?: string
  amount: number
  date?: Date | string
  potId: string
}

export type PotContributionUpdateWithoutMemberInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  amount?: Prisma.FloatFieldUpdateOperationsInput | number
  date?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  pot?: Prisma.PotUpdateOneRequiredWithoutContributionsNestedInput
}

export type PotContributionUncheckedUpdateWithoutMemberInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  amount?: Prisma.FloatFieldUpdateOperationsInput | number
  date?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  potId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type PotContributionUncheckedUpdateManyWithoutMemberInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  amount?: Prisma.FloatFieldUpdateOperationsInput | number
  date?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  potId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type PotContributionCreateManyPotInput = {
  id?: string
  amount: number
  date?: Date | string
  memberId: string
}

export type PotContributionUpdateWithoutPotInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  amount?: Prisma.FloatFieldUpdateOperationsInput | number
  date?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  member?: Prisma.HouseholdMemberUpdateOneRequiredWithoutPotContributionsNestedInput
}

export type PotContributionUncheckedUpdateWithoutPotInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  amount?: Prisma.FloatFieldUpdateOperationsInput | number
  date?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  memberId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type PotContributionUncheckedUpdateManyWithoutPotInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  amount?: Prisma.FloatFieldUpdateOperationsInput | number
  date?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  memberId?: Prisma.StringFieldUpdateOperationsInput | string
}



export type PotContributionSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  amount?: boolean
  date?: boolean
  potId?: boolean
  memberId?: boolean
  pot?: boolean | Prisma.PotDefaultArgs<ExtArgs>
  member?: boolean | Prisma.HouseholdMemberDefaultArgs<ExtArgs>
}, ExtArgs["result"]["potContribution"]>

export type PotContributionSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  amount?: boolean
  date?: boolean
  potId?: boolean
  memberId?: boolean
  pot?: boolean | Prisma.PotDefaultArgs<ExtArgs>
  member?: boolean | Prisma.HouseholdMemberDefaultArgs<ExtArgs>
}, ExtArgs["result"]["potContribution"]>

export type PotContributionSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  amount?: boolean
  date?: boolean
  potId?: boolean
  memberId?: boolean
  pot?: boolean | Prisma.PotDefaultArgs<ExtArgs>
  member?: boolean | Prisma.HouseholdMemberDefaultArgs<ExtArgs>
}, ExtArgs["result"]["potContribution"]>

export type PotContributionSelectScalar = {
  id?: boolean
  amount?: boolean
  date?: boolean
  potId?: boolean
  memberId?: boolean
}

export type PotContributionOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "amount" | "date" | "potId" | "memberId", ExtArgs["result"]["potContribution"]>
export type PotContributionInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  pot?: boolean | Prisma.PotDefaultArgs<ExtArgs>
  member?: boolean | Prisma.HouseholdMemberDefaultArgs<ExtArgs>
}
export type PotContributionIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  pot?: boolean | Prisma.PotDefaultArgs<ExtArgs>
  member?: boolean | Prisma.HouseholdMemberDefaultArgs<ExtArgs>
}
export type PotContributionIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  pot?: boolean | Prisma.PotDefaultArgs<ExtArgs>
  member?: boolean | Prisma.HouseholdMemberDefaultArgs<ExtArgs>
}

export type $PotContributionPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "PotContribution"
  objects: {
    pot: Prisma.$PotPayload<ExtArgs>
    member: Prisma.$HouseholdMemberPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    amount: number
    date: Date
    potId: string
    memberId: string
  }, ExtArgs["result"]["potContribution"]>
  composites: {}
}

export type PotContributionGetPayload<S extends boolean | null | undefined | PotContributionDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$PotContributionPayload, S>

export type PotContributionCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<PotContributionFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: PotContributionCountAggregateInputType | true
  }

export interface PotContributionDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['PotContribution'], meta: { name: 'PotContribution' } }
  /**
   * Find zero or one PotContribution that matches the filter.
   * @param {PotContributionFindUniqueArgs} args - Arguments to find a PotContribution
   * @example
   * // Get one PotContribution
   * const potContribution = await prisma.potContribution.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends PotContributionFindUniqueArgs>(args: Prisma.SelectSubset<T, PotContributionFindUniqueArgs<ExtArgs>>): Prisma.Prisma__PotContributionClient<runtime.Types.Result.GetResult<Prisma.$PotContributionPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one PotContribution that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {PotContributionFindUniqueOrThrowArgs} args - Arguments to find a PotContribution
   * @example
   * // Get one PotContribution
   * const potContribution = await prisma.potContribution.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends PotContributionFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, PotContributionFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__PotContributionClient<runtime.Types.Result.GetResult<Prisma.$PotContributionPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first PotContribution that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PotContributionFindFirstArgs} args - Arguments to find a PotContribution
   * @example
   * // Get one PotContribution
   * const potContribution = await prisma.potContribution.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends PotContributionFindFirstArgs>(args?: Prisma.SelectSubset<T, PotContributionFindFirstArgs<ExtArgs>>): Prisma.Prisma__PotContributionClient<runtime.Types.Result.GetResult<Prisma.$PotContributionPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first PotContribution that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PotContributionFindFirstOrThrowArgs} args - Arguments to find a PotContribution
   * @example
   * // Get one PotContribution
   * const potContribution = await prisma.potContribution.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends PotContributionFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, PotContributionFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__PotContributionClient<runtime.Types.Result.GetResult<Prisma.$PotContributionPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more PotContributions that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PotContributionFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all PotContributions
   * const potContributions = await prisma.potContribution.findMany()
   * 
   * // Get first 10 PotContributions
   * const potContributions = await prisma.potContribution.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const potContributionWithIdOnly = await prisma.potContribution.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends PotContributionFindManyArgs>(args?: Prisma.SelectSubset<T, PotContributionFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$PotContributionPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a PotContribution.
   * @param {PotContributionCreateArgs} args - Arguments to create a PotContribution.
   * @example
   * // Create one PotContribution
   * const PotContribution = await prisma.potContribution.create({
   *   data: {
   *     // ... data to create a PotContribution
   *   }
   * })
   * 
   */
  create<T extends PotContributionCreateArgs>(args: Prisma.SelectSubset<T, PotContributionCreateArgs<ExtArgs>>): Prisma.Prisma__PotContributionClient<runtime.Types.Result.GetResult<Prisma.$PotContributionPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many PotContributions.
   * @param {PotContributionCreateManyArgs} args - Arguments to create many PotContributions.
   * @example
   * // Create many PotContributions
   * const potContribution = await prisma.potContribution.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends PotContributionCreateManyArgs>(args?: Prisma.SelectSubset<T, PotContributionCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many PotContributions and returns the data saved in the database.
   * @param {PotContributionCreateManyAndReturnArgs} args - Arguments to create many PotContributions.
   * @example
   * // Create many PotContributions
   * const potContribution = await prisma.potContribution.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many PotContributions and only return the `id`
   * const potContributionWithIdOnly = await prisma.potContribution.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends PotContributionCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, PotContributionCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$PotContributionPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a PotContribution.
   * @param {PotContributionDeleteArgs} args - Arguments to delete one PotContribution.
   * @example
   * // Delete one PotContribution
   * const PotContribution = await prisma.potContribution.delete({
   *   where: {
   *     // ... filter to delete one PotContribution
   *   }
   * })
   * 
   */
  delete<T extends PotContributionDeleteArgs>(args: Prisma.SelectSubset<T, PotContributionDeleteArgs<ExtArgs>>): Prisma.Prisma__PotContributionClient<runtime.Types.Result.GetResult<Prisma.$PotContributionPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one PotContribution.
   * @param {PotContributionUpdateArgs} args - Arguments to update one PotContribution.
   * @example
   * // Update one PotContribution
   * const potContribution = await prisma.potContribution.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends PotContributionUpdateArgs>(args: Prisma.SelectSubset<T, PotContributionUpdateArgs<ExtArgs>>): Prisma.Prisma__PotContributionClient<runtime.Types.Result.GetResult<Prisma.$PotContributionPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more PotContributions.
   * @param {PotContributionDeleteManyArgs} args - Arguments to filter PotContributions to delete.
   * @example
   * // Delete a few PotContributions
   * const { count } = await prisma.potContribution.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends PotContributionDeleteManyArgs>(args?: Prisma.SelectSubset<T, PotContributionDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more PotContributions.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PotContributionUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many PotContributions
   * const potContribution = await prisma.potContribution.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends PotContributionUpdateManyArgs>(args: Prisma.SelectSubset<T, PotContributionUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more PotContributions and returns the data updated in the database.
   * @param {PotContributionUpdateManyAndReturnArgs} args - Arguments to update many PotContributions.
   * @example
   * // Update many PotContributions
   * const potContribution = await prisma.potContribution.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more PotContributions and only return the `id`
   * const potContributionWithIdOnly = await prisma.potContribution.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends PotContributionUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, PotContributionUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$PotContributionPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one PotContribution.
   * @param {PotContributionUpsertArgs} args - Arguments to update or create a PotContribution.
   * @example
   * // Update or create a PotContribution
   * const potContribution = await prisma.potContribution.upsert({
   *   create: {
   *     // ... data to create a PotContribution
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the PotContribution we want to update
   *   }
   * })
   */
  upsert<T extends PotContributionUpsertArgs>(args: Prisma.SelectSubset<T, PotContributionUpsertArgs<ExtArgs>>): Prisma.Prisma__PotContributionClient<runtime.Types.Result.GetResult<Prisma.$PotContributionPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of PotContributions.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PotContributionCountArgs} args - Arguments to filter PotContributions to count.
   * @example
   * // Count the number of PotContributions
   * const count = await prisma.potContribution.count({
   *   where: {
   *     // ... the filter for the PotContributions we want to count
   *   }
   * })
  **/
  count<T extends PotContributionCountArgs>(
    args?: Prisma.Subset<T, PotContributionCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], PotContributionCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a PotContribution.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PotContributionAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends PotContributionAggregateArgs>(args: Prisma.Subset<T, PotContributionAggregateArgs>): Prisma.PrismaPromise<GetPotContributionAggregateType<T>>

  /**
   * Group by PotContribution.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PotContributionGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends PotContributionGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: PotContributionGroupByArgs['orderBy'] }
      : { orderBy?: PotContributionGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, PotContributionGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetPotContributionGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the PotContribution model
 */
readonly fields: PotContributionFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for PotContribution.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__PotContributionClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  pot<T extends Prisma.PotDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.PotDefaultArgs<ExtArgs>>): Prisma.Prisma__PotClient<runtime.Types.Result.GetResult<Prisma.$PotPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  member<T extends Prisma.HouseholdMemberDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.HouseholdMemberDefaultArgs<ExtArgs>>): Prisma.Prisma__HouseholdMemberClient<runtime.Types.Result.GetResult<Prisma.$HouseholdMemberPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the PotContribution model
 */
export interface PotContributionFieldRefs {
  readonly id: Prisma.FieldRef<"PotContribution", 'String'>
  readonly amount: Prisma.FieldRef<"PotContribution", 'Float'>
  readonly date: Prisma.FieldRef<"PotContribution", 'DateTime'>
  readonly potId: Prisma.FieldRef<"PotContribution", 'String'>
  readonly memberId: Prisma.FieldRef<"PotContribution", 'String'>
}
    

// Custom InputTypes
/**
 * PotContribution findUnique
 */
export type PotContributionFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PotContribution
   */
  select?: Prisma.PotContributionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PotContribution
   */
  omit?: Prisma.PotContributionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PotContributionInclude<ExtArgs> | null
  /**
   * Filter, which PotContribution to fetch.
   */
  where: Prisma.PotContributionWhereUniqueInput
}

/**
 * PotContribution findUniqueOrThrow
 */
export type PotContributionFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PotContribution
   */
  select?: Prisma.PotContributionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PotContribution
   */
  omit?: Prisma.PotContributionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PotContributionInclude<ExtArgs> | null
  /**
   * Filter, which PotContribution to fetch.
   */
  where: Prisma.PotContributionWhereUniqueInput
}

/**
 * PotContribution findFirst
 */
export type PotContributionFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PotContribution
   */
  select?: Prisma.PotContributionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PotContribution
   */
  omit?: Prisma.PotContributionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PotContributionInclude<ExtArgs> | null
  /**
   * Filter, which PotContribution to fetch.
   */
  where?: Prisma.PotContributionWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of PotContributions to fetch.
   */
  orderBy?: Prisma.PotContributionOrderByWithRelationInput | Prisma.PotContributionOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for PotContributions.
   */
  cursor?: Prisma.PotContributionWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` PotContributions from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` PotContributions.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of PotContributions.
   */
  distinct?: Prisma.PotContributionScalarFieldEnum | Prisma.PotContributionScalarFieldEnum[]
}

/**
 * PotContribution findFirstOrThrow
 */
export type PotContributionFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PotContribution
   */
  select?: Prisma.PotContributionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PotContribution
   */
  omit?: Prisma.PotContributionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PotContributionInclude<ExtArgs> | null
  /**
   * Filter, which PotContribution to fetch.
   */
  where?: Prisma.PotContributionWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of PotContributions to fetch.
   */
  orderBy?: Prisma.PotContributionOrderByWithRelationInput | Prisma.PotContributionOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for PotContributions.
   */
  cursor?: Prisma.PotContributionWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` PotContributions from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` PotContributions.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of PotContributions.
   */
  distinct?: Prisma.PotContributionScalarFieldEnum | Prisma.PotContributionScalarFieldEnum[]
}

/**
 * PotContribution findMany
 */
export type PotContributionFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PotContribution
   */
  select?: Prisma.PotContributionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PotContribution
   */
  omit?: Prisma.PotContributionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PotContributionInclude<ExtArgs> | null
  /**
   * Filter, which PotContributions to fetch.
   */
  where?: Prisma.PotContributionWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of PotContributions to fetch.
   */
  orderBy?: Prisma.PotContributionOrderByWithRelationInput | Prisma.PotContributionOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing PotContributions.
   */
  cursor?: Prisma.PotContributionWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` PotContributions from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` PotContributions.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of PotContributions.
   */
  distinct?: Prisma.PotContributionScalarFieldEnum | Prisma.PotContributionScalarFieldEnum[]
}

/**
 * PotContribution create
 */
export type PotContributionCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PotContribution
   */
  select?: Prisma.PotContributionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PotContribution
   */
  omit?: Prisma.PotContributionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PotContributionInclude<ExtArgs> | null
  /**
   * The data needed to create a PotContribution.
   */
  data: Prisma.XOR<Prisma.PotContributionCreateInput, Prisma.PotContributionUncheckedCreateInput>
}

/**
 * PotContribution createMany
 */
export type PotContributionCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many PotContributions.
   */
  data: Prisma.PotContributionCreateManyInput | Prisma.PotContributionCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * PotContribution createManyAndReturn
 */
export type PotContributionCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PotContribution
   */
  select?: Prisma.PotContributionSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the PotContribution
   */
  omit?: Prisma.PotContributionOmit<ExtArgs> | null
  /**
   * The data used to create many PotContributions.
   */
  data: Prisma.PotContributionCreateManyInput | Prisma.PotContributionCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PotContributionIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * PotContribution update
 */
export type PotContributionUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PotContribution
   */
  select?: Prisma.PotContributionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PotContribution
   */
  omit?: Prisma.PotContributionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PotContributionInclude<ExtArgs> | null
  /**
   * The data needed to update a PotContribution.
   */
  data: Prisma.XOR<Prisma.PotContributionUpdateInput, Prisma.PotContributionUncheckedUpdateInput>
  /**
   * Choose, which PotContribution to update.
   */
  where: Prisma.PotContributionWhereUniqueInput
}

/**
 * PotContribution updateMany
 */
export type PotContributionUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update PotContributions.
   */
  data: Prisma.XOR<Prisma.PotContributionUpdateManyMutationInput, Prisma.PotContributionUncheckedUpdateManyInput>
  /**
   * Filter which PotContributions to update
   */
  where?: Prisma.PotContributionWhereInput
  /**
   * Limit how many PotContributions to update.
   */
  limit?: number
}

/**
 * PotContribution updateManyAndReturn
 */
export type PotContributionUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PotContribution
   */
  select?: Prisma.PotContributionSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the PotContribution
   */
  omit?: Prisma.PotContributionOmit<ExtArgs> | null
  /**
   * The data used to update PotContributions.
   */
  data: Prisma.XOR<Prisma.PotContributionUpdateManyMutationInput, Prisma.PotContributionUncheckedUpdateManyInput>
  /**
   * Filter which PotContributions to update
   */
  where?: Prisma.PotContributionWhereInput
  /**
   * Limit how many PotContributions to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PotContributionIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * PotContribution upsert
 */
export type PotContributionUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PotContribution
   */
  select?: Prisma.PotContributionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PotContribution
   */
  omit?: Prisma.PotContributionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PotContributionInclude<ExtArgs> | null
  /**
   * The filter to search for the PotContribution to update in case it exists.
   */
  where: Prisma.PotContributionWhereUniqueInput
  /**
   * In case the PotContribution found by the `where` argument doesn't exist, create a new PotContribution with this data.
   */
  create: Prisma.XOR<Prisma.PotContributionCreateInput, Prisma.PotContributionUncheckedCreateInput>
  /**
   * In case the PotContribution was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.PotContributionUpdateInput, Prisma.PotContributionUncheckedUpdateInput>
}

/**
 * PotContribution delete
 */
export type PotContributionDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PotContribution
   */
  select?: Prisma.PotContributionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PotContribution
   */
  omit?: Prisma.PotContributionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PotContributionInclude<ExtArgs> | null
  /**
   * Filter which PotContribution to delete.
   */
  where: Prisma.PotContributionWhereUniqueInput
}

/**
 * PotContribution deleteMany
 */
export type PotContributionDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which PotContributions to delete
   */
  where?: Prisma.PotContributionWhereInput
  /**
   * Limit how many PotContributions to delete.
   */
  limit?: number
}

/**
 * PotContribution without action
 */
export type PotContributionDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PotContribution
   */
  select?: Prisma.PotContributionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PotContribution
   */
  omit?: Prisma.PotContributionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PotContributionInclude<ExtArgs> | null
}
