
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `SignUpSession` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model SignUpSession
 * 
 */
export type SignUpSessionModel = runtime.Types.Result.DefaultSelection<Prisma.$SignUpSessionPayload>

export type AggregateSignUpSession = {
  _count: SignUpSessionCountAggregateOutputType | null
  _avg: SignUpSessionAvgAggregateOutputType | null
  _sum: SignUpSessionSumAggregateOutputType | null
  _min: SignUpSessionMinAggregateOutputType | null
  _max: SignUpSessionMaxAggregateOutputType | null
}

export type SignUpSessionAvgAggregateOutputType = {
  annualWage: number | null
}

export type SignUpSessionSumAggregateOutputType = {
  annualWage: number | null
}

export type SignUpSessionMinAggregateOutputType = {
  id: string | null
  email: string | null
  name: string | null
  passwordHash: string | null
  job: string | null
  annualWage: number | null
  businessName: string | null
  selectedBanks: string | null
  expiresAt: Date | null
  createdAt: Date | null
}

export type SignUpSessionMaxAggregateOutputType = {
  id: string | null
  email: string | null
  name: string | null
  passwordHash: string | null
  job: string | null
  annualWage: number | null
  businessName: string | null
  selectedBanks: string | null
  expiresAt: Date | null
  createdAt: Date | null
}

export type SignUpSessionCountAggregateOutputType = {
  id: number
  email: number
  name: number
  passwordHash: number
  job: number
  annualWage: number
  businessName: number
  selectedBanks: number
  expiresAt: number
  createdAt: number
  _all: number
}


export type SignUpSessionAvgAggregateInputType = {
  annualWage?: true
}

export type SignUpSessionSumAggregateInputType = {
  annualWage?: true
}

export type SignUpSessionMinAggregateInputType = {
  id?: true
  email?: true
  name?: true
  passwordHash?: true
  job?: true
  annualWage?: true
  businessName?: true
  selectedBanks?: true
  expiresAt?: true
  createdAt?: true
}

export type SignUpSessionMaxAggregateInputType = {
  id?: true
  email?: true
  name?: true
  passwordHash?: true
  job?: true
  annualWage?: true
  businessName?: true
  selectedBanks?: true
  expiresAt?: true
  createdAt?: true
}

export type SignUpSessionCountAggregateInputType = {
  id?: true
  email?: true
  name?: true
  passwordHash?: true
  job?: true
  annualWage?: true
  businessName?: true
  selectedBanks?: true
  expiresAt?: true
  createdAt?: true
  _all?: true
}

export type SignUpSessionAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which SignUpSession to aggregate.
   */
  where?: Prisma.SignUpSessionWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of SignUpSessions to fetch.
   */
  orderBy?: Prisma.SignUpSessionOrderByWithRelationInput | Prisma.SignUpSessionOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.SignUpSessionWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` SignUpSessions from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` SignUpSessions.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned SignUpSessions
  **/
  _count?: true | SignUpSessionCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: SignUpSessionAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: SignUpSessionSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: SignUpSessionMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: SignUpSessionMaxAggregateInputType
}

export type GetSignUpSessionAggregateType<T extends SignUpSessionAggregateArgs> = {
      [P in keyof T & keyof AggregateSignUpSession]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateSignUpSession[P]>
    : Prisma.GetScalarType<T[P], AggregateSignUpSession[P]>
}




export type SignUpSessionGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.SignUpSessionWhereInput
  orderBy?: Prisma.SignUpSessionOrderByWithAggregationInput | Prisma.SignUpSessionOrderByWithAggregationInput[]
  by: Prisma.SignUpSessionScalarFieldEnum[] | Prisma.SignUpSessionScalarFieldEnum
  having?: Prisma.SignUpSessionScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: SignUpSessionCountAggregateInputType | true
  _avg?: SignUpSessionAvgAggregateInputType
  _sum?: SignUpSessionSumAggregateInputType
  _min?: SignUpSessionMinAggregateInputType
  _max?: SignUpSessionMaxAggregateInputType
}

export type SignUpSessionGroupByOutputType = {
  id: string
  email: string
  name: string
  passwordHash: string
  job: string
  annualWage: number
  businessName: string | null
  selectedBanks: string
  expiresAt: Date
  createdAt: Date
  _count: SignUpSessionCountAggregateOutputType | null
  _avg: SignUpSessionAvgAggregateOutputType | null
  _sum: SignUpSessionSumAggregateOutputType | null
  _min: SignUpSessionMinAggregateOutputType | null
  _max: SignUpSessionMaxAggregateOutputType | null
}

export type GetSignUpSessionGroupByPayload<T extends SignUpSessionGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<SignUpSessionGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof SignUpSessionGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], SignUpSessionGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], SignUpSessionGroupByOutputType[P]>
      }
    >
  >



export type SignUpSessionWhereInput = {
  AND?: Prisma.SignUpSessionWhereInput | Prisma.SignUpSessionWhereInput[]
  OR?: Prisma.SignUpSessionWhereInput[]
  NOT?: Prisma.SignUpSessionWhereInput | Prisma.SignUpSessionWhereInput[]
  id?: Prisma.StringFilter<"SignUpSession"> | string
  email?: Prisma.StringFilter<"SignUpSession"> | string
  name?: Prisma.StringFilter<"SignUpSession"> | string
  passwordHash?: Prisma.StringFilter<"SignUpSession"> | string
  job?: Prisma.StringFilter<"SignUpSession"> | string
  annualWage?: Prisma.FloatFilter<"SignUpSession"> | number
  businessName?: Prisma.StringNullableFilter<"SignUpSession"> | string | null
  selectedBanks?: Prisma.StringFilter<"SignUpSession"> | string
  expiresAt?: Prisma.DateTimeFilter<"SignUpSession"> | Date | string
  createdAt?: Prisma.DateTimeFilter<"SignUpSession"> | Date | string
}

export type SignUpSessionOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  email?: Prisma.SortOrder
  name?: Prisma.SortOrder
  passwordHash?: Prisma.SortOrder
  job?: Prisma.SortOrder
  annualWage?: Prisma.SortOrder
  businessName?: Prisma.SortOrderInput | Prisma.SortOrder
  selectedBanks?: Prisma.SortOrder
  expiresAt?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type SignUpSessionWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  email?: string
  AND?: Prisma.SignUpSessionWhereInput | Prisma.SignUpSessionWhereInput[]
  OR?: Prisma.SignUpSessionWhereInput[]
  NOT?: Prisma.SignUpSessionWhereInput | Prisma.SignUpSessionWhereInput[]
  name?: Prisma.StringFilter<"SignUpSession"> | string
  passwordHash?: Prisma.StringFilter<"SignUpSession"> | string
  job?: Prisma.StringFilter<"SignUpSession"> | string
  annualWage?: Prisma.FloatFilter<"SignUpSession"> | number
  businessName?: Prisma.StringNullableFilter<"SignUpSession"> | string | null
  selectedBanks?: Prisma.StringFilter<"SignUpSession"> | string
  expiresAt?: Prisma.DateTimeFilter<"SignUpSession"> | Date | string
  createdAt?: Prisma.DateTimeFilter<"SignUpSession"> | Date | string
}, "id" | "email">

export type SignUpSessionOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  email?: Prisma.SortOrder
  name?: Prisma.SortOrder
  passwordHash?: Prisma.SortOrder
  job?: Prisma.SortOrder
  annualWage?: Prisma.SortOrder
  businessName?: Prisma.SortOrderInput | Prisma.SortOrder
  selectedBanks?: Prisma.SortOrder
  expiresAt?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  _count?: Prisma.SignUpSessionCountOrderByAggregateInput
  _avg?: Prisma.SignUpSessionAvgOrderByAggregateInput
  _max?: Prisma.SignUpSessionMaxOrderByAggregateInput
  _min?: Prisma.SignUpSessionMinOrderByAggregateInput
  _sum?: Prisma.SignUpSessionSumOrderByAggregateInput
}

export type SignUpSessionScalarWhereWithAggregatesInput = {
  AND?: Prisma.SignUpSessionScalarWhereWithAggregatesInput | Prisma.SignUpSessionScalarWhereWithAggregatesInput[]
  OR?: Prisma.SignUpSessionScalarWhereWithAggregatesInput[]
  NOT?: Prisma.SignUpSessionScalarWhereWithAggregatesInput | Prisma.SignUpSessionScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"SignUpSession"> | string
  email?: Prisma.StringWithAggregatesFilter<"SignUpSession"> | string
  name?: Prisma.StringWithAggregatesFilter<"SignUpSession"> | string
  passwordHash?: Prisma.StringWithAggregatesFilter<"SignUpSession"> | string
  job?: Prisma.StringWithAggregatesFilter<"SignUpSession"> | string
  annualWage?: Prisma.FloatWithAggregatesFilter<"SignUpSession"> | number
  businessName?: Prisma.StringNullableWithAggregatesFilter<"SignUpSession"> | string | null
  selectedBanks?: Prisma.StringWithAggregatesFilter<"SignUpSession"> | string
  expiresAt?: Prisma.DateTimeWithAggregatesFilter<"SignUpSession"> | Date | string
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"SignUpSession"> | Date | string
}

export type SignUpSessionCreateInput = {
  id?: string
  email: string
  name: string
  passwordHash: string
  job: string
  annualWage: number
  businessName?: string | null
  selectedBanks?: string
  expiresAt: Date | string
  createdAt?: Date | string
}

export type SignUpSessionUncheckedCreateInput = {
  id?: string
  email: string
  name: string
  passwordHash: string
  job: string
  annualWage: number
  businessName?: string | null
  selectedBanks?: string
  expiresAt: Date | string
  createdAt?: Date | string
}

export type SignUpSessionUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  passwordHash?: Prisma.StringFieldUpdateOperationsInput | string
  job?: Prisma.StringFieldUpdateOperationsInput | string
  annualWage?: Prisma.FloatFieldUpdateOperationsInput | number
  businessName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  selectedBanks?: Prisma.StringFieldUpdateOperationsInput | string
  expiresAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type SignUpSessionUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  passwordHash?: Prisma.StringFieldUpdateOperationsInput | string
  job?: Prisma.StringFieldUpdateOperationsInput | string
  annualWage?: Prisma.FloatFieldUpdateOperationsInput | number
  businessName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  selectedBanks?: Prisma.StringFieldUpdateOperationsInput | string
  expiresAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type SignUpSessionCreateManyInput = {
  id?: string
  email: string
  name: string
  passwordHash: string
  job: string
  annualWage: number
  businessName?: string | null
  selectedBanks?: string
  expiresAt: Date | string
  createdAt?: Date | string
}

export type SignUpSessionUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  passwordHash?: Prisma.StringFieldUpdateOperationsInput | string
  job?: Prisma.StringFieldUpdateOperationsInput | string
  annualWage?: Prisma.FloatFieldUpdateOperationsInput | number
  businessName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  selectedBanks?: Prisma.StringFieldUpdateOperationsInput | string
  expiresAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type SignUpSessionUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  passwordHash?: Prisma.StringFieldUpdateOperationsInput | string
  job?: Prisma.StringFieldUpdateOperationsInput | string
  annualWage?: Prisma.FloatFieldUpdateOperationsInput | number
  businessName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  selectedBanks?: Prisma.StringFieldUpdateOperationsInput | string
  expiresAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type SignUpSessionCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  email?: Prisma.SortOrder
  name?: Prisma.SortOrder
  passwordHash?: Prisma.SortOrder
  job?: Prisma.SortOrder
  annualWage?: Prisma.SortOrder
  businessName?: Prisma.SortOrder
  selectedBanks?: Prisma.SortOrder
  expiresAt?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type SignUpSessionAvgOrderByAggregateInput = {
  annualWage?: Prisma.SortOrder
}

export type SignUpSessionMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  email?: Prisma.SortOrder
  name?: Prisma.SortOrder
  passwordHash?: Prisma.SortOrder
  job?: Prisma.SortOrder
  annualWage?: Prisma.SortOrder
  businessName?: Prisma.SortOrder
  selectedBanks?: Prisma.SortOrder
  expiresAt?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type SignUpSessionMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  email?: Prisma.SortOrder
  name?: Prisma.SortOrder
  passwordHash?: Prisma.SortOrder
  job?: Prisma.SortOrder
  annualWage?: Prisma.SortOrder
  businessName?: Prisma.SortOrder
  selectedBanks?: Prisma.SortOrder
  expiresAt?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type SignUpSessionSumOrderByAggregateInput = {
  annualWage?: Prisma.SortOrder
}

export type FloatFieldUpdateOperationsInput = {
  set?: number
  increment?: number
  decrement?: number
  multiply?: number
  divide?: number
}



export type SignUpSessionSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  email?: boolean
  name?: boolean
  passwordHash?: boolean
  job?: boolean
  annualWage?: boolean
  businessName?: boolean
  selectedBanks?: boolean
  expiresAt?: boolean
  createdAt?: boolean
}, ExtArgs["result"]["signUpSession"]>

export type SignUpSessionSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  email?: boolean
  name?: boolean
  passwordHash?: boolean
  job?: boolean
  annualWage?: boolean
  businessName?: boolean
  selectedBanks?: boolean
  expiresAt?: boolean
  createdAt?: boolean
}, ExtArgs["result"]["signUpSession"]>

export type SignUpSessionSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  email?: boolean
  name?: boolean
  passwordHash?: boolean
  job?: boolean
  annualWage?: boolean
  businessName?: boolean
  selectedBanks?: boolean
  expiresAt?: boolean
  createdAt?: boolean
}, ExtArgs["result"]["signUpSession"]>

export type SignUpSessionSelectScalar = {
  id?: boolean
  email?: boolean
  name?: boolean
  passwordHash?: boolean
  job?: boolean
  annualWage?: boolean
  businessName?: boolean
  selectedBanks?: boolean
  expiresAt?: boolean
  createdAt?: boolean
}

export type SignUpSessionOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "email" | "name" | "passwordHash" | "job" | "annualWage" | "businessName" | "selectedBanks" | "expiresAt" | "createdAt", ExtArgs["result"]["signUpSession"]>

export type $SignUpSessionPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "SignUpSession"
  objects: {}
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    email: string
    name: string
    passwordHash: string
    job: string
    annualWage: number
    businessName: string | null
    selectedBanks: string
    expiresAt: Date
    createdAt: Date
  }, ExtArgs["result"]["signUpSession"]>
  composites: {}
}

export type SignUpSessionGetPayload<S extends boolean | null | undefined | SignUpSessionDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$SignUpSessionPayload, S>

export type SignUpSessionCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<SignUpSessionFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: SignUpSessionCountAggregateInputType | true
  }

export interface SignUpSessionDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['SignUpSession'], meta: { name: 'SignUpSession' } }
  /**
   * Find zero or one SignUpSession that matches the filter.
   * @param {SignUpSessionFindUniqueArgs} args - Arguments to find a SignUpSession
   * @example
   * // Get one SignUpSession
   * const signUpSession = await prisma.signUpSession.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends SignUpSessionFindUniqueArgs>(args: Prisma.SelectSubset<T, SignUpSessionFindUniqueArgs<ExtArgs>>): Prisma.Prisma__SignUpSessionClient<runtime.Types.Result.GetResult<Prisma.$SignUpSessionPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one SignUpSession that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {SignUpSessionFindUniqueOrThrowArgs} args - Arguments to find a SignUpSession
   * @example
   * // Get one SignUpSession
   * const signUpSession = await prisma.signUpSession.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends SignUpSessionFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, SignUpSessionFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__SignUpSessionClient<runtime.Types.Result.GetResult<Prisma.$SignUpSessionPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first SignUpSession that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SignUpSessionFindFirstArgs} args - Arguments to find a SignUpSession
   * @example
   * // Get one SignUpSession
   * const signUpSession = await prisma.signUpSession.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends SignUpSessionFindFirstArgs>(args?: Prisma.SelectSubset<T, SignUpSessionFindFirstArgs<ExtArgs>>): Prisma.Prisma__SignUpSessionClient<runtime.Types.Result.GetResult<Prisma.$SignUpSessionPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first SignUpSession that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SignUpSessionFindFirstOrThrowArgs} args - Arguments to find a SignUpSession
   * @example
   * // Get one SignUpSession
   * const signUpSession = await prisma.signUpSession.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends SignUpSessionFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, SignUpSessionFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__SignUpSessionClient<runtime.Types.Result.GetResult<Prisma.$SignUpSessionPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more SignUpSessions that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SignUpSessionFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all SignUpSessions
   * const signUpSessions = await prisma.signUpSession.findMany()
   * 
   * // Get first 10 SignUpSessions
   * const signUpSessions = await prisma.signUpSession.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const signUpSessionWithIdOnly = await prisma.signUpSession.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends SignUpSessionFindManyArgs>(args?: Prisma.SelectSubset<T, SignUpSessionFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$SignUpSessionPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a SignUpSession.
   * @param {SignUpSessionCreateArgs} args - Arguments to create a SignUpSession.
   * @example
   * // Create one SignUpSession
   * const SignUpSession = await prisma.signUpSession.create({
   *   data: {
   *     // ... data to create a SignUpSession
   *   }
   * })
   * 
   */
  create<T extends SignUpSessionCreateArgs>(args: Prisma.SelectSubset<T, SignUpSessionCreateArgs<ExtArgs>>): Prisma.Prisma__SignUpSessionClient<runtime.Types.Result.GetResult<Prisma.$SignUpSessionPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many SignUpSessions.
   * @param {SignUpSessionCreateManyArgs} args - Arguments to create many SignUpSessions.
   * @example
   * // Create many SignUpSessions
   * const signUpSession = await prisma.signUpSession.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends SignUpSessionCreateManyArgs>(args?: Prisma.SelectSubset<T, SignUpSessionCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many SignUpSessions and returns the data saved in the database.
   * @param {SignUpSessionCreateManyAndReturnArgs} args - Arguments to create many SignUpSessions.
   * @example
   * // Create many SignUpSessions
   * const signUpSession = await prisma.signUpSession.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many SignUpSessions and only return the `id`
   * const signUpSessionWithIdOnly = await prisma.signUpSession.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends SignUpSessionCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, SignUpSessionCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$SignUpSessionPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a SignUpSession.
   * @param {SignUpSessionDeleteArgs} args - Arguments to delete one SignUpSession.
   * @example
   * // Delete one SignUpSession
   * const SignUpSession = await prisma.signUpSession.delete({
   *   where: {
   *     // ... filter to delete one SignUpSession
   *   }
   * })
   * 
   */
  delete<T extends SignUpSessionDeleteArgs>(args: Prisma.SelectSubset<T, SignUpSessionDeleteArgs<ExtArgs>>): Prisma.Prisma__SignUpSessionClient<runtime.Types.Result.GetResult<Prisma.$SignUpSessionPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one SignUpSession.
   * @param {SignUpSessionUpdateArgs} args - Arguments to update one SignUpSession.
   * @example
   * // Update one SignUpSession
   * const signUpSession = await prisma.signUpSession.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends SignUpSessionUpdateArgs>(args: Prisma.SelectSubset<T, SignUpSessionUpdateArgs<ExtArgs>>): Prisma.Prisma__SignUpSessionClient<runtime.Types.Result.GetResult<Prisma.$SignUpSessionPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more SignUpSessions.
   * @param {SignUpSessionDeleteManyArgs} args - Arguments to filter SignUpSessions to delete.
   * @example
   * // Delete a few SignUpSessions
   * const { count } = await prisma.signUpSession.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends SignUpSessionDeleteManyArgs>(args?: Prisma.SelectSubset<T, SignUpSessionDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more SignUpSessions.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SignUpSessionUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many SignUpSessions
   * const signUpSession = await prisma.signUpSession.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends SignUpSessionUpdateManyArgs>(args: Prisma.SelectSubset<T, SignUpSessionUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more SignUpSessions and returns the data updated in the database.
   * @param {SignUpSessionUpdateManyAndReturnArgs} args - Arguments to update many SignUpSessions.
   * @example
   * // Update many SignUpSessions
   * const signUpSession = await prisma.signUpSession.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more SignUpSessions and only return the `id`
   * const signUpSessionWithIdOnly = await prisma.signUpSession.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends SignUpSessionUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, SignUpSessionUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$SignUpSessionPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one SignUpSession.
   * @param {SignUpSessionUpsertArgs} args - Arguments to update or create a SignUpSession.
   * @example
   * // Update or create a SignUpSession
   * const signUpSession = await prisma.signUpSession.upsert({
   *   create: {
   *     // ... data to create a SignUpSession
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the SignUpSession we want to update
   *   }
   * })
   */
  upsert<T extends SignUpSessionUpsertArgs>(args: Prisma.SelectSubset<T, SignUpSessionUpsertArgs<ExtArgs>>): Prisma.Prisma__SignUpSessionClient<runtime.Types.Result.GetResult<Prisma.$SignUpSessionPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of SignUpSessions.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SignUpSessionCountArgs} args - Arguments to filter SignUpSessions to count.
   * @example
   * // Count the number of SignUpSessions
   * const count = await prisma.signUpSession.count({
   *   where: {
   *     // ... the filter for the SignUpSessions we want to count
   *   }
   * })
  **/
  count<T extends SignUpSessionCountArgs>(
    args?: Prisma.Subset<T, SignUpSessionCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], SignUpSessionCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a SignUpSession.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SignUpSessionAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends SignUpSessionAggregateArgs>(args: Prisma.Subset<T, SignUpSessionAggregateArgs>): Prisma.PrismaPromise<GetSignUpSessionAggregateType<T>>

  /**
   * Group by SignUpSession.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SignUpSessionGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends SignUpSessionGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: SignUpSessionGroupByArgs['orderBy'] }
      : { orderBy?: SignUpSessionGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, SignUpSessionGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetSignUpSessionGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the SignUpSession model
 */
readonly fields: SignUpSessionFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for SignUpSession.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__SignUpSessionClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the SignUpSession model
 */
export interface SignUpSessionFieldRefs {
  readonly id: Prisma.FieldRef<"SignUpSession", 'String'>
  readonly email: Prisma.FieldRef<"SignUpSession", 'String'>
  readonly name: Prisma.FieldRef<"SignUpSession", 'String'>
  readonly passwordHash: Prisma.FieldRef<"SignUpSession", 'String'>
  readonly job: Prisma.FieldRef<"SignUpSession", 'String'>
  readonly annualWage: Prisma.FieldRef<"SignUpSession", 'Float'>
  readonly businessName: Prisma.FieldRef<"SignUpSession", 'String'>
  readonly selectedBanks: Prisma.FieldRef<"SignUpSession", 'String'>
  readonly expiresAt: Prisma.FieldRef<"SignUpSession", 'DateTime'>
  readonly createdAt: Prisma.FieldRef<"SignUpSession", 'DateTime'>
}
    

// Custom InputTypes
/**
 * SignUpSession findUnique
 */
export type SignUpSessionFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SignUpSession
   */
  select?: Prisma.SignUpSessionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SignUpSession
   */
  omit?: Prisma.SignUpSessionOmit<ExtArgs> | null
  /**
   * Filter, which SignUpSession to fetch.
   */
  where: Prisma.SignUpSessionWhereUniqueInput
}

/**
 * SignUpSession findUniqueOrThrow
 */
export type SignUpSessionFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SignUpSession
   */
  select?: Prisma.SignUpSessionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SignUpSession
   */
  omit?: Prisma.SignUpSessionOmit<ExtArgs> | null
  /**
   * Filter, which SignUpSession to fetch.
   */
  where: Prisma.SignUpSessionWhereUniqueInput
}

/**
 * SignUpSession findFirst
 */
export type SignUpSessionFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SignUpSession
   */
  select?: Prisma.SignUpSessionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SignUpSession
   */
  omit?: Prisma.SignUpSessionOmit<ExtArgs> | null
  /**
   * Filter, which SignUpSession to fetch.
   */
  where?: Prisma.SignUpSessionWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of SignUpSessions to fetch.
   */
  orderBy?: Prisma.SignUpSessionOrderByWithRelationInput | Prisma.SignUpSessionOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for SignUpSessions.
   */
  cursor?: Prisma.SignUpSessionWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` SignUpSessions from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` SignUpSessions.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of SignUpSessions.
   */
  distinct?: Prisma.SignUpSessionScalarFieldEnum | Prisma.SignUpSessionScalarFieldEnum[]
}

/**
 * SignUpSession findFirstOrThrow
 */
export type SignUpSessionFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SignUpSession
   */
  select?: Prisma.SignUpSessionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SignUpSession
   */
  omit?: Prisma.SignUpSessionOmit<ExtArgs> | null
  /**
   * Filter, which SignUpSession to fetch.
   */
  where?: Prisma.SignUpSessionWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of SignUpSessions to fetch.
   */
  orderBy?: Prisma.SignUpSessionOrderByWithRelationInput | Prisma.SignUpSessionOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for SignUpSessions.
   */
  cursor?: Prisma.SignUpSessionWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` SignUpSessions from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` SignUpSessions.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of SignUpSessions.
   */
  distinct?: Prisma.SignUpSessionScalarFieldEnum | Prisma.SignUpSessionScalarFieldEnum[]
}

/**
 * SignUpSession findMany
 */
export type SignUpSessionFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SignUpSession
   */
  select?: Prisma.SignUpSessionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SignUpSession
   */
  omit?: Prisma.SignUpSessionOmit<ExtArgs> | null
  /**
   * Filter, which SignUpSessions to fetch.
   */
  where?: Prisma.SignUpSessionWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of SignUpSessions to fetch.
   */
  orderBy?: Prisma.SignUpSessionOrderByWithRelationInput | Prisma.SignUpSessionOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing SignUpSessions.
   */
  cursor?: Prisma.SignUpSessionWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` SignUpSessions from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` SignUpSessions.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of SignUpSessions.
   */
  distinct?: Prisma.SignUpSessionScalarFieldEnum | Prisma.SignUpSessionScalarFieldEnum[]
}

/**
 * SignUpSession create
 */
export type SignUpSessionCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SignUpSession
   */
  select?: Prisma.SignUpSessionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SignUpSession
   */
  omit?: Prisma.SignUpSessionOmit<ExtArgs> | null
  /**
   * The data needed to create a SignUpSession.
   */
  data: Prisma.XOR<Prisma.SignUpSessionCreateInput, Prisma.SignUpSessionUncheckedCreateInput>
}

/**
 * SignUpSession createMany
 */
export type SignUpSessionCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many SignUpSessions.
   */
  data: Prisma.SignUpSessionCreateManyInput | Prisma.SignUpSessionCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * SignUpSession createManyAndReturn
 */
export type SignUpSessionCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SignUpSession
   */
  select?: Prisma.SignUpSessionSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the SignUpSession
   */
  omit?: Prisma.SignUpSessionOmit<ExtArgs> | null
  /**
   * The data used to create many SignUpSessions.
   */
  data: Prisma.SignUpSessionCreateManyInput | Prisma.SignUpSessionCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * SignUpSession update
 */
export type SignUpSessionUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SignUpSession
   */
  select?: Prisma.SignUpSessionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SignUpSession
   */
  omit?: Prisma.SignUpSessionOmit<ExtArgs> | null
  /**
   * The data needed to update a SignUpSession.
   */
  data: Prisma.XOR<Prisma.SignUpSessionUpdateInput, Prisma.SignUpSessionUncheckedUpdateInput>
  /**
   * Choose, which SignUpSession to update.
   */
  where: Prisma.SignUpSessionWhereUniqueInput
}

/**
 * SignUpSession updateMany
 */
export type SignUpSessionUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update SignUpSessions.
   */
  data: Prisma.XOR<Prisma.SignUpSessionUpdateManyMutationInput, Prisma.SignUpSessionUncheckedUpdateManyInput>
  /**
   * Filter which SignUpSessions to update
   */
  where?: Prisma.SignUpSessionWhereInput
  /**
   * Limit how many SignUpSessions to update.
   */
  limit?: number
}

/**
 * SignUpSession updateManyAndReturn
 */
export type SignUpSessionUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SignUpSession
   */
  select?: Prisma.SignUpSessionSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the SignUpSession
   */
  omit?: Prisma.SignUpSessionOmit<ExtArgs> | null
  /**
   * The data used to update SignUpSessions.
   */
  data: Prisma.XOR<Prisma.SignUpSessionUpdateManyMutationInput, Prisma.SignUpSessionUncheckedUpdateManyInput>
  /**
   * Filter which SignUpSessions to update
   */
  where?: Prisma.SignUpSessionWhereInput
  /**
   * Limit how many SignUpSessions to update.
   */
  limit?: number
}

/**
 * SignUpSession upsert
 */
export type SignUpSessionUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SignUpSession
   */
  select?: Prisma.SignUpSessionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SignUpSession
   */
  omit?: Prisma.SignUpSessionOmit<ExtArgs> | null
  /**
   * The filter to search for the SignUpSession to update in case it exists.
   */
  where: Prisma.SignUpSessionWhereUniqueInput
  /**
   * In case the SignUpSession found by the `where` argument doesn't exist, create a new SignUpSession with this data.
   */
  create: Prisma.XOR<Prisma.SignUpSessionCreateInput, Prisma.SignUpSessionUncheckedCreateInput>
  /**
   * In case the SignUpSession was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.SignUpSessionUpdateInput, Prisma.SignUpSessionUncheckedUpdateInput>
}

/**
 * SignUpSession delete
 */
export type SignUpSessionDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SignUpSession
   */
  select?: Prisma.SignUpSessionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SignUpSession
   */
  omit?: Prisma.SignUpSessionOmit<ExtArgs> | null
  /**
   * Filter which SignUpSession to delete.
   */
  where: Prisma.SignUpSessionWhereUniqueInput
}

/**
 * SignUpSession deleteMany
 */
export type SignUpSessionDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which SignUpSessions to delete
   */
  where?: Prisma.SignUpSessionWhereInput
  /**
   * Limit how many SignUpSessions to delete.
   */
  limit?: number
}

/**
 * SignUpSession without action
 */
export type SignUpSessionDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SignUpSession
   */
  select?: Prisma.SignUpSessionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SignUpSession
   */
  omit?: Prisma.SignUpSessionOmit<ExtArgs> | null
}
