
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `TransactionAuthor` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model TransactionAuthor
 * 
 */
export type TransactionAuthorModel = runtime.Types.Result.DefaultSelection<Prisma.$TransactionAuthorPayload>

export type AggregateTransactionAuthor = {
  _count: TransactionAuthorCountAggregateOutputType | null
  _min: TransactionAuthorMinAggregateOutputType | null
  _max: TransactionAuthorMaxAggregateOutputType | null
}

export type TransactionAuthorMinAggregateOutputType = {
  id: string | null
  memberId: string | null
}

export type TransactionAuthorMaxAggregateOutputType = {
  id: string | null
  memberId: string | null
}

export type TransactionAuthorCountAggregateOutputType = {
  id: number
  memberId: number
  _all: number
}


export type TransactionAuthorMinAggregateInputType = {
  id?: true
  memberId?: true
}

export type TransactionAuthorMaxAggregateInputType = {
  id?: true
  memberId?: true
}

export type TransactionAuthorCountAggregateInputType = {
  id?: true
  memberId?: true
  _all?: true
}

export type TransactionAuthorAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which TransactionAuthor to aggregate.
   */
  where?: Prisma.TransactionAuthorWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of TransactionAuthors to fetch.
   */
  orderBy?: Prisma.TransactionAuthorOrderByWithRelationInput | Prisma.TransactionAuthorOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.TransactionAuthorWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` TransactionAuthors from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` TransactionAuthors.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned TransactionAuthors
  **/
  _count?: true | TransactionAuthorCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: TransactionAuthorMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: TransactionAuthorMaxAggregateInputType
}

export type GetTransactionAuthorAggregateType<T extends TransactionAuthorAggregateArgs> = {
      [P in keyof T & keyof AggregateTransactionAuthor]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateTransactionAuthor[P]>
    : Prisma.GetScalarType<T[P], AggregateTransactionAuthor[P]>
}




export type TransactionAuthorGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.TransactionAuthorWhereInput
  orderBy?: Prisma.TransactionAuthorOrderByWithAggregationInput | Prisma.TransactionAuthorOrderByWithAggregationInput[]
  by: Prisma.TransactionAuthorScalarFieldEnum[] | Prisma.TransactionAuthorScalarFieldEnum
  having?: Prisma.TransactionAuthorScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: TransactionAuthorCountAggregateInputType | true
  _min?: TransactionAuthorMinAggregateInputType
  _max?: TransactionAuthorMaxAggregateInputType
}

export type TransactionAuthorGroupByOutputType = {
  id: string
  memberId: string
  _count: TransactionAuthorCountAggregateOutputType | null
  _min: TransactionAuthorMinAggregateOutputType | null
  _max: TransactionAuthorMaxAggregateOutputType | null
}

export type GetTransactionAuthorGroupByPayload<T extends TransactionAuthorGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<TransactionAuthorGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof TransactionAuthorGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], TransactionAuthorGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], TransactionAuthorGroupByOutputType[P]>
      }
    >
  >



export type TransactionAuthorWhereInput = {
  AND?: Prisma.TransactionAuthorWhereInput | Prisma.TransactionAuthorWhereInput[]
  OR?: Prisma.TransactionAuthorWhereInput[]
  NOT?: Prisma.TransactionAuthorWhereInput | Prisma.TransactionAuthorWhereInput[]
  id?: Prisma.StringFilter<"TransactionAuthor"> | string
  memberId?: Prisma.StringFilter<"TransactionAuthor"> | string
  member?: Prisma.XOR<Prisma.HouseholdMemberScalarRelationFilter, Prisma.HouseholdMemberWhereInput>
  transactions?: Prisma.TransactionListRelationFilter
}

export type TransactionAuthorOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  memberId?: Prisma.SortOrder
  member?: Prisma.HouseholdMemberOrderByWithRelationInput
  transactions?: Prisma.TransactionOrderByRelationAggregateInput
}

export type TransactionAuthorWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.TransactionAuthorWhereInput | Prisma.TransactionAuthorWhereInput[]
  OR?: Prisma.TransactionAuthorWhereInput[]
  NOT?: Prisma.TransactionAuthorWhereInput | Prisma.TransactionAuthorWhereInput[]
  memberId?: Prisma.StringFilter<"TransactionAuthor"> | string
  member?: Prisma.XOR<Prisma.HouseholdMemberScalarRelationFilter, Prisma.HouseholdMemberWhereInput>
  transactions?: Prisma.TransactionListRelationFilter
}, "id">

export type TransactionAuthorOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  memberId?: Prisma.SortOrder
  _count?: Prisma.TransactionAuthorCountOrderByAggregateInput
  _max?: Prisma.TransactionAuthorMaxOrderByAggregateInput
  _min?: Prisma.TransactionAuthorMinOrderByAggregateInput
}

export type TransactionAuthorScalarWhereWithAggregatesInput = {
  AND?: Prisma.TransactionAuthorScalarWhereWithAggregatesInput | Prisma.TransactionAuthorScalarWhereWithAggregatesInput[]
  OR?: Prisma.TransactionAuthorScalarWhereWithAggregatesInput[]
  NOT?: Prisma.TransactionAuthorScalarWhereWithAggregatesInput | Prisma.TransactionAuthorScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"TransactionAuthor"> | string
  memberId?: Prisma.StringWithAggregatesFilter<"TransactionAuthor"> | string
}

export type TransactionAuthorCreateInput = {
  id?: string
  member: Prisma.HouseholdMemberCreateNestedOneWithoutTransactionsInput
  transactions?: Prisma.TransactionCreateNestedManyWithoutAuthorInput
}

export type TransactionAuthorUncheckedCreateInput = {
  id?: string
  memberId: string
  transactions?: Prisma.TransactionUncheckedCreateNestedManyWithoutAuthorInput
}

export type TransactionAuthorUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  member?: Prisma.HouseholdMemberUpdateOneRequiredWithoutTransactionsNestedInput
  transactions?: Prisma.TransactionUpdateManyWithoutAuthorNestedInput
}

export type TransactionAuthorUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  memberId?: Prisma.StringFieldUpdateOperationsInput | string
  transactions?: Prisma.TransactionUncheckedUpdateManyWithoutAuthorNestedInput
}

export type TransactionAuthorCreateManyInput = {
  id?: string
  memberId: string
}

export type TransactionAuthorUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
}

export type TransactionAuthorUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  memberId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type TransactionAuthorListRelationFilter = {
  every?: Prisma.TransactionAuthorWhereInput
  some?: Prisma.TransactionAuthorWhereInput
  none?: Prisma.TransactionAuthorWhereInput
}

export type TransactionAuthorOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type TransactionAuthorNullableScalarRelationFilter = {
  is?: Prisma.TransactionAuthorWhereInput | null
  isNot?: Prisma.TransactionAuthorWhereInput | null
}

export type TransactionAuthorCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  memberId?: Prisma.SortOrder
}

export type TransactionAuthorMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  memberId?: Prisma.SortOrder
}

export type TransactionAuthorMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  memberId?: Prisma.SortOrder
}

export type TransactionAuthorCreateNestedManyWithoutMemberInput = {
  create?: Prisma.XOR<Prisma.TransactionAuthorCreateWithoutMemberInput, Prisma.TransactionAuthorUncheckedCreateWithoutMemberInput> | Prisma.TransactionAuthorCreateWithoutMemberInput[] | Prisma.TransactionAuthorUncheckedCreateWithoutMemberInput[]
  connectOrCreate?: Prisma.TransactionAuthorCreateOrConnectWithoutMemberInput | Prisma.TransactionAuthorCreateOrConnectWithoutMemberInput[]
  createMany?: Prisma.TransactionAuthorCreateManyMemberInputEnvelope
  connect?: Prisma.TransactionAuthorWhereUniqueInput | Prisma.TransactionAuthorWhereUniqueInput[]
}

export type TransactionAuthorUncheckedCreateNestedManyWithoutMemberInput = {
  create?: Prisma.XOR<Prisma.TransactionAuthorCreateWithoutMemberInput, Prisma.TransactionAuthorUncheckedCreateWithoutMemberInput> | Prisma.TransactionAuthorCreateWithoutMemberInput[] | Prisma.TransactionAuthorUncheckedCreateWithoutMemberInput[]
  connectOrCreate?: Prisma.TransactionAuthorCreateOrConnectWithoutMemberInput | Prisma.TransactionAuthorCreateOrConnectWithoutMemberInput[]
  createMany?: Prisma.TransactionAuthorCreateManyMemberInputEnvelope
  connect?: Prisma.TransactionAuthorWhereUniqueInput | Prisma.TransactionAuthorWhereUniqueInput[]
}

export type TransactionAuthorUpdateManyWithoutMemberNestedInput = {
  create?: Prisma.XOR<Prisma.TransactionAuthorCreateWithoutMemberInput, Prisma.TransactionAuthorUncheckedCreateWithoutMemberInput> | Prisma.TransactionAuthorCreateWithoutMemberInput[] | Prisma.TransactionAuthorUncheckedCreateWithoutMemberInput[]
  connectOrCreate?: Prisma.TransactionAuthorCreateOrConnectWithoutMemberInput | Prisma.TransactionAuthorCreateOrConnectWithoutMemberInput[]
  upsert?: Prisma.TransactionAuthorUpsertWithWhereUniqueWithoutMemberInput | Prisma.TransactionAuthorUpsertWithWhereUniqueWithoutMemberInput[]
  createMany?: Prisma.TransactionAuthorCreateManyMemberInputEnvelope
  set?: Prisma.TransactionAuthorWhereUniqueInput | Prisma.TransactionAuthorWhereUniqueInput[]
  disconnect?: Prisma.TransactionAuthorWhereUniqueInput | Prisma.TransactionAuthorWhereUniqueInput[]
  delete?: Prisma.TransactionAuthorWhereUniqueInput | Prisma.TransactionAuthorWhereUniqueInput[]
  connect?: Prisma.TransactionAuthorWhereUniqueInput | Prisma.TransactionAuthorWhereUniqueInput[]
  update?: Prisma.TransactionAuthorUpdateWithWhereUniqueWithoutMemberInput | Prisma.TransactionAuthorUpdateWithWhereUniqueWithoutMemberInput[]
  updateMany?: Prisma.TransactionAuthorUpdateManyWithWhereWithoutMemberInput | Prisma.TransactionAuthorUpdateManyWithWhereWithoutMemberInput[]
  deleteMany?: Prisma.TransactionAuthorScalarWhereInput | Prisma.TransactionAuthorScalarWhereInput[]
}

export type TransactionAuthorUncheckedUpdateManyWithoutMemberNestedInput = {
  create?: Prisma.XOR<Prisma.TransactionAuthorCreateWithoutMemberInput, Prisma.TransactionAuthorUncheckedCreateWithoutMemberInput> | Prisma.TransactionAuthorCreateWithoutMemberInput[] | Prisma.TransactionAuthorUncheckedCreateWithoutMemberInput[]
  connectOrCreate?: Prisma.TransactionAuthorCreateOrConnectWithoutMemberInput | Prisma.TransactionAuthorCreateOrConnectWithoutMemberInput[]
  upsert?: Prisma.TransactionAuthorUpsertWithWhereUniqueWithoutMemberInput | Prisma.TransactionAuthorUpsertWithWhereUniqueWithoutMemberInput[]
  createMany?: Prisma.TransactionAuthorCreateManyMemberInputEnvelope
  set?: Prisma.TransactionAuthorWhereUniqueInput | Prisma.TransactionAuthorWhereUniqueInput[]
  disconnect?: Prisma.TransactionAuthorWhereUniqueInput | Prisma.TransactionAuthorWhereUniqueInput[]
  delete?: Prisma.TransactionAuthorWhereUniqueInput | Prisma.TransactionAuthorWhereUniqueInput[]
  connect?: Prisma.TransactionAuthorWhereUniqueInput | Prisma.TransactionAuthorWhereUniqueInput[]
  update?: Prisma.TransactionAuthorUpdateWithWhereUniqueWithoutMemberInput | Prisma.TransactionAuthorUpdateWithWhereUniqueWithoutMemberInput[]
  updateMany?: Prisma.TransactionAuthorUpdateManyWithWhereWithoutMemberInput | Prisma.TransactionAuthorUpdateManyWithWhereWithoutMemberInput[]
  deleteMany?: Prisma.TransactionAuthorScalarWhereInput | Prisma.TransactionAuthorScalarWhereInput[]
}

export type TransactionAuthorCreateNestedOneWithoutTransactionsInput = {
  create?: Prisma.XOR<Prisma.TransactionAuthorCreateWithoutTransactionsInput, Prisma.TransactionAuthorUncheckedCreateWithoutTransactionsInput>
  connectOrCreate?: Prisma.TransactionAuthorCreateOrConnectWithoutTransactionsInput
  connect?: Prisma.TransactionAuthorWhereUniqueInput
}

export type TransactionAuthorUpdateOneWithoutTransactionsNestedInput = {
  create?: Prisma.XOR<Prisma.TransactionAuthorCreateWithoutTransactionsInput, Prisma.TransactionAuthorUncheckedCreateWithoutTransactionsInput>
  connectOrCreate?: Prisma.TransactionAuthorCreateOrConnectWithoutTransactionsInput
  upsert?: Prisma.TransactionAuthorUpsertWithoutTransactionsInput
  disconnect?: Prisma.TransactionAuthorWhereInput | boolean
  delete?: Prisma.TransactionAuthorWhereInput | boolean
  connect?: Prisma.TransactionAuthorWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.TransactionAuthorUpdateToOneWithWhereWithoutTransactionsInput, Prisma.TransactionAuthorUpdateWithoutTransactionsInput>, Prisma.TransactionAuthorUncheckedUpdateWithoutTransactionsInput>
}

export type TransactionAuthorCreateWithoutMemberInput = {
  id?: string
  transactions?: Prisma.TransactionCreateNestedManyWithoutAuthorInput
}

export type TransactionAuthorUncheckedCreateWithoutMemberInput = {
  id?: string
  transactions?: Prisma.TransactionUncheckedCreateNestedManyWithoutAuthorInput
}

export type TransactionAuthorCreateOrConnectWithoutMemberInput = {
  where: Prisma.TransactionAuthorWhereUniqueInput
  create: Prisma.XOR<Prisma.TransactionAuthorCreateWithoutMemberInput, Prisma.TransactionAuthorUncheckedCreateWithoutMemberInput>
}

export type TransactionAuthorCreateManyMemberInputEnvelope = {
  data: Prisma.TransactionAuthorCreateManyMemberInput | Prisma.TransactionAuthorCreateManyMemberInput[]
  skipDuplicates?: boolean
}

export type TransactionAuthorUpsertWithWhereUniqueWithoutMemberInput = {
  where: Prisma.TransactionAuthorWhereUniqueInput
  update: Prisma.XOR<Prisma.TransactionAuthorUpdateWithoutMemberInput, Prisma.TransactionAuthorUncheckedUpdateWithoutMemberInput>
  create: Prisma.XOR<Prisma.TransactionAuthorCreateWithoutMemberInput, Prisma.TransactionAuthorUncheckedCreateWithoutMemberInput>
}

export type TransactionAuthorUpdateWithWhereUniqueWithoutMemberInput = {
  where: Prisma.TransactionAuthorWhereUniqueInput
  data: Prisma.XOR<Prisma.TransactionAuthorUpdateWithoutMemberInput, Prisma.TransactionAuthorUncheckedUpdateWithoutMemberInput>
}

export type TransactionAuthorUpdateManyWithWhereWithoutMemberInput = {
  where: Prisma.TransactionAuthorScalarWhereInput
  data: Prisma.XOR<Prisma.TransactionAuthorUpdateManyMutationInput, Prisma.TransactionAuthorUncheckedUpdateManyWithoutMemberInput>
}

export type TransactionAuthorScalarWhereInput = {
  AND?: Prisma.TransactionAuthorScalarWhereInput | Prisma.TransactionAuthorScalarWhereInput[]
  OR?: Prisma.TransactionAuthorScalarWhereInput[]
  NOT?: Prisma.TransactionAuthorScalarWhereInput | Prisma.TransactionAuthorScalarWhereInput[]
  id?: Prisma.StringFilter<"TransactionAuthor"> | string
  memberId?: Prisma.StringFilter<"TransactionAuthor"> | string
}

export type TransactionAuthorCreateWithoutTransactionsInput = {
  id?: string
  member: Prisma.HouseholdMemberCreateNestedOneWithoutTransactionsInput
}

export type TransactionAuthorUncheckedCreateWithoutTransactionsInput = {
  id?: string
  memberId: string
}

export type TransactionAuthorCreateOrConnectWithoutTransactionsInput = {
  where: Prisma.TransactionAuthorWhereUniqueInput
  create: Prisma.XOR<Prisma.TransactionAuthorCreateWithoutTransactionsInput, Prisma.TransactionAuthorUncheckedCreateWithoutTransactionsInput>
}

export type TransactionAuthorUpsertWithoutTransactionsInput = {
  update: Prisma.XOR<Prisma.TransactionAuthorUpdateWithoutTransactionsInput, Prisma.TransactionAuthorUncheckedUpdateWithoutTransactionsInput>
  create: Prisma.XOR<Prisma.TransactionAuthorCreateWithoutTransactionsInput, Prisma.TransactionAuthorUncheckedCreateWithoutTransactionsInput>
  where?: Prisma.TransactionAuthorWhereInput
}

export type TransactionAuthorUpdateToOneWithWhereWithoutTransactionsInput = {
  where?: Prisma.TransactionAuthorWhereInput
  data: Prisma.XOR<Prisma.TransactionAuthorUpdateWithoutTransactionsInput, Prisma.TransactionAuthorUncheckedUpdateWithoutTransactionsInput>
}

export type TransactionAuthorUpdateWithoutTransactionsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  member?: Prisma.HouseholdMemberUpdateOneRequiredWithoutTransactionsNestedInput
}

export type TransactionAuthorUncheckedUpdateWithoutTransactionsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  memberId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type TransactionAuthorCreateManyMemberInput = {
  id?: string
}

export type TransactionAuthorUpdateWithoutMemberInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  transactions?: Prisma.TransactionUpdateManyWithoutAuthorNestedInput
}

export type TransactionAuthorUncheckedUpdateWithoutMemberInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  transactions?: Prisma.TransactionUncheckedUpdateManyWithoutAuthorNestedInput
}

export type TransactionAuthorUncheckedUpdateManyWithoutMemberInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
}


/**
 * Count Type TransactionAuthorCountOutputType
 */

export type TransactionAuthorCountOutputType = {
  transactions: number
}

export type TransactionAuthorCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  transactions?: boolean | TransactionAuthorCountOutputTypeCountTransactionsArgs
}

/**
 * TransactionAuthorCountOutputType without action
 */
export type TransactionAuthorCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TransactionAuthorCountOutputType
   */
  select?: Prisma.TransactionAuthorCountOutputTypeSelect<ExtArgs> | null
}

/**
 * TransactionAuthorCountOutputType without action
 */
export type TransactionAuthorCountOutputTypeCountTransactionsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.TransactionWhereInput
}


export type TransactionAuthorSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  memberId?: boolean
  member?: boolean | Prisma.HouseholdMemberDefaultArgs<ExtArgs>
  transactions?: boolean | Prisma.TransactionAuthor$transactionsArgs<ExtArgs>
  _count?: boolean | Prisma.TransactionAuthorCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["transactionAuthor"]>

export type TransactionAuthorSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  memberId?: boolean
  member?: boolean | Prisma.HouseholdMemberDefaultArgs<ExtArgs>
}, ExtArgs["result"]["transactionAuthor"]>

export type TransactionAuthorSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  memberId?: boolean
  member?: boolean | Prisma.HouseholdMemberDefaultArgs<ExtArgs>
}, ExtArgs["result"]["transactionAuthor"]>

export type TransactionAuthorSelectScalar = {
  id?: boolean
  memberId?: boolean
}

export type TransactionAuthorOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "memberId", ExtArgs["result"]["transactionAuthor"]>
export type TransactionAuthorInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  member?: boolean | Prisma.HouseholdMemberDefaultArgs<ExtArgs>
  transactions?: boolean | Prisma.TransactionAuthor$transactionsArgs<ExtArgs>
  _count?: boolean | Prisma.TransactionAuthorCountOutputTypeDefaultArgs<ExtArgs>
}
export type TransactionAuthorIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  member?: boolean | Prisma.HouseholdMemberDefaultArgs<ExtArgs>
}
export type TransactionAuthorIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  member?: boolean | Prisma.HouseholdMemberDefaultArgs<ExtArgs>
}

export type $TransactionAuthorPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "TransactionAuthor"
  objects: {
    member: Prisma.$HouseholdMemberPayload<ExtArgs>
    transactions: Prisma.$TransactionPayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    memberId: string
  }, ExtArgs["result"]["transactionAuthor"]>
  composites: {}
}

export type TransactionAuthorGetPayload<S extends boolean | null | undefined | TransactionAuthorDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$TransactionAuthorPayload, S>

export type TransactionAuthorCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<TransactionAuthorFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: TransactionAuthorCountAggregateInputType | true
  }

export interface TransactionAuthorDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['TransactionAuthor'], meta: { name: 'TransactionAuthor' } }
  /**
   * Find zero or one TransactionAuthor that matches the filter.
   * @param {TransactionAuthorFindUniqueArgs} args - Arguments to find a TransactionAuthor
   * @example
   * // Get one TransactionAuthor
   * const transactionAuthor = await prisma.transactionAuthor.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends TransactionAuthorFindUniqueArgs>(args: Prisma.SelectSubset<T, TransactionAuthorFindUniqueArgs<ExtArgs>>): Prisma.Prisma__TransactionAuthorClient<runtime.Types.Result.GetResult<Prisma.$TransactionAuthorPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one TransactionAuthor that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {TransactionAuthorFindUniqueOrThrowArgs} args - Arguments to find a TransactionAuthor
   * @example
   * // Get one TransactionAuthor
   * const transactionAuthor = await prisma.transactionAuthor.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends TransactionAuthorFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, TransactionAuthorFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__TransactionAuthorClient<runtime.Types.Result.GetResult<Prisma.$TransactionAuthorPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first TransactionAuthor that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TransactionAuthorFindFirstArgs} args - Arguments to find a TransactionAuthor
   * @example
   * // Get one TransactionAuthor
   * const transactionAuthor = await prisma.transactionAuthor.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends TransactionAuthorFindFirstArgs>(args?: Prisma.SelectSubset<T, TransactionAuthorFindFirstArgs<ExtArgs>>): Prisma.Prisma__TransactionAuthorClient<runtime.Types.Result.GetResult<Prisma.$TransactionAuthorPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first TransactionAuthor that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TransactionAuthorFindFirstOrThrowArgs} args - Arguments to find a TransactionAuthor
   * @example
   * // Get one TransactionAuthor
   * const transactionAuthor = await prisma.transactionAuthor.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends TransactionAuthorFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, TransactionAuthorFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__TransactionAuthorClient<runtime.Types.Result.GetResult<Prisma.$TransactionAuthorPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more TransactionAuthors that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TransactionAuthorFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all TransactionAuthors
   * const transactionAuthors = await prisma.transactionAuthor.findMany()
   * 
   * // Get first 10 TransactionAuthors
   * const transactionAuthors = await prisma.transactionAuthor.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const transactionAuthorWithIdOnly = await prisma.transactionAuthor.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends TransactionAuthorFindManyArgs>(args?: Prisma.SelectSubset<T, TransactionAuthorFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$TransactionAuthorPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a TransactionAuthor.
   * @param {TransactionAuthorCreateArgs} args - Arguments to create a TransactionAuthor.
   * @example
   * // Create one TransactionAuthor
   * const TransactionAuthor = await prisma.transactionAuthor.create({
   *   data: {
   *     // ... data to create a TransactionAuthor
   *   }
   * })
   * 
   */
  create<T extends TransactionAuthorCreateArgs>(args: Prisma.SelectSubset<T, TransactionAuthorCreateArgs<ExtArgs>>): Prisma.Prisma__TransactionAuthorClient<runtime.Types.Result.GetResult<Prisma.$TransactionAuthorPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many TransactionAuthors.
   * @param {TransactionAuthorCreateManyArgs} args - Arguments to create many TransactionAuthors.
   * @example
   * // Create many TransactionAuthors
   * const transactionAuthor = await prisma.transactionAuthor.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends TransactionAuthorCreateManyArgs>(args?: Prisma.SelectSubset<T, TransactionAuthorCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many TransactionAuthors and returns the data saved in the database.
   * @param {TransactionAuthorCreateManyAndReturnArgs} args - Arguments to create many TransactionAuthors.
   * @example
   * // Create many TransactionAuthors
   * const transactionAuthor = await prisma.transactionAuthor.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many TransactionAuthors and only return the `id`
   * const transactionAuthorWithIdOnly = await prisma.transactionAuthor.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends TransactionAuthorCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, TransactionAuthorCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$TransactionAuthorPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a TransactionAuthor.
   * @param {TransactionAuthorDeleteArgs} args - Arguments to delete one TransactionAuthor.
   * @example
   * // Delete one TransactionAuthor
   * const TransactionAuthor = await prisma.transactionAuthor.delete({
   *   where: {
   *     // ... filter to delete one TransactionAuthor
   *   }
   * })
   * 
   */
  delete<T extends TransactionAuthorDeleteArgs>(args: Prisma.SelectSubset<T, TransactionAuthorDeleteArgs<ExtArgs>>): Prisma.Prisma__TransactionAuthorClient<runtime.Types.Result.GetResult<Prisma.$TransactionAuthorPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one TransactionAuthor.
   * @param {TransactionAuthorUpdateArgs} args - Arguments to update one TransactionAuthor.
   * @example
   * // Update one TransactionAuthor
   * const transactionAuthor = await prisma.transactionAuthor.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends TransactionAuthorUpdateArgs>(args: Prisma.SelectSubset<T, TransactionAuthorUpdateArgs<ExtArgs>>): Prisma.Prisma__TransactionAuthorClient<runtime.Types.Result.GetResult<Prisma.$TransactionAuthorPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more TransactionAuthors.
   * @param {TransactionAuthorDeleteManyArgs} args - Arguments to filter TransactionAuthors to delete.
   * @example
   * // Delete a few TransactionAuthors
   * const { count } = await prisma.transactionAuthor.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends TransactionAuthorDeleteManyArgs>(args?: Prisma.SelectSubset<T, TransactionAuthorDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more TransactionAuthors.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TransactionAuthorUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many TransactionAuthors
   * const transactionAuthor = await prisma.transactionAuthor.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends TransactionAuthorUpdateManyArgs>(args: Prisma.SelectSubset<T, TransactionAuthorUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more TransactionAuthors and returns the data updated in the database.
   * @param {TransactionAuthorUpdateManyAndReturnArgs} args - Arguments to update many TransactionAuthors.
   * @example
   * // Update many TransactionAuthors
   * const transactionAuthor = await prisma.transactionAuthor.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more TransactionAuthors and only return the `id`
   * const transactionAuthorWithIdOnly = await prisma.transactionAuthor.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends TransactionAuthorUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, TransactionAuthorUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$TransactionAuthorPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one TransactionAuthor.
   * @param {TransactionAuthorUpsertArgs} args - Arguments to update or create a TransactionAuthor.
   * @example
   * // Update or create a TransactionAuthor
   * const transactionAuthor = await prisma.transactionAuthor.upsert({
   *   create: {
   *     // ... data to create a TransactionAuthor
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the TransactionAuthor we want to update
   *   }
   * })
   */
  upsert<T extends TransactionAuthorUpsertArgs>(args: Prisma.SelectSubset<T, TransactionAuthorUpsertArgs<ExtArgs>>): Prisma.Prisma__TransactionAuthorClient<runtime.Types.Result.GetResult<Prisma.$TransactionAuthorPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of TransactionAuthors.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TransactionAuthorCountArgs} args - Arguments to filter TransactionAuthors to count.
   * @example
   * // Count the number of TransactionAuthors
   * const count = await prisma.transactionAuthor.count({
   *   where: {
   *     // ... the filter for the TransactionAuthors we want to count
   *   }
   * })
  **/
  count<T extends TransactionAuthorCountArgs>(
    args?: Prisma.Subset<T, TransactionAuthorCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], TransactionAuthorCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a TransactionAuthor.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TransactionAuthorAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends TransactionAuthorAggregateArgs>(args: Prisma.Subset<T, TransactionAuthorAggregateArgs>): Prisma.PrismaPromise<GetTransactionAuthorAggregateType<T>>

  /**
   * Group by TransactionAuthor.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TransactionAuthorGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends TransactionAuthorGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: TransactionAuthorGroupByArgs['orderBy'] }
      : { orderBy?: TransactionAuthorGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, TransactionAuthorGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetTransactionAuthorGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the TransactionAuthor model
 */
readonly fields: TransactionAuthorFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for TransactionAuthor.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__TransactionAuthorClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  member<T extends Prisma.HouseholdMemberDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.HouseholdMemberDefaultArgs<ExtArgs>>): Prisma.Prisma__HouseholdMemberClient<runtime.Types.Result.GetResult<Prisma.$HouseholdMemberPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  transactions<T extends Prisma.TransactionAuthor$transactionsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.TransactionAuthor$transactionsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$TransactionPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the TransactionAuthor model
 */
export interface TransactionAuthorFieldRefs {
  readonly id: Prisma.FieldRef<"TransactionAuthor", 'String'>
  readonly memberId: Prisma.FieldRef<"TransactionAuthor", 'String'>
}
    

// Custom InputTypes
/**
 * TransactionAuthor findUnique
 */
export type TransactionAuthorFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TransactionAuthor
   */
  select?: Prisma.TransactionAuthorSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TransactionAuthor
   */
  omit?: Prisma.TransactionAuthorOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TransactionAuthorInclude<ExtArgs> | null
  /**
   * Filter, which TransactionAuthor to fetch.
   */
  where: Prisma.TransactionAuthorWhereUniqueInput
}

/**
 * TransactionAuthor findUniqueOrThrow
 */
export type TransactionAuthorFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TransactionAuthor
   */
  select?: Prisma.TransactionAuthorSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TransactionAuthor
   */
  omit?: Prisma.TransactionAuthorOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TransactionAuthorInclude<ExtArgs> | null
  /**
   * Filter, which TransactionAuthor to fetch.
   */
  where: Prisma.TransactionAuthorWhereUniqueInput
}

/**
 * TransactionAuthor findFirst
 */
export type TransactionAuthorFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TransactionAuthor
   */
  select?: Prisma.TransactionAuthorSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TransactionAuthor
   */
  omit?: Prisma.TransactionAuthorOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TransactionAuthorInclude<ExtArgs> | null
  /**
   * Filter, which TransactionAuthor to fetch.
   */
  where?: Prisma.TransactionAuthorWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of TransactionAuthors to fetch.
   */
  orderBy?: Prisma.TransactionAuthorOrderByWithRelationInput | Prisma.TransactionAuthorOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for TransactionAuthors.
   */
  cursor?: Prisma.TransactionAuthorWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` TransactionAuthors from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` TransactionAuthors.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of TransactionAuthors.
   */
  distinct?: Prisma.TransactionAuthorScalarFieldEnum | Prisma.TransactionAuthorScalarFieldEnum[]
}

/**
 * TransactionAuthor findFirstOrThrow
 */
export type TransactionAuthorFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TransactionAuthor
   */
  select?: Prisma.TransactionAuthorSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TransactionAuthor
   */
  omit?: Prisma.TransactionAuthorOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TransactionAuthorInclude<ExtArgs> | null
  /**
   * Filter, which TransactionAuthor to fetch.
   */
  where?: Prisma.TransactionAuthorWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of TransactionAuthors to fetch.
   */
  orderBy?: Prisma.TransactionAuthorOrderByWithRelationInput | Prisma.TransactionAuthorOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for TransactionAuthors.
   */
  cursor?: Prisma.TransactionAuthorWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` TransactionAuthors from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` TransactionAuthors.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of TransactionAuthors.
   */
  distinct?: Prisma.TransactionAuthorScalarFieldEnum | Prisma.TransactionAuthorScalarFieldEnum[]
}

/**
 * TransactionAuthor findMany
 */
export type TransactionAuthorFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TransactionAuthor
   */
  select?: Prisma.TransactionAuthorSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TransactionAuthor
   */
  omit?: Prisma.TransactionAuthorOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TransactionAuthorInclude<ExtArgs> | null
  /**
   * Filter, which TransactionAuthors to fetch.
   */
  where?: Prisma.TransactionAuthorWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of TransactionAuthors to fetch.
   */
  orderBy?: Prisma.TransactionAuthorOrderByWithRelationInput | Prisma.TransactionAuthorOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing TransactionAuthors.
   */
  cursor?: Prisma.TransactionAuthorWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` TransactionAuthors from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` TransactionAuthors.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of TransactionAuthors.
   */
  distinct?: Prisma.TransactionAuthorScalarFieldEnum | Prisma.TransactionAuthorScalarFieldEnum[]
}

/**
 * TransactionAuthor create
 */
export type TransactionAuthorCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TransactionAuthor
   */
  select?: Prisma.TransactionAuthorSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TransactionAuthor
   */
  omit?: Prisma.TransactionAuthorOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TransactionAuthorInclude<ExtArgs> | null
  /**
   * The data needed to create a TransactionAuthor.
   */
  data: Prisma.XOR<Prisma.TransactionAuthorCreateInput, Prisma.TransactionAuthorUncheckedCreateInput>
}

/**
 * TransactionAuthor createMany
 */
export type TransactionAuthorCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many TransactionAuthors.
   */
  data: Prisma.TransactionAuthorCreateManyInput | Prisma.TransactionAuthorCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * TransactionAuthor createManyAndReturn
 */
export type TransactionAuthorCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TransactionAuthor
   */
  select?: Prisma.TransactionAuthorSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the TransactionAuthor
   */
  omit?: Prisma.TransactionAuthorOmit<ExtArgs> | null
  /**
   * The data used to create many TransactionAuthors.
   */
  data: Prisma.TransactionAuthorCreateManyInput | Prisma.TransactionAuthorCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TransactionAuthorIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * TransactionAuthor update
 */
export type TransactionAuthorUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TransactionAuthor
   */
  select?: Prisma.TransactionAuthorSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TransactionAuthor
   */
  omit?: Prisma.TransactionAuthorOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TransactionAuthorInclude<ExtArgs> | null
  /**
   * The data needed to update a TransactionAuthor.
   */
  data: Prisma.XOR<Prisma.TransactionAuthorUpdateInput, Prisma.TransactionAuthorUncheckedUpdateInput>
  /**
   * Choose, which TransactionAuthor to update.
   */
  where: Prisma.TransactionAuthorWhereUniqueInput
}

/**
 * TransactionAuthor updateMany
 */
export type TransactionAuthorUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update TransactionAuthors.
   */
  data: Prisma.XOR<Prisma.TransactionAuthorUpdateManyMutationInput, Prisma.TransactionAuthorUncheckedUpdateManyInput>
  /**
   * Filter which TransactionAuthors to update
   */
  where?: Prisma.TransactionAuthorWhereInput
  /**
   * Limit how many TransactionAuthors to update.
   */
  limit?: number
}

/**
 * TransactionAuthor updateManyAndReturn
 */
export type TransactionAuthorUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TransactionAuthor
   */
  select?: Prisma.TransactionAuthorSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the TransactionAuthor
   */
  omit?: Prisma.TransactionAuthorOmit<ExtArgs> | null
  /**
   * The data used to update TransactionAuthors.
   */
  data: Prisma.XOR<Prisma.TransactionAuthorUpdateManyMutationInput, Prisma.TransactionAuthorUncheckedUpdateManyInput>
  /**
   * Filter which TransactionAuthors to update
   */
  where?: Prisma.TransactionAuthorWhereInput
  /**
   * Limit how many TransactionAuthors to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TransactionAuthorIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * TransactionAuthor upsert
 */
export type TransactionAuthorUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TransactionAuthor
   */
  select?: Prisma.TransactionAuthorSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TransactionAuthor
   */
  omit?: Prisma.TransactionAuthorOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TransactionAuthorInclude<ExtArgs> | null
  /**
   * The filter to search for the TransactionAuthor to update in case it exists.
   */
  where: Prisma.TransactionAuthorWhereUniqueInput
  /**
   * In case the TransactionAuthor found by the `where` argument doesn't exist, create a new TransactionAuthor with this data.
   */
  create: Prisma.XOR<Prisma.TransactionAuthorCreateInput, Prisma.TransactionAuthorUncheckedCreateInput>
  /**
   * In case the TransactionAuthor was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.TransactionAuthorUpdateInput, Prisma.TransactionAuthorUncheckedUpdateInput>
}

/**
 * TransactionAuthor delete
 */
export type TransactionAuthorDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TransactionAuthor
   */
  select?: Prisma.TransactionAuthorSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TransactionAuthor
   */
  omit?: Prisma.TransactionAuthorOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TransactionAuthorInclude<ExtArgs> | null
  /**
   * Filter which TransactionAuthor to delete.
   */
  where: Prisma.TransactionAuthorWhereUniqueInput
}

/**
 * TransactionAuthor deleteMany
 */
export type TransactionAuthorDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which TransactionAuthors to delete
   */
  where?: Prisma.TransactionAuthorWhereInput
  /**
   * Limit how many TransactionAuthors to delete.
   */
  limit?: number
}

/**
 * TransactionAuthor.transactions
 */
export type TransactionAuthor$transactionsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Transaction
   */
  select?: Prisma.TransactionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Transaction
   */
  omit?: Prisma.TransactionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TransactionInclude<ExtArgs> | null
  where?: Prisma.TransactionWhereInput
  orderBy?: Prisma.TransactionOrderByWithRelationInput | Prisma.TransactionOrderByWithRelationInput[]
  cursor?: Prisma.TransactionWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.TransactionScalarFieldEnum | Prisma.TransactionScalarFieldEnum[]
}

/**
 * TransactionAuthor without action
 */
export type TransactionAuthorDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TransactionAuthor
   */
  select?: Prisma.TransactionAuthorSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TransactionAuthor
   */
  omit?: Prisma.TransactionAuthorOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TransactionAuthorInclude<ExtArgs> | null
}
