
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * WARNING: This is an internal file that is subject to change!
 *
 * 🛑 Under no circumstances should you import this file directly! 🛑
 *
 * All exports from this file are wrapped under a `Prisma` namespace object in the browser.ts file.
 * While this enables partial backward compatibility, it is not part of the stable public API.
 *
 * If you are looking for your Models, Enums, and Input Types, please import them from the respective
 * model files in the `model` directory!
 */

import * as runtime from "@prisma/client/runtime/index-browser"

export type * from '../models'
export type * from './prismaNamespace'

export const Decimal = runtime.Decimal


export const NullTypes = {
  DbNull: runtime.NullTypes.DbNull as (new (secret: never) => typeof runtime.DbNull),
  JsonNull: runtime.NullTypes.JsonNull as (new (secret: never) => typeof runtime.JsonNull),
  AnyNull: runtime.NullTypes.AnyNull as (new (secret: never) => typeof runtime.AnyNull),
}
/**
 * Helper for filtering JSON entries that have `null` on the database (empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const DbNull = runtime.DbNull

/**
 * Helper for filtering JSON entries that have JSON `null` values (not empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const JsonNull = runtime.JsonNull

/**
 * Helper for filtering JSON entries that are `Prisma.DbNull` or `Prisma.JsonNull`
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const AnyNull = runtime.AnyNull


export const ModelName = {
  User: 'User',
  OtpCode: 'OtpCode',
  SignUpSession: 'SignUpSession',
  Household: 'Household',
  HouseholdMember: 'HouseholdMember',
  Account: 'Account',
  Category: 'Category',
  Transaction: 'Transaction',
  TransactionAuthor: 'TransactionAuthor',
  Pot: 'Pot',
  PotContribution: 'PotContribution',
  LinkedBankAccount: 'LinkedBankAccount',
  PlaidTransaction: 'PlaidTransaction'
} as const

export type ModelName = (typeof ModelName)[keyof typeof ModelName]

/*
 * Enums
 */

export const TransactionIsolationLevel = runtime.makeStrictEnum({
  ReadUncommitted: 'ReadUncommitted',
  ReadCommitted: 'ReadCommitted',
  RepeatableRead: 'RepeatableRead',
  Serializable: 'Serializable'
} as const)

export type TransactionIsolationLevel = (typeof TransactionIsolationLevel)[keyof typeof TransactionIsolationLevel]


export const UserScalarFieldEnum = {
  id: 'id',
  name: 'name',
  email: 'email',
  passwordHash: 'passwordHash',
  emailVerified: 'emailVerified',
  job: 'job',
  annualWage: 'annualWage',
  businessName: 'businessName',
  selectedBanks: 'selectedBanks',
  createdAt: 'createdAt'
} as const

export type UserScalarFieldEnum = (typeof UserScalarFieldEnum)[keyof typeof UserScalarFieldEnum]


export const OtpCodeScalarFieldEnum = {
  id: 'id',
  email: 'email',
  code: 'code',
  expiresAt: 'expiresAt',
  createdAt: 'createdAt',
  userId: 'userId'
} as const

export type OtpCodeScalarFieldEnum = (typeof OtpCodeScalarFieldEnum)[keyof typeof OtpCodeScalarFieldEnum]


export const SignUpSessionScalarFieldEnum = {
  id: 'id',
  email: 'email',
  name: 'name',
  passwordHash: 'passwordHash',
  job: 'job',
  annualWage: 'annualWage',
  businessName: 'businessName',
  selectedBanks: 'selectedBanks',
  expiresAt: 'expiresAt',
  createdAt: 'createdAt'
} as const

export type SignUpSessionScalarFieldEnum = (typeof SignUpSessionScalarFieldEnum)[keyof typeof SignUpSessionScalarFieldEnum]


export const HouseholdScalarFieldEnum = {
  id: 'id',
  name: 'name',
  createdAt: 'createdAt',
  ownerId: 'ownerId'
} as const

export type HouseholdScalarFieldEnum = (typeof HouseholdScalarFieldEnum)[keyof typeof HouseholdScalarFieldEnum]


export const HouseholdMemberScalarFieldEnum = {
  id: 'id',
  name: 'name',
  relationship: 'relationship',
  color: 'color',
  createdAt: 'createdAt',
  householdId: 'householdId'
} as const

export type HouseholdMemberScalarFieldEnum = (typeof HouseholdMemberScalarFieldEnum)[keyof typeof HouseholdMemberScalarFieldEnum]


export const AccountScalarFieldEnum = {
  id: 'id',
  name: 'name',
  institution: 'institution',
  kind: 'kind',
  ownerType: 'ownerType',
  isBusiness: 'isBusiness',
  balance: 'balance',
  currency: 'currency',
  createdAt: 'createdAt',
  householdId: 'householdId',
  ownerId: 'ownerId'
} as const

export type AccountScalarFieldEnum = (typeof AccountScalarFieldEnum)[keyof typeof AccountScalarFieldEnum]


export const CategoryScalarFieldEnum = {
  id: 'id',
  name: 'name',
  icon: 'icon',
  color: 'color'
} as const

export type CategoryScalarFieldEnum = (typeof CategoryScalarFieldEnum)[keyof typeof CategoryScalarFieldEnum]


export const TransactionScalarFieldEnum = {
  id: 'id',
  date: 'date',
  amount: 'amount',
  description: 'description',
  merchant: 'merchant',
  isBusiness: 'isBusiness',
  createdAt: 'createdAt',
  accountId: 'accountId',
  categoryId: 'categoryId',
  authorId: 'authorId'
} as const

export type TransactionScalarFieldEnum = (typeof TransactionScalarFieldEnum)[keyof typeof TransactionScalarFieldEnum]


export const TransactionAuthorScalarFieldEnum = {
  id: 'id',
  memberId: 'memberId'
} as const

export type TransactionAuthorScalarFieldEnum = (typeof TransactionAuthorScalarFieldEnum)[keyof typeof TransactionAuthorScalarFieldEnum]


export const PotScalarFieldEnum = {
  id: 'id',
  name: 'name',
  icon: 'icon',
  color: 'color',
  targetAmount: 'targetAmount',
  currentAmount: 'currentAmount',
  createdAt: 'createdAt',
  householdId: 'householdId'
} as const

export type PotScalarFieldEnum = (typeof PotScalarFieldEnum)[keyof typeof PotScalarFieldEnum]


export const PotContributionScalarFieldEnum = {
  id: 'id',
  amount: 'amount',
  date: 'date',
  potId: 'potId',
  memberId: 'memberId'
} as const

export type PotContributionScalarFieldEnum = (typeof PotContributionScalarFieldEnum)[keyof typeof PotContributionScalarFieldEnum]


export const LinkedBankAccountScalarFieldEnum = {
  id: 'id',
  plaidItemId: 'plaidItemId',
  bankName: 'bankName',
  accountName: 'accountName',
  accountNumber: 'accountNumber',
  balance: 'balance',
  currency: 'currency',
  plaidAccessToken: 'plaidAccessToken',
  lastSync: 'lastSync',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  userId: 'userId'
} as const

export type LinkedBankAccountScalarFieldEnum = (typeof LinkedBankAccountScalarFieldEnum)[keyof typeof LinkedBankAccountScalarFieldEnum]


export const PlaidTransactionScalarFieldEnum = {
  id: 'id',
  plaidTransactionId: 'plaidTransactionId',
  date: 'date',
  amount: 'amount',
  description: 'description',
  merchant: 'merchant',
  category: 'category',
  createdAt: 'createdAt',
  linkedAccountId: 'linkedAccountId'
} as const

export type PlaidTransactionScalarFieldEnum = (typeof PlaidTransactionScalarFieldEnum)[keyof typeof PlaidTransactionScalarFieldEnum]


export const SortOrder = {
  asc: 'asc',
  desc: 'desc'
} as const

export type SortOrder = (typeof SortOrder)[keyof typeof SortOrder]


export const QueryMode = {
  default: 'default',
  insensitive: 'insensitive'
} as const

export type QueryMode = (typeof QueryMode)[keyof typeof QueryMode]


export const NullsOrder = {
  first: 'first',
  last: 'last'
} as const

export type NullsOrder = (typeof NullsOrder)[keyof typeof NullsOrder]

