
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file should be your main import to use Prisma-related types and utilities in a browser. 
 * Use it to get access to models, enums, and input types.
 * 
 * This file does not contain a `PrismaClient` class, nor several other helpers that are intended as server-side only.
 * See `client.ts` for the standard, server-side entry point.
 *
 * 🟢 You can import this file directly.
 */

import * as Prisma from './internal/prismaNamespaceBrowser'
export { Prisma }
export * as $Enums from './enums'
export * from './enums';
/**
 * Model User
 * 
 */
export type User = Prisma.UserModel
/**
 * Model OtpCode
 * 
 */
export type OtpCode = Prisma.OtpCodeModel
/**
 * Model SignUpSession
 * 
 */
export type SignUpSession = Prisma.SignUpSessionModel
/**
 * Model Household
 * 
 */
export type Household = Prisma.HouseholdModel
/**
 * Model HouseholdMember
 * 
 */
export type HouseholdMember = Prisma.HouseholdMemberModel
/**
 * Model Account
 * 
 */
export type Account = Prisma.AccountModel
/**
 * Model Category
 * 
 */
export type Category = Prisma.CategoryModel
/**
 * Model Transaction
 * 
 */
export type Transaction = Prisma.TransactionModel
/**
 * Model TransactionAuthor
 * 
 */
export type TransactionAuthor = Prisma.TransactionAuthorModel
/**
 * Model Pot
 * 
 */
export type Pot = Prisma.PotModel
/**
 * Model PotContribution
 * 
 */
export type PotContribution = Prisma.PotContributionModel
/**
 * Model LinkedBankAccount
 * 
 */
export type LinkedBankAccount = Prisma.LinkedBankAccountModel
/**
 * Model PlaidTransaction
 * 
 */
export type PlaidTransaction = Prisma.PlaidTransactionModel
