
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
* This file exports all enum related types from the schema.
*
* 🟢 You can import this file directly.
*/

export const AccountKind = {
  CHECKING: 'CHECKING',
  SAVINGS: 'SAVINGS',
  CREDIT_CARD: 'CREDIT_CARD',
  INVESTMENT: 'INVESTMENT',
  LOAN: 'LOAN',
  CASH: 'CASH'
} as const

export type AccountKind = (typeof AccountKind)[keyof typeof AccountKind]


export const AccountOwnerType = {
  PERSONAL: 'PERSONAL',
  JOINT: 'JOINT',
  BUSINESS: 'BUSINESS'
} as const

export type AccountOwnerType = (typeof AccountOwnerType)[keyof typeof AccountOwnerType]


export const MemberRelationship = {
  YOURSELF: 'YOURSELF',
  PARTNER: 'PARTNER',
  SPOUSE: 'SPOUSE',
  FAMILY: 'FAMILY',
  OTHER: 'OTHER'
} as const

export type MemberRelationship = (typeof MemberRelationship)[keyof typeof MemberRelationship]
